### ISSUE TITLE
java.lang.NullPointerException occurs when we open a css file.

### ISSUE THREAD

**Issue by junichi11** [apache/netbeans#3593]
### Apache NetBeans version

Latest release candidate

### What happened

java.lang.NullPointerException occurs when we open a css file.

```
java.lang.NullPointerException
	at org.netbeans.modules.csl.navigation.ElementNode.getNodeForOffset(ElementNode.java:245)
	at org.netbeans.modules.csl.navigation.ElementNode.getMimeRootNodeForOffset(ElementNode.java:230)
	at org.netbeans.modules.csl.navigation.ElementNode.getMimeRootNodeForOffset(ElementNode.java:202)
	at org.netbeans.modules.csl.navigation.ClassMemberPanelUI.doSelectNodes0(ClassMemberPanelUI.java:263)
	at org.netbeans.modules.csl.navigation.ClassMemberPanelUI.access$500(ClassMemberPanelUI.java:74)
	at org.netbeans.modules.csl.navigation.ClassMemberPanelUI$3.run(ClassMemberPanelUI.java:254)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1074)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1124)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1096)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:106)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:123)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:77)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1081)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$1AWTQuery.showDialog(DialogDisplayerImpl.java:244)
	at org.netbeans.core.windows.services.DialogDisplayerImpl.notify(DialogDisplayerImpl.java:260)
	at org.netbeans.core.windows.services.DialogDisplayerImpl.notify(DialogDisplayerImpl.java:148)
	at org.netbeans.modules.project.ui.problems.BrokenReferencesImpl$1.run(BrokenReferencesImpl.java:107)
	at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1601)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.lambda$doEventRequest$1(NbMutexEventProvider.java:112)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### How to reproduce

1. Create a css file.
2. Write the following code.
```css
.test {
}
```
3. java.lang.NullPointerException occurs

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Ubuntu 20.4

### JDK

Java: 1.8.0_202;

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by junichi11** [comment]
This is related to https://github.com/apache/netbeans/pull/3327.

We don't expect that `StructureItem.getElementHandle()` returns `null`.
https://github.com/apache/netbeans/blob/aa1f69f3fb50defdda5aab682275d35be49557fa/ide/csl.api/src/org/netbeans/modules/csl/api/StructureItem.java#L36

However, `TopLevelStructureItem.getElementHandle()` returns `null`.
https://github.com/apache/netbeans/blob/aa1f69f3fb50defdda5aab682275d35be49557fa/ide/css.editor/src/org/netbeans/modules/css/editor/module/main/TopLevelStructureItem.java#L52-L55

**Comment by junichi11** [comment]
@matthiasblaesing Could you please have a look at this?

**Comment by neilcsmith-net** [comment]
@junichi11 we can definitely consider it so if you (and @matthiasblaesing ) want to make that call.  Looks like a good one to fix!  We can roll another RC this week if we can get a PR in.  Maybe mention it on dev@ too.  cc/ @ebarboni @geertjanw

**Comment by junichi11** [comment]
@neilcsmith-net 

> Maybe mention it on dev@ too

OK, I'll do it.

Thank you!

**Comment by junichi11** [comment]
@matthiasblaesing Thank you for fixing it!
