### ISSUE TITLE
Bug/ thrown exceptions when creating and managing project of type "Enterprise Application" (Java with Ant)

### ISSUE THREAD

**Issue by asimonsy** [apache/netbeans#3609]
### Apache NetBeans version

Latest release

### What happened

NetBeans 12.6
JDK: OpenJDK 17.0.1
AppServer: GlassFish 6.2.5 (Jakarta EE 9)

When creating a new "Enterprise Application"-Project (Ant Project) and clicking on "Finish":
The create dialog doesn't close.
The new project is created in the file system but it is not automatically opened in NetBeans.
It throws the following Exception in NetBeans:

```
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.j2ee.dd.api.application.Application.setDisplayName(String)" because "this.application" is null
	at org.netbeans.modules.j2ee.earproject.ProjectEar.setupDDFromVirtual(ProjectEar.java:290)
	at org.netbeans.modules.j2ee.earproject.ProjectEar.getApplication(ProjectEar.java:255)
	at org.netbeans.modules.j2ee.earproject.ui.wizards.NewEarProjectWizardIterator.testableInstantiate(NewEarProjectWizardIterator.java:160)
	at org.netbeans.modules.j2ee.earproject.ui.wizards.NewEarProjectWizardIterator.instantiate(NewEarProjectWizardIterator.java:139)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1048)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.netbeans.modules.project.ui.NewProjectWizard.handleInstantiate(NewProjectWizard.java:51)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:228)
	at org.openide.loaders.TemplateWizardIteratorWrapper$ProgressInstantiatingIterator.instantiate(TemplateWizardIteratorWrapper.java:155)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1602)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

Additionally:
When opening the newly created Enterprise Application project from above and trying to add a module, e.g. EJB module, to "Java EE Modules" in the "Add Java EE Module" dialog the following happens:
The dialog is closed, but the module is not added.

The following exception is thrown in NetBeans:

```
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.j2ee.dd.api.application.Application.setDisplayName(String)" because "this.application" is null
	at org.netbeans.modules.j2ee.earproject.ProjectEar.setupDDFromVirtual(ProjectEar.java:290)
	at org.netbeans.modules.j2ee.earproject.ProjectEar.getApplication(ProjectEar.java:255)
	at org.netbeans.modules.j2ee.earproject.ui.customizer.EarProjectProperties.updateContentDependency(EarProjectProperties.java:449)
	at org.netbeans.modules.j2ee.earproject.ui.customizer.EarProjectProperties$5.run(EarProjectProperties.java:749)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.writeAccess(DefaultMutexImplementation.java:213)
	at org.openide.util.Mutex.writeAccess(Mutex.java:291)
	at org.netbeans.modules.j2ee.earproject.ui.customizer.EarProjectProperties.addRemoveJ2eeSubprojects(EarProjectProperties.java:718)
	at org.netbeans.modules.j2ee.earproject.ui.customizer.EarProjectProperties.addJ2eeSubprojects(EarProjectProperties.java:710)
	at org.netbeans.modules.j2ee.earproject.ui.actions.AddModuleAction.performAction(AddModuleAction.java:78)
	at org.openide.util.actions.NodeAction$DelegateAction$1.run(NodeAction.java:561)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.util.actions.NodeAction$DelegateAction.actionPerformed(NodeAction.java:558)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### How to reproduce

See above.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 10

### JDK

Java 17.0.1+12-LTS-39

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by lkishalmi** [comment]
@geertjanw @neilcsmith-net Shall we retire the EAR support in upcoming NB releases?

**Comment by lkishalmi** [comment]
@asimonsy I'd better to create a Simple Web application instead.

**Comment by matthiasblaesing** [comment]
@lkishalmi why would two people decide that? There might be a bug, maybe just a conflict between JDK 17 and the app server, lets not jump to conclusions. I'm not aware, that EARs are removed from JakartaEE.

**Comment by matthiasblaesing** [comment]
The problem is Jakarta 9 (or the lack of full support for this). There was some work to get it supported, but it is not fully there.

@asimonsy in the wizard you are asked for which Java EE version you want to generate the application. Please choose JavaEE 8, 9 is broken.

**Comment by neilcsmith-net** [comment]
Agree with @matthiasblaesing on the decision making, and I have nothing to input on this as it's an area of the IDE I never use (haven't touched anything in the enterprise cluster except for testing in 5+ yrs).

**Comment by pepness** [comment]
It works with PR-4438
- Create EAR
- Create deployment descriptors
- Create EJB Singleton
- Clean, build and Run
![Screenshot from 2022-07-30 11-45-42](https://user-images.githubusercontent.com/9832133/181933576-d0e21d5e-0870-46a0-8ad3-2b7fdff139e5.png)
