### ISSUE TITLE
Maven threaded build output

### ISSUE THREAD

**Issue by cbm64chris** [apache/netbeans#3675]
### Apache NetBeans version

Apache NetBeans 13 release candidate

### What happened

When the maven option of -T is configured in a multi-module reactor, in my example in the ```.mvn/maven.config```, the output window loses track of the folding and this throws;

```
java.lang.NullPointerException: Cannot invoke "org.openide.windows.FoldHandle.silentStartFold(boolean)" because "parentProject.foldHandle" is null
	at org.netbeans.modules.maven.execute.cmd.ExecutionEventObject$Tree.startFold(ExecutionEventObject.java:179)
	at org.netbeans.modules.maven.execute.CommandLineOutputHandler$Output.run(CommandLineOutputHandler.java:352)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

The build continues in the background but the output is stalled.

I am using a maven pom that contains significant number of plugins that are run for each member module. 

### How to reproduce

* Create a multi-module reactor
* Configure to build in parallel
* Run using Clean & Build control

### Did this work correctly in an earlier version?

No

### Operating System

Mac OS X version 12.2.1 running on x86_64

### JDK

OpenJDK Runtime Environment 17.0.2+8-LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Code of Conduct

Yes

**Comment by jglick** [comment]
Long broken. Happens in 16-rc3 when running SpotBugs in a multimodule reactor using mvnd.

**Comment by jglick** [comment]
Long broken. Can be reproduced in trunk (running IDE on Java 17 if it matters):
* Configure the Maven executable to be mvnd (0.8.2, running on Java 11 if it matters).
* Configure non-test Maven executions to pass `-DskipTests`.
* Check out & open https://github.com/jenkinsci/jenkins.
* Clean & build. Error is thrown and log stops after
```
…
[cli] 
[cli] 
[cli] [INFO] 
[cli] [INFO] --- maven-checkstyle-plugin:3.2.0:check (validate) @ cli ---
[jenkins-bom] 
[jenkins-bom] 
[jenkins-bom] [INFO] 
[jenkins-bom] [INFO] >>> spotbugs-maven-plugin:4.7.2.1:check (spotbugs) > :spotbugs @ jenkins-bom >>>

--- spotbugs-maven-plugin:4.7.2.1:spotbugs (spotbugs) @ jenkins-bom ---
```

Has something to do with the forked execution of https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html.

Unfortunately the obvious quick fixes like

```diff
diff --git java/maven/src/org/netbeans/modules/maven/execute/cmd/ExecutionEventObject.java java/maven/src/org/netbeans/modules/maven/execute/cmd/ExecutionEventObject.java
index 06f23c7faf..0e310e783c 100644
--- java/maven/src/org/netbeans/modules/maven/execute/cmd/ExecutionEventObject.java
+++ java/maven/src/org/netbeans/modules/maven/execute/cmd/ExecutionEventObject.java
@@ -175,7 +175,9 @@ public class ExecutionEventObject {
             ExecutionEventObject.Tree parentProject = findParentNodeOfType(ExecutionEvent.Type.MojoStarted);
             if (parentProject != null) {
                 //in forked environment..
-                assert parentProject.foldHandle != null;
+                if (parentProject.foldHandle == null) {
+                    return;
+                }
                 this.foldHandle = parentProject.foldHandle.silentStartFold(true);
                 return;
             }
```

do not work—you just get NPEs later from a variety of other methods here or in `CommandLineOutputHandler`. There is a lot of complex, sparsely commented logic here with numerous unchecked accesses to supposedly nullable fields, and no test coverage that I can find. Other than a small patch in #2309, the code all seems to predate the Apache donation.
