### ISSUE TITLE
Maven: cannot create Java EE 5 Web Project

### ISSUE THREAD

**Issue by NicolaIsotta** [apache/netbeans#3681]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

When trying to create a Java EE 5 web project with Maven, an exception is raised and creation fails.
Link to Jira: https://issues.apache.org/jira/browse/NETBEANS-5585

### How to reproduce

New Project > [Java with Maven] > [Web Application] > Next

Choose a name then > Next

Select [Java EE 5] then > Finish

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10, Windows 11

### JDK

Java: 11.0.13; Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

```
java.lang.IllegalStateException: No archetype defined for profile 1.5 in class org.netbeans.modules.maven.j2ee.ui.wizard.archetype.J2eeArchetypeFactory$WebArchetypes; check whether all possible <Profile, Archetype> pairs have been added
	at org.netbeans.modules.maven.j2ee.ui.wizard.archetype.BaseJ2eeArchetypeProvider.getArchetypeFor(BaseJ2eeArchetypeProvider.java:135)
	at org.netbeans.modules.maven.j2ee.ui.wizard.archetype.J2eeArchetypeFactory.findArchetypeFor(J2eeArchetypeFactory.java:79)
	at org.netbeans.modules.maven.j2ee.ui.wizard.EEWizardIterator.instantiate(EEWizardIterator.java:102)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1050)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.netbeans.modules.project.ui.NewProjectWizard.handleInstantiate(NewProjectWizard.java:51)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:223)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:135)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1605)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by NicolaIsotta** [comment]
Seems like some archetypes have been commented out:
https://github.com/apache/netbeans/blob/5a9c949e8e4e2820109de064f4c2b501dcb49242/enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/J2eeArchetypeFactory.java#L148-L149
The commit is https://github.com/apache/netbeans/commit/3e7e6fe67a0e03f66ec8d86e470042af29494556 in #1298
Is there a reason why those archetypes were commented out @juneau001 ?

**Comment by juneau001** [comment]
> Seems like some archetypes have been commented out:
> 
> https://github.com/apache/netbeans/blob/5a9c949e8e4e2820109de064f4c2b501dcb49242/enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/J2eeArchetypeFactory.java#L148-L149
> 
> 
> The commit is [3e7e6fe](https://github.com/apache/netbeans/commit/3e7e6fe67a0e03f66ec8d86e470042af29494556) in #1298
> Is there a reason why those archetypes were commented out @juneau001 ?

Unfortunately, I am not sure exactly why these were commented out.  It may have been by mistake for testing purposes, or it may be because they were no longer working correctly and out of support.  I will see if I can uncomment and build/run without issues.

**Comment by mbien** [comment]
i am pretty sure EE 5 is EOL, no?

I checked with NB 22 and EE 6 did still work. Wondering if we should simply remove the entry for 5. cc @matthiasblaesing

**Comment by matthiasblaesing** [comment]
The archetypes are present and the result from the JavaEE 1.5 one looks sane to me. So I pushed a PR that readds them.

For the EOL part: I would say JavaEE as a whole is EOL. Oracle did a pretty good job at destroying it. Lets hope JakartaEE has a good future.
