### ISSUE TITLE
Code template expansion with 'forc' causes NetBeans to hang

### ISSUE THREAD

**Issue by ChristianPervoelz** [apache/netbeans#3803]
### Apache NetBeans version

Apache NetBeans 13

### What happened

It was tried to write a simple loop using iterators on a collection.
Typing _forc_ followed by the tab key should expand to 
```
for (Iterator<E> iterator = c.iterator(); iterator.hasNext();) {
  E next = iterator.next();
     
}
```
but actually let NetBeans hang up.
Even several minutes of waiting does not clean up the situation.

### How to reproduce

1. Create a class with a single method like this: (the type of modifiers do not matter)
```
public class MyClass<E> {

  public boolean aMethod(Collection<? extends E> c) {
     
  }
}
```

2. Type `forc` into the method block and press the tab key.

NetBeans will hang now.

**Note**
This happens only if `? extends E` is used.
The same method, but using `Collection<E>` as parameter only will cause no problems.

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

Windows 11

### JDK

OpenJDK 16

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Issues is reproducible constantly.

I don't know for sure in which version this problem occurred first or in which version it worked last, but I'm pretty sure it has been working properly in 12.4 at least.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
this doesn't appear to be a locking/concurrency problem, it looks like a infinite loop locking up the EDT while it keeps running. 
I am not sure if this should be on the EDT on the first place, but this wouldn't solve the issue anyway. @jlahoda @dbalek any thoughts?

some thread dumps after it freezes from mouse click (on the iterator completion) and up:

```
 "AWT-EventQueue-0" - Thread t@30
    java.lang.Thread.State: RUNNABLE
    at java.base@17.0.2/java.lang.Throwable.fillInStackTrace(Native Method)
    at java.base@17.0.2/java.lang.Throwable.fillInStackTrace(Throwable.java:798)
    - locked <30a68cd8> (a com.sun.tools.javac.code.Symbol$CompletionFailure)
    at java.base@17.0.2/java.lang.Throwable.<init>(Throwable.java:256)
    at java.base@17.0.2/java.lang.Exception.<init>(Exception.java:55)
    at java.base@17.0.2/java.lang.RuntimeException.<init>(RuntimeException.java:52)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.Symbol$CompletionFailure.<init>(Symbol.java:2552)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:408)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:395)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:390)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:291)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.ClassFinder$$Lambda$479/0x00000008015c30c8.complete(Unknown Source)
    at org.netbeans.lib.nbjavac.services.NBClassFinder.lambda$getCompleter$1(NBClassFinder.java:95)
    at org.netbeans.lib.nbjavac.services.NBClassFinder$$Lambda$483/0x00000008015a1630.complete(Unknown Source)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.Symbol.complete(Symbol.java:682)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1410)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.code.ClassFinder.loadClass(ClassFinder.java:434)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:2052)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Resolve.findIdentInPackageInternal(Resolve.java:2450)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:2438)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.selectSym(Attr.java:4412)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:4297)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2450)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:4269)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2450)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribType(Attr.java:743)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribType(Attr.java:736)
    at org.netbeans.lib.nbjavac.services.NBAttr.attribType(NBAttr.java:91)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.MemberEnter.visitVarDef(MemberEnter.java:265)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1027)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:163)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1273)
    at org.netbeans.lib.nbjavac.services.NBAttr.visitVarDef(NBAttr.java:85)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1027)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
    at org.netbeans.lib.nbjavac.services.NBAttr.visitBlock(NBAttr.java:78)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitForLoop(Attr.java:1506)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCForLoop.accept(JCTree.java:1191)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
    at org.netbeans.lib.nbjavac.services.NBAttr.visitBlock(NBAttr.java:78)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:500)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribToTree(Attr.java:429)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStatToTree(Attr.java:422)
    at org.netbeans.lib.nbjavac.services.NBAttr.attributeAndCapture(NBAttr.java:140)
    at org.netbeans.api.java.source.TreeUtilities.attributeTreeTo(TreeUtilities.java:930)
    at org.netbeans.api.java.source.TreeUtilities.attributeTreeTo(TreeUtilities.java:841)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.newVarName(JavaCodeTemplateProcessor.java:918)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.getProposedValue(JavaCodeTemplateProcessor.java:516)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.updateDefaultValues(JavaCodeTemplateProcessor.java:147)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateInsertHandler.processTemplate(CodeTemplateInsertHandler.java:225)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateManagerOperation.insert(CodeTemplateManagerOperation.java:273)
    at org.netbeans.lib.editor.codetemplates.api.CodeTemplate.insert(CodeTemplate.java:82)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateCompletionItem.defaultAction(CodeTemplateCompletionItem.java:115)
    at org.netbeans.modules.editor.completion.CompletionLayout$CompletionPopup$1.mouseClicked(CompletionLayout.java:405)
    at java.desktop@17.0.2/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
```

```
  
 "AWT-EventQueue-0" - Thread t@30
    java.lang.Thread.State: RUNNABLE
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.util.IntHashTable.put(IntHashTable.java:127)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser$SimpleEndPosTable.storeEnd(JavacParser.java:4933)
    at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser$EndPosTableImpl.storeEnd(NBParserFactory.java:166)
    at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser$EndPosTableImpl.toP(NBParserFactory.java:183)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.toP(JavacParser.java:539)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.term3Rest(JavacParser.java:1630)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.term3(JavacParser.java:1490)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.term2(JavacParser.java:929)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.term1(JavacParser.java:900)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:856)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:836)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.forInit(JavacParser.java:3160)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.parseSimpleStatement(JavacParser.java:2796)
    at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser.parseSimpleStatement(NBParserFactory.java:134)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2632)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.blockStatements(JavacParser.java:2569)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.block(JavacParser.java:2539)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.block(JavacParser.java:2553)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.parseSimpleStatement(JavacParser.java:2781)
    at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser.parseSimpleStatement(NBParserFactory.java:134)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2632)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.parseStatementAsBlock(JavacParser.java:2594)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2933)
    at org.netbeans.api.java.source.TreeUtilities$$Lambda$764/0x0000000801956420.apply(Unknown Source)
    at org.netbeans.api.java.source.TreeUtilities.doParse(TreeUtilities.java:694)
    at org.netbeans.api.java.source.TreeUtilities.parseStatementImpl(TreeUtilities.java:622)
    at org.netbeans.api.java.source.TreeUtilities.parseStatement(TreeUtilities.java:618)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.assignmentSideType(JavaCodeTemplateProcessor.java:810)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.getProposedValue(JavaCodeTemplateProcessor.java:482)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.updateDefaultValues(JavaCodeTemplateProcessor.java:147)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateInsertHandler.processTemplate(CodeTemplateInsertHandler.java:225)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateManagerOperation.insert(CodeTemplateManagerOperation.java:273)
    at org.netbeans.lib.editor.codetemplates.api.CodeTemplate.insert(CodeTemplate.java:82)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateCompletionItem.defaultAction(CodeTemplateCompletionItem.java:115)
    at org.netbeans.modules.editor.completion.CompletionLayout$CompletionPopup$1.mouseClicked(CompletionLayout.java:405)
    at java.desktop@17.0.2/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)

```


```
 "AWT-EventQueue-0" - Thread t@30
    java.lang.Thread.State: RUNNABLE
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2567)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1797)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:723)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1314)
    at org.netbeans.lib.nbjavac.services.NBAttr.visitVarDef(NBAttr.java:85)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1027)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitForLoop(Attr.java:1496)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCForLoop.accept(JCTree.java:1191)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
    at org.netbeans.lib.nbjavac.services.NBAttr.visitBlock(NBAttr.java:78)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
    at app/jdk.compiler@17.0.2/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
    at org.netbeans.api.java.source.TreeUtilities.attributeTree(TreeUtilities.java:892)
    at org.netbeans.api.java.source.TreeUtilities.attributeTree(TreeUtilities.java:826)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.assignmentSideType(JavaCodeTemplateProcessor.java:819)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.getProposedValue(JavaCodeTemplateProcessor.java:482)
    at org.netbeans.modules.editor.java.JavaCodeTemplateProcessor.updateDefaultValues(JavaCodeTemplateProcessor.java:147)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateInsertHandler.processTemplate(CodeTemplateInsertHandler.java:225)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateManagerOperation.insert(CodeTemplateManagerOperation.java:273)
    at org.netbeans.lib.editor.codetemplates.api.CodeTemplate.insert(CodeTemplate.java:82)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateCompletionItem.defaultAction(CodeTemplateCompletionItem.java:115)
    at org.netbeans.modules.editor.completion.CompletionLayout$CompletionPopup$1.mouseClicked(CompletionLayout.java:405)
    at java.desktop@17.0.2/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)

```

**Comment by jlahoda** [comment]
Hm, `updateDefaultValues` updates the values until they stabilize, but they don't stabilize, because the type for `IT_TYPE` oscillates between `java.util.Iterator` and `java.util.Iterator<? extends <nulltype>>` (which is obviously broken). The reason is probably captured type handling. Will try to take a look, unless @dbalek does.
