### ISSUE TITLE
NetBeans 13 stops when start and compile the project

### ISSUE THREAD

**Issue by dyegocarmo** [apache/netbeans#3842]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I'm installed NetBeans 13, and import configurations of 12.5.

When i start the netbeans, it recreates the cache, but STOP with this message:

 

```
java.lang.IllegalArgumentException: newPosition > limit: (1 > 0)
    at java.base/java.nio.Buffer.createPositionException(Buffer.java:341)
    at java.base/java.nio.Buffer.position(Buffer.java:316)
    at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1516)
    at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:622)
    at org.netbeans.api.queries.FileEncodingQuery$ProxyCharset$ProxyDecoder.decodeLoop(FileEncodingQuery.java:191)
    at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:585)
Caused: java.nio.charset.CoderMalfunctionError
    at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:587)
    at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:305)
    at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
    at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
    at org.netbeans.modules.parsing.api.Source.createSnapshot(Source.java:360)
    at org.netbeans.modules.parsing.impl.SourceCache.createSnapshot(SourceCache.java:157)
    at org.netbeans.modules.parsing.impl.SourceCache.getSnapshot(SourceCache.java:132)
    at org.netbeans.modules.parsing.api.ResultIterator.getSnapshot(ResultIterator.java:86)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1T.run(RepositoryUpdater.java:3192)
    at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
    at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
    at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
    at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
    at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
    at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
    at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
    at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
    at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
    at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
    at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.indexEmbedding(RepositoryUpdater.java:3281)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2860)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2625)
    at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2624)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.lambda$scanSource$3(RepositoryUpdater.java:5747)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2118)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2116)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2097)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1400(RepositoryUpdater.java:134)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5782)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5455)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5087)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5854)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3464)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6209)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$3400(RepositoryUpdater.java:5867)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6128)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
    at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6128)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6124)
    at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
    at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
    at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
    at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
    at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6124)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### How to reproduce

Create a large project and open inside netbeans 13 (from netbeans 12.5)

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

Windows 10 and 11

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by sdedic** [comment]
This is not a symptom of a large project, but possibly of a file with broken encoding = invalid character. But also bug in the lazy-evaluated encoding. It would be hard to decide without the specific file.
Could you please run NetBeans IDE with the following argument on the commandline:
`-J-Dorg.netbeans.api.queries.FileEncodingQuery.level=400`
?
It should log a bunch of messages from the encoding evaluation impl, and the culprit filename should precede the exception.

**Comment by dyegocarmo** [comment]
Hi!
I try to add this option in my netbeans.conf, restart the NetBeans and the same error (without any addtional information) occurs...

Any ideia to "discovery" this file with charset error?

**Comment by sdedic** [comment]
> Any ideia to "discovery" this file with charset error?

Log messages do not pop into the exc. dialog - locate the file(s) `var/log/messages*` in your userdir (see Help | About, the bottom box for the location) or cachedir (perhaps something like `C:\Users\<username>\AppData\Local\NetBeans\Cache\` -- I don't use Windows, sorry). 
There should be a plenty of messages like
```
FINER [org.netbeans.api.queries.FileEncodingQuery]: /space/src/nb/scratch/p/pom.xml@dae97c1a:694d6eb7: received no encoding from org.netbeans.modules.diff.DiffFileEncodingQueryImplementation@1e51b088
FINE [org.netbeans.api.queries.FileEncodingQuery]: /space/src/nb/scratch/p/pom.xml@dae97c1a:694d6eb7: using encodings [UTF-8, UTF-8, ISO-8859-1]
```

**Comment by mbien** [comment]
looks like a duplicate of #4354 which has a reproducer attached
