### ISSUE TITLE
Apache NetBeans 13 JDK 18 fail to fully load.

### ISSUE THREAD

**Issue by TDClarke** [apache/netbeans#3946]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Fails to load after showing loading modules on status bar.

### How to reproduce

Double click on desktop shortcut.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10 Home Edition

### JDK

JDK 18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This only happens in Apache NetBeans 13 and not previous instillations.

Tried removing all java instillations removing NetBeans and reinstalling, still having the same issue of not loading.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by TDClarke** [comment]
Still occurs in jdk 17

**Comment by emaphis** [comment]
Try running your Nebeans 13 installation from the command prompt. That might give you a clue about what's going on.

**Comment by TDClarke** [comment]
The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
WARNING: package sun.awt.X11 not in java.desktop
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
java.lang.IllegalStateException: Missing hosting module org.netbeans.libs.javacimpl for fragment org.netbeans.modules.nbjavac.impl
        at org.netbeans.ModuleManager.refineClassLoader(ModuleManager.java:909)
        at org.netbeans.StandardModule.classLoaderUp(StandardModule.java:527)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1330)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
        at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
        at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
        at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
        at org.netbeans.core.startup.Main.start(Main.java:282)
        at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by matthiasblaesing** [comment]
I saw this artifact when using an old userdir with NetBeans master. Given that you used a release version, I assume you imported all old modules into your new installation. This includes an old implementation of nbjavac, which must not be imported.

If you know your way around the userdir, remove the nbjavac module, if not, delete the userdir.

**Comment by TDClarke** [comment]
Yes that works, perhaps the installer could check this on install if it's a recurring problem?
