### ISSUE TITLE
java.lang.NullPointerException at org.netbeans.modules.java.source.ui.LspElementUtils.processOffsetInfo

### ISSUE THREAD

**Issue by timfel** [apache/netbeans#3967]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Opening any document in emacs lsp in the latest version gives this error:
```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl$$Lambda$234/683895263
java.lang.NullPointerException
	at org.netbeans.modules.java.source.ui.LspElementUtils.processOffsetInfo(LspElementUtils.java:297)
	at org.netbeans.modules.java.source.ui.LspElementUtils.setOffsets(LspElementUtils.java:355)
	at org.netbeans.modules.java.source.ui.LspElementUtils.element2StructureElement(LspElementUtils.java:83)
	at org.netbeans.modules.java.source.ui.LspElementUtils.element2StructureElement(LspElementUtils.java:127)
	at org.netbeans.api.java.source.ui.ElementHeaders.toStructureElement(ElementHeaders.java:215)
	at org.netbeans.modules.editor.java.JavaStructureProvider.element2StructureElement(JavaStructureProvider.java:97)
	at org.netbeans.modules.editor.java.JavaStructureProvider.lambda$getStructure$0(JavaStructureProvider.java:75)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.editor.java.JavaStructureProvider.getStructure(JavaStructureProvider.java:60)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.lambda$documentSymbol$20(TextDocumentServiceImpl.java:829)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### How to reproduce

Open any Java file using lsp-netbeans in emacs.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Ubuntu 18.04

### JDK

GraalVM 22.0 JDK17

### Apache NetBeans packaging

Other

### Anything else

Every time I open a document.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by sdedic** [comment]
Got something similar, although not the same stacktrace. NPE in `processOffsetInfo`.
