### ISSUE TITLE
Unexpected exception in org.netbeans.modules.parsing.spi.ParseException

### ISSUE THREAD

**Issue by mtbadi39** [apache/netbeans#4000]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Unexpected exception was thrown when opening xhtml or js file for editing

### How to reproduce

i dont know, its random

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 64 bits

### JDK

Eclipse Adoptium jdk-18.0.0.36-hotspot 64bits

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

- SpringBoot with Maven
- StackTrace :
`java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at org.netbeans.modules.spring.beans.model.impl.SpringModelProviderImpl.getCachedNamedElements(SpringModelProviderImpl.java:126)
	at org.netbeans.modules.spring.beans.model.impl.SpringModelProviderImpl.getBeans(SpringModelProviderImpl.java:65)
	at org.netbeans.modules.spring.api.beans.model.SpringModel.getBeans(SpringModel.java:43)
	at org.netbeans.modules.spring.webmvc.editor.SpringBeansELVariableResolver$2.run(SpringBeansELVariableResolver.java:161)
	at org.netbeans.modules.spring.webmvc.editor.SpringBeansELVariableResolver$2.run(SpringBeansELVariableResolver.java:156)
	at org.netbeans.modules.spring.beans.model.impl.SpringModelImplementation$1.call(SpringModelImplementation.java:47)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper.runCallable(AnnotationModelHelper.java:231)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper.access$100(AnnotationModelHelper.java:54)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper$2.run(AnnotationModelHelper.java:159)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper$2.run(AnnotationModelHelper.java:156)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:60)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:363)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:346)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:317)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:433)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper.runJavaSourceTask(AnnotationModelHelper.java:156)
	at org.netbeans.modules.j2ee.metadata.model.api.support.annotation.AnnotationModelHelper.runJavaSourceTask(AnnotationModelHelper.java:124)
	at org.netbeans.modules.spring.beans.model.impl.SpringModelImplementation.runReadAction(SpringModelImplementation.java:43)
	at org.netbeans.modules.j2ee.metadata.model.api.MetadataModel.runReadAction(MetadataModel.java:97)
	at org.netbeans.modules.spring.webmvc.editor.SpringBeansELVariableResolver.getAnnotatedBeans(SpringBeansELVariableResolver.java:156)
	at org.netbeans.modules.spring.webmvc.editor.SpringBeansELVariableResolver.getBeansFromScope(SpringBeansELVariableResolver.java:136)
	at org.netbeans.modules.spring.webmvc.editor.SpringBeansELVariableResolver.getSpringBeans(SpringBeansELVariableResolver.java:111)
	at org.netbeans.modules.spring.webmvc.editor.SpringBeansELVariableResolver.getInjectableField(SpringBeansELVariableResolver.java:53)
	at org.netbeans.modules.web.el.ELVariableResolvers$1.get(ELVariableResolvers.java:55)
	at org.netbeans.modules.web.el.ELVariableResolvers$1.get(ELVariableResolvers.java:50)
	at org.netbeans.modules.web.el.CompilationCache.getOrCache(CompilationCache.java:35)
	at org.netbeans.modules.web.el.ELVariableResolvers.findBeanClass(ELVariableResolvers.java:48)
	at org.netbeans.modules.web.el.ELTypeUtilities.getIdentifierType(ELTypeUtilities.java:590)
	at org.netbeans.modules.web.el.ELTypeUtilities.access$100(ELTypeUtilities.java:72)
	at org.netbeans.modules.web.el.ELTypeUtilities$TypeResolverVisitor.visit(ELTypeUtilities.java:851)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:222)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:225)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:225)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:225)
	at org.netbeans.modules.web.el.ELTypeUtilities.resolveElement(ELTypeUtilities.java:168)
	at org.netbeans.modules.web.el.ELTypeUtilities.resolveElement(ELTypeUtilities.java:157)
	at org.netbeans.modules.web.el.hints.Identifiers$1.visit(Identifiers.java:97)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:222)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:225)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:225)
	at com.sun.el.parser.SimpleNode.accept(SimpleNode.java:225)
	at org.netbeans.modules.web.el.hints.Identifiers.run(Identifiers.java:83)
	at org.netbeans.modules.web.el.hints.ELHintsProvider$1.run(ELHintsProvider.java:70)
	at org.netbeans.modules.web.el.hints.ELHintsProvider$1.run(ELHintsProvider.java:62)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:60)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:363)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:346)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:317)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:433)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.web.el.hints.ELHintsProvider.computeHints(ELHintsProvider.java:62)
	at org.netbeans.modules.csl.hints.infrastructure.HintsTask$1.run(HintsTask.java:114)
	at org.netbeans.modules.csl.hints.infrastructure.HintsTask$1.run(HintsTask.java:76)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:186)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
[catch] at org.netbeans.modules.csl.hints.infrastructure.HintsTask.run(HintsTask.java:69)
	at org.netbeans.modules.csl.hints.infrastructure.HintsTask.run(HintsTask.java:52)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
`

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by GisTom2** [comment]
I have a similar issue. I use 

Product Version: Apache NetBeans IDE 29
Java: 25.0.2; OpenJDK 64-Bit Server VM 25.0.2+10-LTS
Runtime: OpenJDK Runtime Environment 25.0.2+10-LTS
System: Linux version 6.17.0-19-generic running on amd64; UTF-8; en_US (nb)


java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.parsing.api.Snapshot.getSource()" because "snapshot" is null
	at org.netbeans.modules.cnd.modelimpl.platform.CndParserResult.<init>(CndParserResult.java:76)
	at org.netbeans.modules.cnd.modelimpl.platform.CndParserFactory$ParserImpl.<init>(CndParserFactory.java:139)
	at org.netbeans.modules.cnd.modelimpl.platform.CndParserFactory$ParserImpl.<init>(CndParserFactory.java:127)
	at org.netbeans.modules.cnd.modelimpl.platform.CndParserFactory.createParser(CndParserFactory.java:121)
	at org.netbeans.modules.parsing.api.ParserManager$MultiUserTaskAction.run(ParserManager.java:228)
	at org.netbeans.modules.parsing.api.ParserManager$MultiUserTaskAction.run(ParserManager.java:205)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:341)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:186)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:85)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.indexEmbedding(RepositoryUpdater.java:3268)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2861)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2626)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:574)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2625)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.lambda$scanSource$3(RepositoryUpdater.java:5735)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5770)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5443)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5075)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:341)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2012)
