### ISSUE TITLE
Unexpected Exception 

### ISSUE THREAD

**Issue by aletriste** [apache/netbeans#4139]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I breaks when a try to make an import

### Did this work correctly in an earlier version?

No

### Operating System

Windos 10

### JDK

1.8.0_321

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
	at org.netbeans.modules.java.source.parsing.FileObjects.memoryFileObject(FileObjects.java:516)
	at org.netbeans.modules.java.source.parsing.FileObjects.memoryFileObject(FileObjects.java:490)
	at org.netbeans.modules.java.source.save.Reformatter.reformat(Reformatter.java:114)
	at org.netbeans.modules.java.source.pretty.VeryPretty.printAnnotationsFormatted(VeryPretty.java:2761)
	at org.netbeans.modules.java.source.pretty.VeryPretty.printAnnotations(VeryPretty.java:2780)
	at org.netbeans.modules.java.source.pretty.VeryPretty.visitMethodDef(VeryPretty.java:985)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:936)
	at org.netbeans.modules.java.source.pretty.VeryPretty.doAccept(VeryPretty.java:421)
	at org.netbeans.modules.java.source.pretty.VeryPretty.print(VeryPretty.java:283)
	at org.netbeans.modules.java.source.save.CasualDiff.diffList(CasualDiff.java:4141)
	at org.netbeans.modules.java.source.save.CasualDiff.diffClassDef(CasualDiff.java:1102)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTreeImpl0(CasualDiff.java:5557)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTreeImpl(CasualDiff.java:5451)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTree(CasualDiff.java:5378)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTree(CasualDiff.java:5349)
	at org.netbeans.modules.java.source.save.CasualDiff.diffList(CasualDiff.java:4184)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTopLevel(CasualDiff.java:594)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTreeImpl0(CasualDiff.java:5530)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTreeImpl(CasualDiff.java:5451)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTree(CasualDiff.java:5378)
	at org.netbeans.modules.java.source.save.CasualDiff.diffTree(CasualDiff.java:5361)
	at org.netbeans.modules.java.source.save.CasualDiff.diff(CasualDiff.java:350)
	at org.netbeans.api.java.source.WorkingCopy.processCurrentCompilationUnit(WorkingCopy.java:920)
	at org.netbeans.api.java.source.WorkingCopy.getChanges(WorkingCopy.java:1332)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:676)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:663)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:502)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:130)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:114)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:81)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:452)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:423)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:684)
	at org.netbeans.modules.java.editor.codegen.ImplementOverrideMethodGenerator.invoke(ImplementOverrideMethodGenerator.java:279)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.invokeSelected(GenerateCodePanel.java:165)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.listMouseReleased(GenerateCodePanel.java:109)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel.access$000(GenerateCodePanel.java:41)
	at org.netbeans.modules.editor.codegen.GenerateCodePanel$2.mouseReleased(GenerateCodePanel.java:85)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
NetBeans 13 requires running on JDK 11+. Please try that and you shouldn't see this issue.
