### ISSUE TITLE
project tree not showing up on project window

### ISSUE THREAD

**Issue by bai0000** [apache/netbeans#4208]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I created a web application project, the first time working with it was fine, then I close netbeans and tried to load it up again but this time, the project tree is not showing up at all, and I got an error/exception:

```
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.startsWith(java.nio.file.Path)" because "path" is null
	at org.netbeans.modules.gradle.GradleModuleFileCache21$CachedArtifactVersion.<init>(GradleModuleFileCache21.java:143)
	at org.netbeans.modules.gradle.GradleModuleFileCache21.resolveCachedArtifactVersion(GradleModuleFileCache21.java:225)
	at org.netbeans.modules.gradle.api.GradleProjects.getSources(GradleProjects.java:50)
	at org.netbeans.modules.gradle.java.queries.GradleSourceForRepository.findSourceRoots2(GradleSourceForRepository.java:61)
	at org.netbeans.api.java.queries.SourceForBinaryQuery.findSourceRoots2(SourceForBinaryQuery.java:101)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.createResources(PathRegistry.java:728)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.getSources(PathRegistry.java:275)
	at org.netbeans.modules.parsing.impl.indexing.errors.Utilities.findIndexedRootsUnderDirectory(Utilities.java:87)
	at org.netbeans.modules.parsing.ui.indexing.errors.ErrorAnnotator$1.run(ErrorAnnotator.java:295)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```
![image](https://user-images.githubusercontent.com/107113095/172596391-8f767fa6-d320-4dc8-8d16-e24f7fa875e6.png)
![image](https://user-images.githubusercontent.com/107113095/172596472-903e530b-4bdd-45d9-8b32-71c0c2b221ab.png)

### How to reproduce

Create a project, close it, open it up again and the problems is there. Most commonly the project trees should pop out automatically.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Microsoft Windows 11 Home Single Language Ver. 10.0.220000

### JDK

JDK 18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
@lkishalmi should this be linked to the PR and closed or left open?

**Comment by vandittalwadia** [comment]
hey is this problem resolved ? please tell me what is the solution?

**Comment by mbien** [comment]
The NPE should be fixed. NetBeans 16 release candidate builds are available [here](https://github.com/apache/netbeans/discussions/4815) if you want to test if it is working

**Comment by vandittalwadia** [comment]
If i am facing this issue right now ..how it is fixed?

**Comment by vandittalwadia** [comment]
Tell me the steps..

**Comment by lkishalmi** [comment]
Are you sure that you are facing with this issue?
Could you provide steps to reproduce or exception log while using NetBeans 15 (it would be better to check it with NetBeans 16-rc4 though)

**Comment by vandittalwadia** [comment]
Ok, I will check.
