### ISSUE TITLE
Module graph fails to display

### ISSUE THREAD

**Issue by seven0f** [apache/netbeans#4227]
### Apache NetBeans version

Apache NetBeans 13

### What happened

Applies in both Apache Netbeans 14 and 13.

While module-info.java is loaded into editor window, click Graph view button (of Source, History, Graph). No graph display and an Unexpected Exception notification is generated. 

Priority: Silent; Category: Error.
Cannot invoke "org.netbeans.modules.java.graph.GraphNode.getImpl()" because the return value of "org.netbeans.modules.java.graph.DependencyGraphScene.getRootGraphNode()" is null.

Full text is:
```
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.java.graph.GraphNode.getImpl()" because the return value of "org.netbeans.modules.java.graph.DependencyGraphScene.getRootGraphNode()" is null
	at org.netbeans.modules.java.graph.DependencyGraphScene.highlightDepth(DependencyGraphScene.java:690)
	at org.netbeans.modules.java.graph.DependencyGraphScene.highlightDepthIntern(DependencyGraphScene.java:706)
	at org.netbeans.modules.java.graph.DependencyGraphScene.access$900(DependencyGraphScene.java:75)
	at org.netbeans.modules.java.graph.DependencyGraphScene$AllActionsProvider.select(DependencyGraphScene.java:672)
	at org.netbeans.modules.visual.action.SelectAction.mousePressed(SelectAction.java:69)
	at org.netbeans.api.visual.action.WidgetAction$Chain.mousePressed(WidgetAction.java:749)
	at org.netbeans.api.visual.widget.SceneComponent$Operator$2.operate(SceneComponent.java:529)
	at org.netbeans.api.visual.widget.SceneComponent.processLocationOperator(SceneComponent.java:306)
	at org.netbeans.api.visual.widget.SceneComponent.processLocationOperator(SceneComponent.java:261)
	at org.netbeans.api.visual.widget.SceneComponent.mousePressed(SceneComponent.java:133)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### How to reproduce

Load a project, open module-info.java in the editor, click Graph button.

### Did this work correctly in an earlier version?

No

### Operating System

macos Monterey 12.4 (on Apple M1 Max)

### JDK

zulu17.34.19-ca-fx-jdk17.0.3-macosx_aarch64 (java --version: openjdk 17.0.3 2022-04-19 LTS OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS) OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

As far as I can tell (I'm a very new user), this happens every time in both v13 and v14.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebresie** [comment]
Still stalls as of NB 17
