### ISSUE TITLE
Annotation: An error occurred during parsing of ...

### ISSUE THREAD

**Issue by gilbertoca** [apache/netbeans#4269]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Open an maven war project, set up java 1.8 in plataforms then clean and build. The output shows compilation errors, but the editor shows nothing wrong with the code. The notification icon appears giving me the option to report the error.

Output window:

```
Changes detected - recompiling the module!
Compiling 395 source files to /home/gilberto.andrade/tmp/SECAD/aede/target/classes
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
br/gov/to/secad/aede/domain/AuditoriaHomologacao.java:[3,40] package com.fasterxml.jackson.annotation does not exist
br/gov/to/secad/aede/domain/AuditoriaPublicacao.java:[3,40] package com.fasterxml.jackson.annotation does not exist
br/gov/to/secad/aede/domain/MigracaoHomologacao.java:[5,40] package com.fasterxml.jackson.annotation does not exist
br/gov/to/secad/aede/domain/AuditoriaMigracao.java:[3,40] package com.fasterxml.jackson.annotation does not exist
br/gov/to/secad/aede/domain/AuditoriaHomologacao.java:[22,6] cannot find symbol
  symbol:   class JsonBackReference
  location: class br.gov.to.secad.aede.domain.AuditoriaHomologacao
br/gov/to/secad/aede/domain/AuditoriaHomologacao.java:[27,6] cannot find symbol
```

### Did this work correctly in an earlier version?

No

### Operating System

openSUSE Leap 15.3

### JDK

jdk 11 and jdk 1.8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
extracted exception from the provided log:

```
com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/xml/bind/JAXBException
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:739)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:819)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:913)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2300(JavacProcessingEnvironment.java:114)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1256)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1371)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:62)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1133)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:747)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:239)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/xml/bind/JAXBException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.netbeans.modules.java.source.parsing.CachingArchiveClassLoader.access$600(CachingArchiveClassLoader.java:58)
	at org.netbeans.modules.java.source.parsing.CachingArchiveClassLoader$1.call(CachingArchiveClassLoader.java:114)
	at org.netbeans.modules.java.source.parsing.CachingArchiveClassLoader$1.call(CachingArchiveClassLoader.java:99)
	at org.netbeans.modules.java.source.parsing.CachingArchiveClassLoader.readAction(CachingArchiveClassLoader.java:278)
	at org.netbeans.modules.java.source.parsing.CachingArchiveClassLoader.findClass(CachingArchiveClassLoader.java:99)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.hibernate.jpamodelgen.xml.JpaDescriptorParser.<init>(JpaDescriptorParser.java:60)
	at org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor.init(JPAMetaModelEntityProcessor.java:99)
	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:973)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:690)
	... 25 more
```

this was fixed back in NB 20 https://github.com/apache/netbeans/pull/6422
