### ISSUE TITLE
A java.lang.IndexOutOfBoundsException exception has occurred.

### ISSUE THREAD

**Issue by konstaalex** [apache/netbeans#4329]
### Apache NetBeans version

Apache NetBeans 14

### What happened

so basically i am trying to setup a layered arhitecture project and when i try to import/esport modules i got this error from netbeans 
```
A java.lang.IndexOutOfBoundsException exception has occurred.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.sun.tools.javac.util.List.get(List.java:490)
	at org.netbeans.modules.maven.ModuleInfoSupport.lambda$addRequires$3(ModuleInfoSupport.java:238)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:675)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:665)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:686)
	at org.netbeans.modules.maven.ModuleInfoSupport.addRequires(ModuleInfoSupport.java:235)
	at org.netbeans.modules.maven.ModuleInfoSupport.lambda$addRequires$2(ModuleInfoSupport.java:211)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

macos catalina

### JDK

java version "11.0.11" 2021-04-20 LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by konstaalex** [comment]
i do not know if this worked or not in an early version...probably yes...it also worked on this version

**Comment by mbien** [comment]
provide steps how to reproduce this from a new project. Its unlikely anyone will be able to fix something which isn't reproducible.

**Comment by ebresie** [comment]
Is this an ant, maven, or other related project?

**Comment by ebresie** [comment]
Could this be related to 4322
