### ISSUE TITLE
java.lang.NullPointerException exception

### ISSUE THREAD

**Issue by YuranyD** [apache/netbeans#4334]
### Apache NetBeans version

Apache NetBeans 14

### What happened

When I start NetBeans IDE 14, appears an error that says:
A java.lang.NullPointerException exception has occurred.
Please report this at https://netbeans.apache.org/nb/report-issue,
including a copy of your messages.log file as an attachment.
Also, when I try to create a new project (New project/Java with Ant/Web Applicaton) it appears the next error: Cannot invoke "org.netbeans.modules.editor.indent.spi.IndentTask.indentLock()" because "this.val$netbeansDefaultTask" is null.
If I try to create a normal Java Application (no web) or a Java Application With maven, everything run ok, this error just happen when I try to create a new project Web Application  with Ant.
I'm Working with Apache Tomcat 10.0.22 Server and JDK 18.0.1.1
I also reinstall NetBeans, the JDK and the Tomcat several times, but the bug  did not fix.
![error1](https://user-images.githubusercontent.com/85708115/177401646-314cc44c-3d66-479e-b141-a1042b88abc5.png)
![error2](https://user-images.githubusercontent.com/85708115/177401649-b5e24551-7663-42aa-9adf-bbca32322dde.PNG)

### How to reproduce

You have to create a new project/Java with Ant/Java  Web/Web Application. Also next/next/Finish. 
When I press Finish it shows me the error.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 Pro Versión 21H2 OS 64 bits, procesador x64

### JDK

18.0.1.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ebresie** [comment]
Click the Show Details and save the stack trace to the issue if able.

**Comment by Ponraj3079** [comment]
same problem:
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.editor.indent.spi.IndentTask.indentLock()" because "this.val$netbeansDefaultTask" is null
	at de.funfried.netbeans.plugins.external.formatter.ui.editor.ExternalFormatterIndentTaskFactory$2.indentLock(ExternalFormatterIndentTaskFactory.java:104)
	at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.createTask(TaskHandler.java:533)
	at org.netbeans.modules.editor.indent.TaskHandler.addItem(TaskHandler.java:315)
	at org.netbeans.modules.editor.indent.TaskHandler.collectTasks(TaskHandler.java:133)
	at org.netbeans.modules.editor.indent.IndentImpl.reformatLock(IndentImpl.java:191)
	at org.netbeans.modules.editor.indent.api.Reformat.lock(Reformat.java:89)
	at org.netbeans.modules.editor.indent.IndentScriptEngineHack.eval(IndentScriptEngineHack.java:67)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at org.netbeans.modules.editor.indent.IndentScriptEngineHack.eval(IndentScriptEngineHack.java:119)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at org.netbeans.modules.templates.ScriptingCreateFromTemplateHandler.createFromTemplate(ScriptingCreateFromTemplateHandler.java:130)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:146)
	at org.netbeans.api.templates.CreateFromTemplateImpl.lambda$build$0(CreateFromTemplateImpl.java:86)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:84)
	at org.netbeans.api.templates.FileBuilder.build(FileBuilder.java:267)
	at org.netbeans.api.templates.FileBuilder.createFromTemplate(FileBuilder.java:369)
	at org.openide.loaders.MultiDataObject.handleCreateFromTemplate(MultiDataObject.java:860)
	at org.openide.loaders.MultiDataObject.handleCreateFromTemplate(MultiDataObject.java:841)
	at org.openide.loaders.DataObject$CreateAction.run(DataObject.java:1572)
	at org.openide.loaders.DataObjectPool$1WrapAtomicAction.run(DataObjectPool.java:236)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.loaders.DataObjectPool.runAtomicAction(DataObjectPool.java:261)
	at org.openide.loaders.DataObject.invokeAtomicAction(DataObject.java:1026)
	at org.openide.loaders.DataObject.createFromTemplate(DataObject.java:958)
	at org.openide.loaders.DataObject.createFromTemplate(DataObject.java:938)
	at org.netbeans.modules.web.project.api.WebProjectUtilities.createWelcomeFile(WebProjectUtilities.java:377)
	at org.netbeans.modules.web.project.api.WebProjectUtilities.ensureWelcomePage(WebProjectUtilities.java:336)
	at org.netbeans.modules.web.project.ui.wizards.NewWebProjectWizardIterator.instantiate(NewWebProjectWizardIterator.java:178)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1048)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.netbeans.modules.project.ui.NewProjectWizard.handleInstantiate(NewProjectWizard.java:51)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:228)
	at org.openide.loaders.TemplateWizardIteratorWrapper$ProgressInstantiatingIterator.instantiate(TemplateWizardIteratorWrapper.java:155)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1602)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)


> 

java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.editor.indent.spi.IndentTask.indentLock()" because "this.val$netbeansDefaultTask" is null
	at de.funfried.netbeans.plugins.external.formatter.ui.editor.ExternalFormatterIndentTaskFactory$2.indentLock(ExternalFormatterIndentTaskFactory.java:104)
	at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.createTask(TaskHandler.java:533)
	at org.netbeans.modules.editor.indent.TaskHandler.addItem(TaskHandler.java:315)
	at org.netbeans.modules.editor.indent.TaskHandler.collectTasks(TaskHandler.java:133)
	at org.netbeans.modules.editor.indent.IndentImpl.reformatLock(IndentImpl.java:191)
	at org.netbeans.modules.editor.indent.api.Reformat.lock(Reformat.java:89)
	at org.netbeans.modules.editor.indent.IndentScriptEngineHack.eval(IndentScriptEngineHack.java:67)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at org.netbeans.modules.editor.indent.IndentScriptEngineHack.eval(IndentScriptEngineHack.java:119)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at org.netbeans.modules.templates.ScriptingCreateFromTemplateHandler.createFromTemplate(ScriptingCreateFromTemplateHandler.java:130)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:146)
	at org.netbeans.api.templates.CreateFromTemplateImpl.lambda$build$0(CreateFromTemplateImpl.java:86)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:84)
	at org.netbeans.api.templates.FileBuilder.build(FileBuilder.java:267)
	at org.netbeans.api.templates.FileBuilder.createFromTemplate(FileBuilder.java:369)
	at org.openide.loaders.MultiDataObject.handleCreateFromTemplate(MultiDataObject.java:860)
	at org.openide.loaders.MultiDataObject.handleCreateFromTemplate(MultiDataObject.java:841)
	at org.openide.loaders.DataObject$CreateAction.run(DataObject.java:1572)
	at org.openide.loaders.DataObjectPool$1WrapAtomicAction.run(DataObjectPool.java:236)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.loaders.DataObjectPool.runAtomicAction(DataObjectPool.java:261)
	at org.openide.loaders.DataObject.invokeAtomicAction(DataObject.java:1026)
	at org.openide.loaders.DataObject.createFromTemplate(DataObject.java:958)
	at org.openide.loaders.DataObject.createFromTemplate(DataObject.java:938)
	at org.netbeans.modules.web.project.api.WebProjectUtilities.createWelcomeFile(WebProjectUtilities.java:377)
	at org.netbeans.modules.web.project.api.WebProjectUtilities.ensureWelcomePage(WebProjectUtilities.java:336)
	at org.netbeans.modules.web.project.ui.wizards.NewWebProjectWizardIterator.instantiate(NewWebProjectWizardIterator.java:178)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1048)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.netbeans.modules.project.ui.NewProjectWizard.handleInstantiate(NewProjectWizard.java:51)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:228)
	at org.openide.loaders.TemplateWizardIteratorWrapper$ProgressInstantiatingIterator.instantiate(TemplateWizardIteratorWrapper.java:155)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1602)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by Ashen-Shaminda** [comment]
I have the same issue. Did you figure out how to solve this ? .

**Comment by ebresie** [comment]
What version of Netbeans and Java is in use?

Is the "[External Java Code Formatters for NetBeans](https://plugins.netbeans.apache.org/catalogue/?id=15)" plug-in installed?

**Comment by ebresie** [comment]
Have you tried it in Netbeans 15 or 16?

**Comment by Ashen-Shaminda** [comment]
Thank You. I solved the problem after uninstalling the External Java Code Formatter for NetBeans plug-in.

**Comment by camxcube** [comment]
> Thank You. I solved the problem after uninstalling the External Java Code Formatter for NetBeans plug-in.

Really helpful. It works for me.

**Comment by pepness** [comment]
There was no support for Tomcat 10 until [PR-4822](https://github.com/apache/netbeans/pull/4822), best test it on master or the soon to be released NB17.

**Comment by DanielFRB** [comment]
> What version of Netbeans and Java is in use?
> 
> Is the "[External Java Code Formatters for NetBeans](https://plugins.netbeans.apache.org/catalogue/?id=15)" plug-in installed?

After trying versions 15, 16 and the last one 17, the solution was to remove the External Java Code Formatters

**Comment by mbien** [comment]
lets close this. Looks like everyone is happy after removing the external code formatter plugin.
