### ISSUE TITLE
Occasional NPE in javac during scan of JDK classes

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#4341]
### Body

NB 14

seeing this exception during scans of the NetBeans codebase (I am not sure if this also happens with other projects):
```
Caused: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null
	at com.sun.tools.javac.comp.TypeEnter.ensureImportsChecked(TypeEnter.java:172)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:627)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:587)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1042)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:345)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:747)
	at org.netbeans.modules.java.source.parsing.CompilationInfoImpl.toPhase(CompilationInfoImpl.java:426)
...
```
`.netbeans/14/var/log` contains dump files for several JDK classes with the same NPE in it: `Object`, `Class`, `CharSequence`, `Integer`, `System` and `Thread`. All have one thing in common: `java.lang` package.

This doesn't seam to influence anything though, the parser is probably just skipping the file.

example dump for java.lang.Object:
[Object_48.dump.txt](https://github.com/apache/netbeans/files/9060378/Object_48.dump.txt)

### Committer

- [X] I acknowledge that I am a maintainer/committer in the Apache NetBeans project.

**Comment by ebresie** [comment]
Is the related to #4341?

**Comment by dathyrius** [comment]
I have encountered the same problem:

An error occurred during parsing of 'java/lang/NumberFormatException.java in /Library/Java/JavaVirtualMachines/jdk1.8.0_131.
/*
 * Copyright (c) 1994, 2012, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package java.lang;

/**
 * Thrown to indicate that the application has attempted to convert
 * a string to one of the numeric types, but that the string does not
 * have the appropriate format.
 *
 * @author  unascribed
 * @see     java.lang.Integer#parseInt(String)
 * @since   JDK1.0
 */
public
class NumberFormatException extends IllegalArgumentException {
    static final long serialVersionUID = -2848938806368998894L;

    /**
     * Constructs a <code>NumberFormatException</code> with no detail message.
     */
    public NumberFormatException () {
        super();
    }

    /**
     * Constructs a <code>NumberFormatException</code> with the
     * specified detail message.
     *
     * @param   s   the detail message.
     */
    public NumberFormatException (String s) {
        super (s);
    }

    /**
     * Factory method for making a <code>NumberFormatException</code>
     * given the specified input which caused the error.
     *
     * @param   s   the input causing the error
     */
    static NumberFormatException forInputString(String s) {
        return new NumberFormatException("For input string: \"" + s + "\"");
    }
}

----- Classpath: ---------------------------------------------
bootPath: nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/com.azul.crs.client/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/com.azul.tooling/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.base/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.compiler/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.datatransfer/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.desktop/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.instrument/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.logging/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.management/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.management.rmi/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.naming/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.net.http/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.prefs/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.rmi/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.scripting/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.se/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.security.jgss/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.security.sasl/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.smartcardio/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.sql/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.sql.rowset/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.transaction.xa/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.xml/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/java.xml.crypto/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.accessibility/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.aot/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.attach/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.charsets/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.compiler/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.crypto.cryptoki/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.crypto.ec/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.dynalink/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.editpad/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.hotspot.agent/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.httpserver/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.ed/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.jvmstat/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.le/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.opt/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.vm.ci/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.vm.compiler/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.internal.vm.compiler.management/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jartool/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.javadoc/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jcmd/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jconsole/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jdeps/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jdi/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jdwp.agent/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jfr/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jlink/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jshell/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jsobject/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.jstatd/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.localedata/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.management/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.management.agent/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.management.jfr/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.naming.dns/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.naming.ldap/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.naming.rmi/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.net/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.pack/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.rmic/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.scripting.nashorn/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.scripting.nashorn.shell/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.sctp/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.security.auth/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.security.jgss/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.unsupported/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.unsupported.desktop/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.xml.dom/:nbjrt:file:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/!/modules/jdk.zipfs/
classPath: /Users/XXXXX/NetBeansProjects/YYYYYYY/build/classes
sourcePath: 
----- Original exception ---------------------------------------------
java.lang.NullPointerException
	at com.sun.tools.javac.comp.TypeEnter.ensureImportsChecked(TypeEnter.java:170)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:627)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:587)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1042)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:345)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:747)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by DivyaMaddipudi** [comment]
Any update on this issue? I'm getting the same issue

**Comment by DivyaMaddipudi** [comment]
Caused by: java.lang.NullPointerException: Cannot invoke                                                                          
"com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null                                
       at com.sun.tools.javac.comp.TypeEnter.ensureImportsChecked(TypeEnter.java:172)                                            
       at com.sun.tools.javac.comp.Enter.complete(Enter.java:627)                                                                
       at com.sun.tools.javac.comp.Enter.main(Enter.java:587)                                        
       
       
       
 I'm getting the following issue, I couldn't find proper solution for this. Any help would be appreciated!!

**Comment by mbien** [comment]
closing. the last time I saw this in the log file was NB 19
