### ISSUE TITLE
Netbeans 12 -- java.lang.NullPointerException

### ISSUE THREAD

**Issue by cktducky** [apache/netbeans#4373]
### Apache NetBeans version

Apache NetBeans 14

### What happened

```
Netbeans 12:

UI Log Data:
<record>
  <date>2022-07-14T15:36:39</date>
  <millis>1657784199791</millis>
  <sequence>1336</sequence>
  <level>1000</level>
  <thread>24</thread>
  <exception>
    <message>java.lang.NullPointerException</message>
    <frame>
      <class>javax.swing.text.JTextComponent</class>
      <method>write</method>
      <line>1655</line>
      <file>jrt:/java.desktop/javax/swing/text/JTextComponent.class</file>
    </frame>
    <frame>
      <class>javax.swing.JEditorPane</class>
      <method>getText</method>
      <line>1451</line>
      <file>jrt:/java.desktop/javax/swing/JEditorPane.class</file>
    </frame>
    <frame>
      <class>hk.quantr.netbeans.minimap.MinimapPanel$1</class>
      <method>stateChanged</method>
      <line>127</line>
      <file>${user.dir}modules/hk-quantr-netbeans-minimap.jar</file>
    </frame>
    <frame>
      <class>javax.swing.JViewport</class>
      <method>fireStateChanged</method>
      <line>1490</line>
      <file>jrt:/java.desktop/javax/swing/JViewport.class</file>
    </frame>
    <frame>
      <class>javax.swing.JViewport$ViewListener</class>
      <method>componentResized</method>
      <line>1409</line>
      <file>jrt:/java.desktop/javax/swing/JViewport$ViewListener.class</file>
    </frame>
    <frame>
      <class>java.awt.AWTEventMulticaster</class>
      <method>componentResized</method>
      <line>167</line>
      <file>jrt:/java.desktop/java/awt/AWTEventMulticaster.class</file>
    </frame>
    <frame>
      <class>java.awt.Component</class>
      <method>processComponentEvent</method>
      <line>6462</line>
      <file>jrt:/java.desktop/java/awt/Component.class</file>
    </frame>
    <frame>
      <class>java.awt.Component</class>
      <method>processEvent</method>
      <line>6416</line>
      <file>jrt:/java.desktop/java/awt/Component.class</file>
    </frame>
    <frame>
      <class>java.awt.Container</class>
      <method>processEvent</method>
      <line>2263</line>
      <file>jrt:/java.desktop/java/awt/Container.class</file>
    </frame>
    <frame>
      <class>java.awt.Component</class>
      <method>dispatchEventImpl</method>
      <line>5012</line>
      <file>jrt:/java.desktop/java/awt/Component.class</file>
    </frame>
    <frame>
      <class>java.awt.Container</class>
      <method>dispatchEventImpl</method>
      <line>2321</line>
      <file>jrt:/java.desktop/java/awt/Container.class</file>
    </frame>
    <frame>
      <class>java.awt.Component</class>
      <method>dispatchEvent</method>
      <line>4844</line>
      <file>jrt:/java.desktop/java/awt/Component.class</file>
    </frame>
    <frame>
      <class>java.awt.EventQueue</class>
      <method>dispatchEventImpl</method>
      <line>772</line>
      <file>jrt:/java.desktop/java/awt/EventQueue.class</file>
    </frame>
    <frame>
      <class>java.awt.EventQueue$4</class>
      <method>run</method>
      <line>721</line>
      <file>jrt:/java.desktop/java/awt/EventQueue$4.class</file>
    </frame>
    <frame>
      <class>java.awt.EventQueue$4</class>
      <method>run</method>
      <line>715</line>
      <file>jrt:/java.desktop/java/awt/EventQueue$4.class</file>
    </frame>
    <frame>
      <class>java.security.AccessController</class>
      <method>doPrivileged</method>
      <line>391</line>
      <file>jrt:/java.base/java/security/AccessController.class</file>
    </frame>
    <frame>
      <class>java.security.ProtectionDomain$JavaSecurityAccessImpl</class>
      <method>doIntersectionPrivilege</method>
      <line>85</line>
      <file>jrt:/java.base/java/security/ProtectionDomain$JavaSecurityAccessImpl.class</file>
    </frame>
    <frame>
      <class>java.security.ProtectionDomain$JavaSecurityAccessImpl</class>
      <method>doIntersectionPrivilege</method>
      <line>95</line>
      <file>jrt:/java.base/java/security/ProtectionDomain$JavaSecurityAccessImpl.class</file>
    </frame>
    <frame>
      <class>java.awt.EventQueue$5</class>
      <method>run</method>
      <line>745</line>
      <file>jrt:/java.desktop/java/awt/EventQueue$5.class</file>
    </frame>
    <frame>
      <class>java.awt.EventQueue$5</class>
      <method>run</method>
      <line>743</line>
      <file>jrt:/java.desktop/java/awt/EventQueue$5.class</file>
    </frame>
    <frame>
      <class>java.security.AccessController</class>
      <method>doPrivileged</method>
      <line>391</line>
      <file>jrt:/java.base/java/security/AccessController.class</file>
    </frame>
    <frame>
      <class>java.security.ProtectionDomain$JavaSecurityAccessImpl</class>
      <method>doIntersectionPrivilege</method>
      <line>85</line>
      <file>jrt:/java.base/java/security/ProtectionDomain$JavaSecurityAccessImpl.class</file>
    </frame>
    <frame>
      <class>java.awt.EventQueue</class>
      <method>dispatchEvent</method>
      <line>742</line>
      <file>jrt:/java.desktop/java/awt/EventQueue.class</file>
    </frame>
    <frame>
      <class>org.exbin.utils.guipopup.GuiPopupMenu$PopupEventQueue</class>
      <method>dispatchEvent</method>
      <line>320</line>
      <file>${user.dir}modules/org-exbin-utils-guipopup.jar</file>
    </frame>
    <frame>
      <class>java.awt.EventDispatchThread</class>
      <method>pumpOneEventForFilters</method>
      <line>203</line>
      <file>jrt:/java.desktop/java/awt/EventDispatchThread.class</file>
    </frame>
    <frame>
      <class>java.awt.EventDispatchThread</class>
      <method>pumpEventsForFilter</method>
      <line>124</line>
      <file>jrt:/java.desktop/java/awt/EventDispatchThread.class</file>
    </frame>
    <frame>
      <class>java.awt.EventDispatchThread</class>
      <method>pumpEventsForHierarchy</method>
      <line>113</line>
      <file>jrt:/java.desktop/java/awt/EventDispatchThread.class</file>
    </frame>
    <frame>
      <class>java.awt.EventDispatchThread</class>
      <method>pumpEvents</method>
      <line>109</line>
      <file>jrt:/java.desktop/java/awt/EventDispatchThread.class</file>
    </frame>
    <frame>
      <class>java.awt.EventDispatchThread</class>
      <method>pumpEvents</method>
      <line>101</line>
      <file>jrt:/java.desktop/java/awt/EventDispatchThread.class</file>
    </frame>
    <frame>
      <class>java.awt.EventDispatchThread</class>
      <method>run</method>
      <line>90</line>
      <file>jrt:/java.desktop/java/awt/EventDispatchThread.class</file>
    </frame>
  </exception>
</record>
<record>
  <date>2022-07-14T15:53:38</date>
  <millis>1657785218500</millis>
  <sequence>1554</sequence>
  <level>700</level>
  <thread>366</thread>
  <message>UI_USER_CONFIGURATION</message>
  <key>UI_USER_CONFIGURATION</key>
  <catalog>org.netbeans.modules.uihandler.Bundle</catalog>
  <param>Windows 10, 10.0, amd64</param>
  <param>Java HotSpot(TM) 64-Bit Server VM, 13.0.2+8, Java(TM) SE Runtime Environment, 13.0.2+8</param>
  <param>Apache NetBeans IDE 12.0</param>
  <param></param>
  <param>NullPointerException at javax.swing.text.JTextComponent.write</param>
  <param>&lt;Please provide a description of the problem or the steps to reproduce&gt;</param>
  <param>*********</param>
</record>

IDE Log Data:
SEVERE [global]
java.lang.NullPointerException
	at java.desktop/javax.swing.text.JTextComponent.write(JTextComponent.java:1655)
	at java.desktop/javax.swing.JEditorPane.getText(JEditorPane.java:1451)
	at hk.quantr.netbeans.minimap.MinimapPanel$1.stateChanged(MinimapPanel.java:127)
	at java.desktop/javax.swing.JViewport.fireStateChanged(JViewport.java:1490)
	at java.desktop/javax.swing.JViewport$ViewListener.componentResized(JViewport.java:1409)
	at java.desktop/java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:167)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6462)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.exbin.utils.guipopup.GuiPopupMenu$PopupEventQueue.dispatchEvent(GuiPopupMenu.java:320)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO [org.netbeans.modules.parsing.impl.TaskProcessor]: Task: com.github.philippefichet.sonarlint4netbeans.SonarLintParserResultTask@323fa5e2 : class com.github.philippefichet.sonarlint4netbeans.SonarLintParserResultTask ignored cancel for 219 ms.

```

### How to reproduce

Do not know, randomly.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 11

### JDK

11

### Apache NetBeans packaging

Apache NetBeans platform

### Anything else

It will show this error after using Netbeans a moment.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
NetBeans 12 is no longer supported. Please verify the issue still affects NetBeans 14.

`MinimapPanel` is not part of NetBeans.  Please verify if the issue occurs without that included.
