### ISSUE TITLE
java.lang.RuntimeException: 94/2: The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by scsynergy** [apache/netbeans#4381]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Ijava.lang.RuntimeException: 94/2: The name org.freedesktop.secrets was not provided by any .service files
	at org.netbeans.modules.keyring.gnome.libsecret.GnomeLibSecretProvider.processError(GnomeLibSecretProvider.java:134)
	at org.netbeans.modules.keyring.gnome.libsecret.GnomeLibSecretProvider.read(GnomeLibSecretProvider.java:94)
[catch] at org.netbeans.modules.keyring.gnome.libsecret.GnomeLibSecretProvider.enabled(GnomeLibSecretProvider.java:75)
	at org.netbeans.api.keyring.Keyring.provider(Keyring.java:67)
	at org.netbeans.api.keyring.Keyring.readImpl(Keyring.java:82)
	at org.netbeans.api.keyring.Keyring.access$100(Keyring.java:52)
	at org.netbeans.api.keyring.Keyring$1.call(Keyring.java:105)
	at org.netbeans.api.keyring.Keyring$1.call(Keyring.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### How to reproduce

I have GIT configured to use ssh to communicate with a remote GIT server. Everything works fine, yet, each time I push changes to the remote server I get a notification in Netbeans with the above error message.

Since the error message mentions "Gnome": I use KDE, not Gnome.

### Did this work correctly in an earlier version?

Apache NetBeans 12.4

### Operating System

Debian 11 stable

### JDK

Adoptium "17.0.2" 2022-01-18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lherschi** [comment]
I have the same problem on a KDE desktop with Netbeans 16. As a workaround you can set the switch -J-Dnetbeans.keyring.no.native=true in netbeans.conf. Then there will be no more exceptions, but KWallet will no longer be queried by Netbeans.
