### ISSUE TITLE
Git autorization

### ISSUE THREAD

**Issue by bash098** [apache/netbeans#4443]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Hello!
Can't autorized to github:
```
INFO [org.netbeans.modules.subversion]: Finished indexing svn cache with 0 entries. Elapsed time: 0 ms.
INFO [org.netbeans.modules.subversion.remote]: Finished indexing svn cache with 0 entries. Elapsed time: 0 ms.
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Indexing of: C:\Users\karam\OneDrive\Documents\NetBeansProjects\GitTest took: 2 611 ms (New or modified files: 12, Deleted files: 0) [Adding listeners took: 0 ms]
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Complete indexing of 1 source roots took: 2 611 ms (New or modified files: 12, Deleted files: 0) [Adding listeners took: 0 ms]
INFO [org.netbeans.ui.indexing]: Индексирование завершено; для индексирования потребовалось 2 613 мс.
WARNING [org.netbeans.modules.options.keymap.LayersBridge]: Invalid shortcut: org.openide.loaders.XMLDataObject@34817c3f[MultiFileObject@717ff03f[Actions/Help/master-help.xml]]
INFO [org.netbeans.ui.vcs]: Вызвана команда управления версиями INTERNAL-init, потребовалось 1 173мс.
WARNING [org.netbeans.modules.options.keymap.KeymapModel]: Duplicate action ID used: copy-to-clipboard
INFO [org.netbeans.ui.metrics.vcs]: USG_VCS_REPOSITORY
INFO [org.netbeans.modules.git.ui.repository.remote.SelectUriStep]: Auth failed when accessing https://github.com/bash098/GitTest.git/
org.eclipse.jgit.errors.TransportException: https://bash098@github.com/bash098/GitTest.git/: not authorized
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:538)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:359)
	at org.netbeans.libs.git.jgit.commands.ListRemoteObjectsCommand.runTransportCommand(ListRemoteObjectsCommand.java:51)
Caused: org.netbeans.libs.git.GitException$AuthorizationException: https://bash098@github.com/bash098/GitTest.git/: not authorized
	at org.netbeans.libs.git.jgit.commands.TransportCommand.handleException(TransportCommand.java:220)
	at org.netbeans.libs.git.jgit.commands.ListRemoteObjectsCommand.runTransportCommand(ListRemoteObjectsCommand.java:64)
	at org.netbeans.libs.git.jgit.commands.TransportCommand.run(TransportCommand.java:168)
	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:57)
	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.netbeans.libs.git.jgit.commands.GitCommand.execute(GitCommand.java:54)
	at org.netbeans.libs.git.GitClient.listRemoteBranches(GitClient.java:893)
	at org.netbeans.modules.git.client.GitClient$36.call(GitClient.java:582)
	at org.netbeans.modules.git.client.GitClient$36.call(GitClient.java:578)
	at org.openide.util.NetworkSettings.suppressAuthenticationDialog(NetworkSettings.java:138)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1$1.call(GitClient.java:931)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1.call(GitClient.java:956)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethodIntern(GitClient.java:968)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:897)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:875)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.access$400(GitClient.java:869)
	at org.netbeans.modules.git.client.GitClient.listRemoteBranches(GitClient.java:578)
[catch] at org.netbeans.modules.git.ui.repository.remote.SelectUriStep$2.perform(SelectUriStep.java:240)
	at org.netbeans.modules.git.client.GitProgressSupport.performIntern(GitProgressSupport.java:92)
	at org.netbeans.modules.git.client.GitProgressSupport.run(GitProgressSupport.java:85)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
INFO [null]: Last record repeated again.
```

I'm sorry if issue like this was create. I didn't find anything about it.

### How to reproduce

I tryed create a new project and push to git.
Tryed to clone/fetch/push project.

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10 Pro

### JDK

java version "1.8.0_111" Java(TM) SE Runtime Environment (build 1.8.0_111-b14) Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Git authotizing work with token.
temporary solution:
https://www.javafixing.com/2022/05/fixed-can-connect-to-github-repository.html

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
The solution is the correct one, not a temporary one.  GitHub does not support using your account password for this - you need to set up a personal access token and use that as the password in NetBeans.
