### ISSUE TITLE
org.netbeans.modules.java.source.parsing.JavacParser:  Analyzer error when processing

### ISSUE THREAD

**Issue by cariny0** [apache/netbeans#4470]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Internal error,   after a while Netbeans will freeze completely.
Tried with version 12.5  and  fails the same way.

### How to reproduce

No Idea.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro  21H1   compilation 19043.1826

### JDK

openjdk version "16.0.2" 2021-07-20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

```
Annotation: An error occurred during parsing of 'D:\Personal\desarrollo\Java\DataTypes\src\com\v5\memoria\FabricaV5.java'. Please report a bug against java/source and attach dump file 'C:\Users\user\AppData\Roaming\NetBeans\14\var\log\FabricaV5_30.dump'.
Annotation: An error occurred during parsing of 'D:\Personal\desarrollo\Java\DataTypes\src\com\v5\memoria\FabricaV5.java'. Please report a bug against java/source and attach dump file 'C:\Users\user\AppData\Roaming\NetBeans\14\var\log\FabricaV5_30.dump'.
Annotation: An error occurred during parsing of 'D:\Personal\desarrollo\Java\DataTypes\src\com\v5\memoria\FabricaV5.java'. Please report a bug against java/source and attach dump file 'C:\Users\user\AppData\Roaming\NetBeans\14\var\log\FabricaV5_30.dump'.
An error occurred during parsing of 'D:\Personal\desarrollo\Java\DataTypes\src\com\v5\memoria\FabricaV5.java'. Please report a bug against java/source and attach dump file 'C:\Users\user\AppData\Roaming\NetBeans\14\var\log\FabricaV5_30.dump'.
An error occurred during parsing of 'D:\Personal\desarrollo\Java\DataTypes\src\com\v5\memoria\FabricaV5.java'. Please report a bug against java/source and attach dump file 'C:\Users\user\AppData\Roaming\NetBeans\14\var\log\FabricaV5_30.dump'.
Caused: java.lang.AssertionError: Analyzer error when processing: return new DatoJava<Number>(this, dato);:java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.isPartial()" because "s" is null
com.sun.tools.javac.code.Types$5.visitClassType(Types.java:1396)
com.sun.tools.javac.code.Types$5.visitClassType(Types.java:1348)
com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1013)
com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4900)
com.sun.tools.javac.code.Types.isSameType(Types.java:1340)
com.sun.tools.javac.comp.Analyzer$DiamondInitializer.process(Analyzer.java:263)
com.sun.tools.javac.comp.Analyzer$DiamondInitializer.process(Analyzer.java:223)
com.sun.tools.javac.comp.Analyzer.doAnalysis(Analyzer.java:572)
com.sun.tools.javac.comp.Analyzer$2.flush(Analyzer.java:542)
com.sun.tools.javac.comp.Analyzer.flush(Analyzer.java:586)
com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1383)
com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:404)
com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:770)
org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:239)
org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.comp.Analyzer.doAnalysis(Analyzer.java:574)
	at com.sun.tools.javac.comp.Analyzer$2.flush(Analyzer.java:542)
	at com.sun.tools.javac.comp.Analyzer.flush(Analyzer.java:586)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1383)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
	at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
Caused: java.lang.IllegalStateException
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:770)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:239)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```
[FabricaV5_30.dump.txt](https://github.com/apache/netbeans/files/9273924/FabricaV5_30.dump.txt)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by hrotkogabor** [comment]
I have the same problem, and I have a sample project.

### Apache NetBeans version
Apache NetBeans 15

### What happened
With the sample project, the ide will not freeze, but with a larger project, it will freeze.

### How to reproduce
The problem appears when I have the following code, I already have import java.util.List; , and click the hint: Add import java.util.ArrayList :
List<String> myList = new ArrayList<Long>();


### Did this work correctly in an earlier version?
Also fail with version 14

### Operating System
System: Linux version 5.15.60-1-MANJARO running on amd64; UTF-8; hu_HU (nb)

### JDK
11.0.15; Java HotSpot(TM) 64-Bit Server VM 11.0.15+8-LTS-149

### Apache NetBeans packaging
Apache NetBeans provided zip

### Anything else
Annotation: An error occurred during parsing of '/home/hrotkog/NetBeansProjects/temp/mavenproject5/src/main/java/sample/mavenproject5/Mavenproject5.java'. Please report a bug against java/source and attach dump file '/home/hrotkog/.netbeans/15/var/log/Mavenproject5_1.dump'.
Annotation: An error occurred during parsing of '/home/hrotkog/NetBeansProjects/temp/mavenproject5/src/main/java/sample/mavenproject5/Mavenproject5.java'. Please report a bug against java/source and attach dump file '/home/hrotkog/.netbeans/15/var/log/Mavenproject5_1.dump'.
Annotation: An error occurred during parsing of '/home/hrotkog/NetBeansProjects/temp/mavenproject5/src/main/java/sample/mavenproject5/Mavenproject5.java'. Please report a bug against java/source and attach dump file '/home/hrotkog/.netbeans/15/var/log/Mavenproject5_1.dump'.
An error occurred during parsing of '/home/hrotkog/NetBeansProjects/temp/mavenproject5/src/main/java/sample/mavenproject5/Mavenproject5.java'. Please report a bug against java/source and attach dump file '/home/hrotkog/.netbeans/15/var/log/Mavenproject5_1.dump'.
An error occurred during parsing of '/home/hrotkog/NetBeansProjects/temp/mavenproject5/src/main/java/sample/mavenproject5/Mavenproject5.java'. Please report a bug against java/source and attach dump file '/home/hrotkog/.netbeans/15/var/log/Mavenproject5_1.dump'.
Caused: java.lang.AssertionError: Analyzer error when processing: List<String> myList = new ArrayList<Long>():java.lang.NullPointerException
com.sun.tools.javac.code.Types$5.visitClassType(Types.java:1396)
com.sun.tools.javac.code.Types$5.visitClassType(Types.java:1348)
com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1013)
com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4900)
com.sun.tools.javac.code.Types.isSameType(Types.java:1340)
com.sun.tools.javac.comp.Analyzer$DiamondInitializer.process(Analyzer.java:263)
com.sun.tools.javac.comp.Analyzer$DiamondInitializer.process(Analyzer.java:223)
com.sun.tools.javac.comp.Analyzer.doAnalysis(Analyzer.java:572)
com.sun.tools.javac.comp.Analyzer$2.flush(Analyzer.java:542)
com.sun.tools.javac.comp.Analyzer.flush(Analyzer.java:586)
com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1383)
com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:404)
com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:770)
org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.comp.Analyzer.doAnalysis(Analyzer.java:574)
	at com.sun.tools.javac.comp.Analyzer$2.flush(Analyzer.java:542)
	at com.sun.tools.javac.comp.Analyzer.flush(Analyzer.java:586)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1383)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
	at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
Caused: java.lang.IllegalStateException
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:770)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)


### Are you willing to submit a pull request?
No

### Code of Conduct
Yes

**Comment by mbien** [comment]
still reproducible with javac 23
change
```java
ArrayList<Object> arrayList = new ArrayList<>();
```
into
```java
ArrayList<Object> arrayList = new ArrayList<ArrayList>();
```
and it should cause
```
Caused: java.lang.AssertionError: Analyzer error when processing: ArrayList<Object> arrayList = new ArrayList<ArrayList>():
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.isPartial()" because "s" is null
...
```
running javac over CLI would result in :
```
NewClass.java:[16,39] incompatible types: java.util.ArrayList<java.util.ArrayList> cannot be converted to java.util.ArrayList<java.lang.Object>
```

**Comment by lahodaj** [comment]
Filled:
https://bugs.openjdk.org/browse/JDK-8364987
