### ISSUE TITLE
A java.lang.NoClassDefFoundError exception has occurred.

### ISSUE THREAD

**Issue by c-rosati** [apache/netbeans#4584]
### Apache NetBeans version

Apache NetBeans 14

### What happened

Started debugging a small demo application. Variables view is showing nothing and Unexpected Exception appeared in the Notifications view.

java.lang.ClassNotFoundException: org.netbeans.spi.viewmodel.NodeActionsProviderFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: org.netbeans.spi.viewmodel.NodeActionsProviderFilter starting from ModuleCL@49393f70[org.exbin.bined.netbeans] with possible defining loaders [ModuleCL@6ba44ecc[org.netbeans.spi.viewmodel]] and declared parents [ModuleCL@269acfd6[org.netbeans.modules.settings], org.netbeans.JarClassLoader@1c4a3cf8, ModuleCL@569672b3[org.netbeans.modules.queries], ModuleCL@7d20393a[org.netbeans.modules.options.api], ModuleCL@14c82de4[org.openide.windows], org.netbeans.MainImpl$BootClassLoader@4edde6e5, ModuleCL@39f8bb52[org.openide.loaders], ModuleCL@5d1e5d97[org.netbeans.core.multiview], ModuleCL@50a794df[org.netbeans.api.annotations.common], ModuleCL@77cb19a8[org.openide.dialogs], ...3 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Caused: java.lang.NoClassDefFoundError: org/netbeans/spi/viewmodel/NodeActionsProviderFilter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:287)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:246)
Caused: java.lang.NoClassDefFoundError: org/netbeans/spi/viewmodel/NodeActionsProviderFilter while loading org.exbin.bined.netbeans.debug.BinedLocalsActionsProviderFilter; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:250)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:174)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.spi.debugger.ContextAwareSupport.createInstance(ContextAwareSupport.java:75)
	at org.netbeans.debugger.registry.ContextAwareServiceHandler.invoke(ContextAwareServiceHandler.java:109)
	at jdk.proxy20/jdk.proxy20.$Proxy99.forContext(Unknown Source)
	at org.netbeans.api.debugger.Lookup$MetaInf$MetaInfLookupList$LazyInstance.getEntry(Lookup.java:1053)
	at org.netbeans.api.debugger.Lookup$LookupList$LookupLazyEntry.get(Lookup.java:1271)
	at org.netbeans.api.debugger.LazyArrayList.get(LazyArrayList.java:138)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.fillElements(Lookup.java:243)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:195)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:179)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:179)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.api.debugger.DebuggerEngine.lookup(DebuggerEngine.java:172)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:178)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.modules.debugger.ui.views.ViewModelListener.updateModelLazily(ViewModelListener.java:390)
	at org.netbeans.modules.debugger.ui.views.ViewModelListener.setUp(ViewModelListener.java:215)
	at org.netbeans.modules.debugger.ui.views.ViewModelListener$1.run(ViewModelListener.java:199)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Windows 10 Enterprise, 20H2, 19042.1889, Windows Feature Experience Pack 120.2212.4180.0

### JDK

18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

After the first occurrence, I'm not able do debug anymore because of this error always occurring.

[messages.log](https://github.com/apache/netbeans/files/9489798/messages.log)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by c-rosati** [comment]
I've just installed NetBeans 15 and the same problem exists, so I lost the possibility to debug code.

**Comment by c-rosati** [comment]
I've found the problem. I've disabled all User Installed Plugins and debugging was working fine without exceptions. Re-enabling the plugins if found the cause:

    BinEd - Binary/Hexadecimal Editor, ver. 0.2.3

Disabling (and then uninstalling) it fixed the issue.

**Comment by neilcsmith-net** [comment]
As noted in #3797 BinEd does some creative things to register its actions.  Some things even persist after uninstall.  Please report this issue to the author.  Closing this. Thanks!

**Comment by Chris2011** [comment]
Hey @c-rosati please check with latest NetBeans 15 (I think NetBeans 16 is around the corner) and with newest Bined-netbeans-plugin 0.2.4 (https://bined.exbin.org/netbeans-plugin/)
