### ISSUE TITLE
A java.util.ConcurrentModificationException has occurred.

### ISSUE THREAD

**Issue by sai20-creator** [apache/netbeans#4608]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
	at org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController.setTestMethodsImpl(TestMethodController.java:67)
	at org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController.lambda$setTestMethods$0(TestMethodController.java:44)
	at org.netbeans.editor.GuardedDocument.runAtomic(GuardedDocument.java:296)
	at org.openide.text.NbDocument.runAtomic(NbDocument.java:411)
	at org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController.setTestMethods(TestMethodController.java:43)
	at org.netbeans.modules.java.testrunner.ui.ComputeTestMethodsImpl$TaskImpl.lambda$run$0(ComputeTestMethodsImpl.java:106)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Monterey

### JDK

Oracle

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
closing in favor of #5148 since it has more details
