### ISSUE TITLE
Renaming class with the `Rename Also File With the Declaration` option ends with an error

### ISSUE THREAD

**Issue by r-man** [apache/netbeans#4620]
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

When I try to rename the class name and the file, NB first renames the file and then gives me the error "File <filepath> seems no longer valid!"

### How to reproduce

1. Create php class
2. Try rename class name
3. In rename dialog check `Rename Also File With the Declaration` option

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

windows 11 pro

### JDK

Java: 18.0.1; Java HotSpot(TM) 64-Bit Server VM 18.0.1+10-24

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Daniel-Peder** [comment]
Confirmed still happens. Hard to isolate. Somtimes happens, sometimes not. Mostly for newly created classes, not yet referenced from other files. 

The issue dissapears once the "reference" gets created. For example:

$o = new myclass();
$o->some_method();

Then click some_method and use navigate to the declaration. Since then, the file can be refactored without issues.

--

Also after the issue occurs, there still appears the old file (before rename) in the list of files (sorry not where ATM) but it disappears from the above list after netbeans close-open. The point is, the issue leaves the reference of the old file somewhere.

**Comment by junichi11** [comment]
I can't reproduce it.

```
Product Version: Apache NetBeans IDE 20
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-0ubuntu322.04
Runtime: OpenJDK Runtime Environment 19.0.2+7-Ubuntu-0ubuntu322.04
System: Linux version 6.5.0-17-generic running on amd64; UTF-8;
```

**Comment by Daniel-Peder** [comment]
> I can't reproduce it.
> 
> ```
> Product Version: Apache NetBeans IDE 20
> Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-0ubuntu322.04
> Runtime: OpenJDK Runtime Environment 19.0.2+7-Ubuntu-0ubuntu322.04
> System: Linux version 6.5.0-17-generic running on amd64; UTF-8;
> ```

yes, as said before, sometimes happens, sometimes not, not sure but seems to be related to the size of project or number of project files

```
Product Version: Apache NetBeans IDE 21
Java: 11.0.22; OpenJDK 64-Bit Server VM 11.0.22+7-post-Ubuntu-0ubuntu220.04.1
Runtime: OpenJDK Runtime Environment 11.0.22+7-post-Ubuntu-0ubuntu220.04.1
System: Linux version 5.4.0-173-generic running on amd64; UTF-8; en_US (nb)
```

**Comment by troizet** [comment]
I'm facing the same problem.
In the end the file was renamed, the class was not.

Logs:
```
INFO [org.netbeans.ui.vcs]: Versioning command INTERNAL-rename called, took 25ms.
File: /var/www/belgau-rasp/models/Students.php
StartOffset: 292
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.refactoring.spi.impl.RefactoringPanel$2
msg
Caused: org.openide.filesystems.FileStateInvalidException: /var/www/belgau-rasp/models/Students.php@78ddac1:3ef3c650[invalid]
	at org.openide.loaders.DataObject.find(DataObject.java:586)
Caused: org.openide.loaders.DataObjectNotFoundException: /var/www/belgau-rasp/models/Students.php@78ddac1:3ef3c650[invalid]
	at org.openide.loaders.DataObject.find(DataObject.java:609)
	at org.netbeans.modules.csl.spi.support.ModificationResult.commit(ModificationResult.java:113)
	at org.netbeans.modules.csl.spi.support.ModificationResult.commit(ModificationResult.java:105)
	at org.netbeans.modules.refactoring.spi.RefactoringCommit.commit(RefactoringCommit.java:128)
Caused: java.lang.RuntimeException
	at org.netbeans.modules.refactoring.spi.RefactoringCommit.commit(RefactoringCommit.java:140)
	at org.netbeans.modules.refactoring.api.RefactoringSession.reallyDoRefactoring(RefactoringSession.java:141)
	at org.netbeans.modules.refactoring.api.RefactoringSession.access$100(RefactoringSession.java:54)
	at org.netbeans.modules.refactoring.api.RefactoringSession$1.run(RefactoringSession.java:97)
	at org.netbeans.modules.refactoring.api.RefactoringSession$1.run(RefactoringSession.java:95)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks.runWithOnSaveTasksDisabled(BeforeSaveTasks.java:68)
	at org.netbeans.editor.Utilities.runWithOnSaveTasksDisabled(Utilities.java:1676)
	at org.netbeans.modules.refactoring.api.RefactoringSession.doRefactoring(RefactoringSession.java:95)
	at org.netbeans.modules.refactoring.spi.impl.RefactoringPanel$2.run(RefactoringPanel.java:547)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
ALL [null]: The file /var/www/belgau-rasp/models/Students.php seems no longer valid!
```
