### ISSUE TITLE
NPE at startup Maven indexer

### ISSUE THREAD

**Issue by bernard01** [apache/netbeans#4701]
### Apache NetBeans version

Apache NetBeans 15

### What happened

On startup an exception occurred
[messages.log](https://github.com/apache/netbeans/files/9675201/messages.log)
```
java.lang.NullPointerException
	at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.indexLoadedRepo(NexusRepositoryIndexerImpl.java:586)
	at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.lambda$indexRepo$6(NexusRepositoryIndexerImpl.java:663)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.writeAccess(DefaultMutexImplementation.java:229)
	at org.openide.util.Mutex.writeAccess(Mutex.java:252)
	at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.indexRepo(NexusRepositoryIndexerImpl.java:657)
	at org.netbeans.modules.maven.indexer.api.RepositoryIndexer.indexRepo(RepositoryIndexer.java:42)
	at org.netbeans.modules.maven.ProjectOpenedHookImpl$2.run(ProjectOpenedHookImpl.java:207)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### How to reproduce

Startup

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 7

### JDK

Java 14

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Product Version: Apache NetBeans IDE 15
Java: 14; Java HotSpot(TM) 64-Bit Server VM 14+36-1461
Runtime: Java(TM) SE Runtime Environment 14+36-1461
System: Windows 7 version 6.1 running on amd64; Cp1252; en_NZ (nb)
User directory: C:\Users\user\AppData\Roaming\NetBeans\15
Cache directory: C:\Users\user\AppData\Local\NetBeans\Cache\15

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
I'll take a look. Could it be that you don't have any space left on your C drive?
