### ISSUE TITLE
Warning about unused variable disappears when adding private nested record

### ISSUE THREAD

**Issue by negora** [apache/netbeans#4709]
### Apache NetBeans version

Apache NetBeans 15

### What happened

I've a method whose body contains an unused variable. NetBeans reports about this issue right. However, if I add a `private` nested `record` to my class, then the warning disappears. By *disappears* I mean that is not detected as a proper warning anymore:

* The light bulb isn't shown in the left margin of the editor.

* The yellow line isn't shown in the right margin of the editor.

* If I run *Source* → *Inspect...* and choose the hint *Probable bugs* → *Unused element*, it's not detected anymore.

It's strange, because the unused variable is still underlined, but in gray color, not in yellow. And if you hover it with the mouse pointer, the IDE still shows the tip *Variable X is not used*.

Other odd fact: If you change the visibility of the `record` to `public`, `protected` or *package-private*, then the warning comes back.

### How to reproduce

Use this so simple code to reproduce the problem:

```java
public class MyClass {

	public void myMethod () {
		int x = 1;
		// ^^^ Unused variable.
	}

	private record MyRecord (String myField) {
	}

}
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Debian GNU/Linux 11.5 (Bullseye)

### JDK

OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
I just checked and it is also reproducible in NB 14. So its not a recent regression.

**Comment by negora** [comment]
@mbien I just tried in NetBeans IDE 13, and it works OK. So whatever that causes this error appeared between versions 13 and 14. Thank you.

**Comment by negora** [comment]
I've found another case, similar to the previous one, in which the visibility of a class member affects the result of this type of check. However, this time it affects a method parameter instead of a local variable. Look at this:

```java
public class Main {

    public Main() {
        checkParameter(1);
    }

    public static void checkParameter(int myParameter) {
                                    // ^^^ This variable should be marked as unused,
                                    // but it isn't.
    }

}
```

Now, if you change the visibility of the method from `public` to `private`, NetBeans correctly detects that `myParameter` is not used at all in the body of the method.

I've tested this in versions 13, 14 and 15 and this *bug* happens in all them.

I was tempted to open a separate issue, because I'm not sure that it's 100% related to the original issue. If you think that it deserves a separate one, please, let me know.

**Comment by negora** [comment]
Just a little update about the first case that I presented in this report. If I remove all the fields of the `record` and leave it empty, the warning the appears again. Example:

```java
public class MyClass {

    public void myMethod () {
        int x = 1;
        // ^^^ Unused variable.
    }

    private record MyRecord () {
                         // ^^^ Empty record.
    }

}
```

**Comment by maffe** [comment]
> I've found another case, similar to the previous one, in which the visibility of a class member affects the result of this type of check. However, this time it affects a method parameter instead of a local variable. Look at this:
> 
> ```java
> public class Main {
> 
>     public Main() {
>         checkParameter(1);
>     }
> 
>     public static void checkParameter(int myParameter) {
>                                     // ^^^ This variable should be marked as unused,
>                                     // but it isn't.
>     }
> 
> }
> ```
> 
> Now, if you change the visibility of the method from `public` to `private`, NetBeans correctly detects that `myParameter` is not used at all in the body of the method.

I think it is intentional to not mark unused parameters in public methods since removing them would change your public API, breaking code using that method.

**Comment by mbien** [comment]
this was fixed between NB 23 and 24 and should work with current releases. Closing.

<details>

```
java.lang.IllegalArgumentException: Handle for synthetic path
	at org.netbeans.api.java.source.TreePathHandle.create(TreePathHandle.java:233)
	at org.netbeans.spi.java.hints.JavaFix.<init>(JavaFix.java:100)
	at org.netbeans.spi.java.hints.JavaFix.<init>(JavaFix.java:82)
	at org.netbeans.spi.java.hints.JavaFixUtilities$RemoveFromParent.<init>(JavaFixUtilities.java:1638)
	at org.netbeans.spi.java.hints.JavaFixUtilities.safelyRemoveFromParent(JavaFixUtilities.java:255)
	at org.netbeans.modules.java.hints.bugs.Unused.convertUnused(Unused.java:126)
	at org.netbeans.modules.java.hints.bugs.Unused.unused(Unused.java:78)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[catch] at org.netbeans.modules.java.hints.providers.code.CodeHintProviderImpl$WorkerImpl.createErrors(CodeHintProviderImpl.java:305)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.runHint(HintsInvoker.java:721)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.runAndAdd(HintsInvoker.java:596)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:615)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:562)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:110)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:118)
	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:220)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:989)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:621)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:562)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:110)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:118)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:202)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:896)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:621)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:562)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:95)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:110)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:118)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:202)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:896)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:621)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:562)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:110)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:118)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:151)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:625)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:640)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHintsImpl(HintsInvoker.java:240)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:224)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:191)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:166)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:128)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:111)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:62)
	at org.netbeans.modules.java.source.JavaSourceAccessor$CancelableTaskWrapper.run(JavaSourceAccessor.java:273)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)

```

</details>
