### ISSUE TITLE
Parse error with some java file

### ISSUE THREAD

**Issue by tarmax** [apache/netbeans#4772]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Netbeans is not enable to parse some java file, with exception but no useful informations.

### How to reproduce

[MessageStorageNoSessionRestServiceImpl.log](https://github.com/apache/netbeans/files/9756981/MessageStorageNoSessionRestServiceImpl.log)

An error occurred during parsing of '/home/maax/isp/cdbp0/architettura-v1/architettura-rest/src/main/java/com/arch/pt/rest/service/messagestorage/nosession/MessageStorageNoSessionRestServiceImpl.java'. Please report a bug against java/source and attach dump file '/home/maax/.netbeans/15/var/log/MessageStorageNoSessionRestServiceImpl_1.dump'.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

openSuse & Mint I do not know other

### JDK

1.11.0

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
>JDK
>
>1.11.0

where did you find that version? :)


trace taken from the log:

```
com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.ExceptionInInitializerError
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:739)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:819)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:913)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2300(JavacProcessingEnvironment.java:114)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1256)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1371)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:62)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1133)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:747)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: java.lang.ExceptionInInitializerError
	at lombok.javac.handlers.HandleGetter.<clinit>(HandleGetter.java:298)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:170)
	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:155)
	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
	at lombok.javac.apt.Processor.init(Processor.java:86)
	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:973)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:690)
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
	at java.lang.ClassLoader.findClass(ClassLoader.java:524)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:373)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at lombok.javac.JavacTreeMaker$SchroedingerType.getFieldCached(JavacTreeMaker.java:156)
	at lombok.javac.JavacTreeMaker$TypeTag.typeTag(JavacTreeMaker.java:244)
	at lombok.javac.Javac.<clinit>(Javac.java:154)
	... 38 more
```

**Comment by tarmax** [comment]
it seems i have made a mistake.
i am using 1.8 for all my projects, because it is mandatory from my job and my JAVA_HOME point to jdk openjdk 1.8 too

**Comment by tarmax** [comment]
it seems i have made a mistake.
i am using 1.8 for all my projects, because it is mandatory from my job and my JAVA_HOME point to jdk openjdk 1.8 too

**Comment by asbachb** [comment]
If you're using NetBeans 15 you should use java 11+ at least to run NetBeans as stated here:

> The Apache NetBeans 15 binary releases require JDK 11+, and officially support running on JDK 11 and JDK 17.

https://netbeans.apache.org/download/nb15/

(What you're using to compile does not depend on NetBeans runtime JRE/JDK)

Basically it seems that lombok crashes during code generation. Which lombok version you're using? I propose you to use a recent JDK to run NetBeans and/or play around with the lombok version you're using in your project.

**Comment by tarmax** [comment]
Sorry for delay.
I have solved my problem adding last lombok library in my pom file.
Before my operation lombok library was inhereditated by other libs.
Thank's a lot for your suggestion to check lombok library.

Massimo

________________________________

**Comment by mbien** [comment]
good that you could solve the issue. closing.
