### ISSUE TITLE
Unexpected Exception reported during Clean and Build of Project

### ISSUE THREAD

**Issue by stoxford** [apache/netbeans#4853]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Unexpected Exception occurring during "Clean and Build Project."

May be related to issue #4852, but the stack trace is different.

"Show Details" output:

```
Annotation: An error occurred during parsing of '/Users/james/Development/stoxford.com/economics/src/java/com/stoxford/economics/fred/AsyncFredUpdateSingletonEJB.java'. Please report a bug against java/source and attach dump file '/Users/james/Library/Application Support/NetBeans/15/var/log/AsyncFredUpdateSingletonEJB.dump'.
An error occurred during parsing of '/Users/james/Development/stoxford.com/economics/src/java/com/stoxford/economics/fred/AsyncFredUpdateSingletonEJB.java'. Please report a bug against java/source and attach dump file '/Users/james/Library/Application Support/NetBeans/15/var/log/AsyncFredUpdateSingletonEJB.dump'.
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoClassDefFoundError: javax.xml.bind.JAXBException
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:739)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:819)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:913)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2300(JavacProcessingEnvironment.java:114)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1256)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1371)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:62)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1133)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:747)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: java.lang.NoClassDefFoundError: javax.xml.bind.JAXBException
	at org.hibernate.jpamodelgen.xml.JpaDescriptorParser.<init>(JpaDescriptorParser.java:77)
	at org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor.init(JPAMetaModelEntityProcessor.java:116)
	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:973)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:690)
	... 25 more
Caused by: java.lang.ClassNotFoundException
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:636)
	at org.netbeans.modules.java.source.parsing.CachingArchiveClassLoader.findClass(CachingArchiveClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
	... 29 more
An error occurred during parsing of '/Users/james/Development/stoxford.com/economics/src/java/com/stoxford/economics/fred/AsyncFredUpdateSingletonEJB.java'. Please report a bug against java/source and attach dump file '/Users/james/Library/Application Support/NetBeans/15/var/log/AsyncFredUpdateSingletonEJB.dump'.

```

### How to reproduce

This occurred during the clean and build of my project. I don't know how others can reproduce it without access to my project.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Catalina

### JDK

NetBeans running on JDK 17.0.4.1. Compiling with JDK 8.

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This was also occurring in NetBeans 13. I don't know how to attach the .dump file.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
this is likely fixed by the linked PR above and can be tested in current dev builds. Closing, feel free to reopen if it still causes issues.
