### ISSUE TITLE
Gradle Project Loading issues with NetBeans 16 RC-3

### ISSUE THREAD

**Issue by swpalmer** [apache/netbeans#4923]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

Project loads, but still NetBeans complains that it cannot load the project.  The message simply states:

boolean org.gradle.api.internal.provider.ValueSupplier$ExecutionTimeVaue.isFixedValue()

Gradle is configured to use a fixed path to my Gradle installation of Gradle 7.6 RC-1

In the same NB session I changed the settings to use Gradle 7.5.1 and checked the box to use the gradle wrapper.
The automatically triggered a reload which also failed.  this time with the following exception:

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.netbeans.modules.gradle.loaders.LegacyProjectLoader.getLocation(LegacyProjectLoader.java:374)
	at org.netbeans.modules.gradle.loaders.LegacyProjectLoader.createReport(LegacyProjectLoader.java:417)
	at org.netbeans.modules.gradle.loaders.LegacyProjectLoader.exceptionsToProblems(LegacyProjectLoader.java:356)
	at org.netbeans.modules.gradle.loaders.LegacyProjectLoader.loadGradleProject(LegacyProjectLoader.java:285)
	at org.netbeans.modules.gradle.loaders.LegacyProjectLoader.access$200(LegacyProjectLoader.java:92)
[catch] at org.netbeans.modules.gradle.loaders.LegacyProjectLoader$ProjectLoaderTask.call(LegacyProjectLoader.java:623)
	at org.netbeans.modules.gradle.loaders.LegacyProjectLoader$ProjectLoaderTask.call(LegacyProjectLoader.java:592)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

Attached messages.log (with -J-Dorg.netbeans.modules.gradle.loaders.LegacyProjectLoader.level=400)

[messages.log](https://github.com/apache/netbeans/files/9944626/messages.log)

### How to reproduce

1. Install a local copy of Gradle 7.6RC-1

2. Configure Gradle in NetBeans to always use the Gradle at the location where Gradle 7.6.RC-1 is installed.
  - OR -
  Check the "Prefer to  use Gradle Wrapper..." box

3. Load the attached Gradle project (NetBeansGradleTest.zip)

4. Build or Run the project. Note that it does build and run, but NB still complains.

Loading strictly with Gradle 7.5.1 and no wrapper works.
[NetBeansGradleTest.zip](https://github.com/apache/netbeans/files/9944663/NetBeansGradleTest.zip)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 12.6.1

### JDK

Zulu 17.0.5 with JavaFX

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I just updated my Gradle install to 7.6. RC-1.  My project is building and running on JDK 19 via Gradle's Java Toolchain mechanism.  Previously my Gradle install was 7.5.1.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by sdedic** [comment]
Re. `isFixedValue`: Found a cause. Gradle has refactored this internal API because of a change in Groovy 4 property resolution; see https://issues.apache.org/jira/browse/GROOVY-10707 for deails.

I'll make an appropriate wrapper for that.

**Comment by neilcsmith-net** [comment]
> I'll make an appropriate wrapper for that.

@sdedic aiming for NB16 or NB17?  We need to assess whether we need an rc4.

**Comment by sdedic** [comment]
The PR targets `delivery`, however I'd left to the reviewer and/or release master to decide whether the change should go to NB16. The fix aims to wrap all potentially failing calls (because accessing gradle's internals) into try-catch/log wrapper that should continue project loading even in case of incompatible gradle changes.

**Comment by errael** [comment]
@sdedic Does #4936 generally remove the requirement that certain Gradle projects require NB to run on specific JDK? Perhaps not a total fix; but IIUC with the PR in place there is at least light at the end of the tunnel, an adaptor for `gradle <old-version>` could be built.

I'm thinking in particular of the `gradle 6.8.x` projects I have that require NB to run on JDK-11 (or at least JDK-15 or less). With #4936 in place, if it doesn't work out of the box, I could work-on/contribute an adaptor; is that correct?

It's not obvious to me if I can register and adaptor, maybe a service provider, or if something needs to be compiled into NB. But I haven't looked at the PR in detail to figure out where the adapters come from.

**Comment by mbien** [comment]
the same applies to the daemon. But at least there we can tell it to use a different JDK to run on so that we can build NB on 19 at least: https://github.com/apache/netbeans/pull/4817#pullrequestreview-1169510219

Interestingly: I still can't explain why we can build NB locally with JDK 19 just fine. But it will fail on gh without me telling the daemon where to run on. (both me and @lkishalmi tried to reproduce the github CI issue locally this weekend)

Gradle 7.6 will support JDK 19.
rc1 is already out:
https://docs.gradle.org/7.6-rc-1/release-notes.html

pinging @neilcsmith-net since I know he has custom NB bundles with JDK included. This might be relevant there too regarding what JDK to pick.

we could also try a last minute update to 7.6 rc1 - not sure if its worth the risk.

If we want to keep covering the whole JDK range from 8 to current we probably will have to end up shipping multiple gradle versions at once unless we figure out some other way to make this work (please no nb-gradle :)).

**Comment by sdedic** [comment]
> 
> we could also try a last minute update to 7.6 rc1 - not sure if its worth the risk.
> 
I'd prefer just to add `7.6-rc-1` to the compatibility table as OK for JDK19. I've tried that locally and works well - the project-configured version will satisfy the check.

**Comment by swpalmer** [comment]
On a related note, if we feel the need to call internal Gradle APIs for proper IDE integration, are we filing issues with the Gradle team for improved APIs?ScottOn Nov 7, 2022, at 3:37 PM, Michael Bien ***@***.***> wrote:﻿
the same applies to the daemon. But at least there we can tell it to use a different JDK to run on so that we can build NB on 19 at least: #4817 (review)
Interestingly: I still can't explain why we can build NB locally with JDK 19 just fine. But it will fail on gh without me telling the daemon where to run on. (both me and @lkishalmi tried to reproduce the github CI issue locally this weekend)
Gradle 7.6 will support JDK 19.
rc1 is already out:
https://docs.gradle.org/7.6-rc-1/release-notes.html
pinging @neilcsmith-net since I know he has custom NB bundles with JDK included. This might be relevant there too regarding what JDK to pick.
we could also try a last minute update to 7.6 rc1 - not sure if its worth the risk.
If we want to keep covering the whole JDK range from 8 to current we probably will have to end up shipping multiple gradle versions at once unless we figure out some other way to make this work (please no nb-gradle :)).

**Comment by sdedic** [comment]
> On a related note, if we feel the need to call internal Gradle APIs for proper IDE integration, are we filing issues with the Gradle team for improved APIs?ScottOn Nov 7, 2022, at 3:37 PM, Michael Bien ***@***.***> wrote:﻿ the same applies to the daemon. But at least there we can tell it to use a different JDK to run on so that we can build NB on 19 at least: #4817 (review) Interestingly: I still can't explain why we can build NB locally with JDK 19 just fine. But it will fail on gh without me telling the daemon where to run on. (both me and @lkishalmi tried to reproduce the github CI issue locally this weekend) Gradle 7.6 will support JDK 19. rc1 is already out: https://docs.gradle.org/7.6-rc-1/release-notes.html pinging @neilcsmith-net since I know he has custom NB bundles with JDK included. This might be relevant there too regarding what JDK to pick. we could also try a last minute update to 7.6 rc1 - not sure if its worth the risk. If we want to keep covering the whole JDK range from 8 to current we probably will have to end up shipping multiple gradle versions at once unless we figure out some other way to make this work (please no nb-gradle :)). —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by errael** [comment]
> At first sight I don't think it's reasonable from Gradle's point of view, since e.g. NB gets 'under the hood' of an initialized Plugin

Is the information that NB examines something that most IDEs would (might) want to look at? Seems that use case is a strong argument in favor of an API.

**Comment by sdedic** [comment]
> > At first sight I don't think it's reasonable from Gradle's point of view, since e.g. NB gets 'under the hood' of an initialized Plugin
> 
> Is the information that NB examines something that most IDEs would (might) want to look at? Seems that use case is a strong argument in favor of an API.

I think so. Both the default values (+ conventions) as that is a part that would have to be replicated by an IDE, and the actually configured values, which is also rather hard, given the flexibility of inheritance, property interpolation etc.

Anyone volunteers to approach Gradle people with a kindly formulated sugggestion ?

**Comment by neilcsmith-net** [comment]
> pinging @neilcsmith-net since I know he has custom NB bundles with JDK included. This might be relevant there too regarding what JDK to pick.

Thanks @mbien - but already aware, and raised in https://lists.apache.org/thread/2hggcxcph44gdgwq58kk98ntrt5bsb3v

The community installers that @geertjanw and I produce will have to bundle JDK 18 I guess.  It also means that we should caveat JDK 19 on the downloads page?

> Is the information that NB examines something that most IDEs would (might) want to look at? Seems that use case is a strong argument in favor of an API.

Seems a strong argument in favour of a plugin or similar that runs on the target JDK and not the runtime JDK of the IDE to me!

**Comment by sdedic** [comment]
> 
> Seems a strong argument in favour of a plugin or similar that runs on the target JDK and not the runtime JDK of the IDE to me!

AFAIK NetBeans _can_ do a better job here, since we do not tell Gradle any JDK (so it chooses the one the tooling API within NB executes on). But - it's the user who shoudl decide. Based on my experience, both scenarios are valid:
- compile on the JDK set as compile target
- compile on user-chosen JDK *different* from the compilation target: the user may want to use e.g. extended syntax, especially with newer javacs that compile against exact target's JDK API set.

We do not have a separate setting for the (external, forked) build tool though - and such setting might be useful even for Maven.

**Comment by mbien** [comment]
> The community installers that @geertjanw and I produce will have to bundle JDK 18 I guess.

@neilcsmith-net I would go down to jdk 17 tbh since 18 is basically EOL with the release of 19. (you might have to stick to 17 for a few NB releases anyway)

 >  It also means that we should caveat JDK 19 on the downloads page?

not only for JDK 19. Users which work on projects which use older gradle versions might have to run on 11 as @errael [explained](https://github.com/apache/netbeans/issues/4923#issuecomment-1306055735).

IMO more importantly: NB should also tell the user what to do if it can't open a gradle project due to incompatibilities so that it doesn't look like a bug, given that workarounds exist. (but thats for NB 17)

**Comment by errael** [comment]
> IMO more importantly: NB should also tell the user what to do if it can't open a gradle project due to incompatibilities

Hopefully the instructions, for NB17, are to set the 

> separate setting for the (external, forked) build tool

as @sdedic suggests above https://github.com/apache/netbeans/issues/4923#issuecomment-1306981881 and at the end of https://github.com/apache/netbeans/issues/4923#issuecomment-1306104696

BTW, I've been thinking of opening an issue like "Gradle project dictates NetBeans' JDK runtime". Haven't looked to see if there's an issue for this. Is it needed? Seems like a solution is so close in the minds of those in the know.

**Comment by mbien** [comment]
> Hopefully the instructions, for NB17, are to set the...

of course. I was thinking what we still could do with the release which is currently baking.

> BTW, I've been thinking of opening an issue like "Gradle project dictates NetBeans' JDK runtime". Haven't looked to see if there's an issue for this. Is it needed? Seems like a solution is so close in the minds of those in the know.

if you add a table to show what JDK version to use for what gradle version we could link this issue from the NB 16 release page instead of having to explain it there again. (@neilcsmith-net would this be ok?)

**Comment by neilcsmith-net** [comment]
> @neilcsmith-net possibly jdk 17 tbh since 18 is basically EOL with the release of 19

A decision still to be made - I don't like reverting down a release either.  Being EOL doesn't really make a lot of difference there.  Decision to ship JDK18 with NB 15 was based on trying to provide a latest features experience out of the box.

> BTW, I've been thinking of opening an issue like "Gradle project dictates NetBeans' JDK runtime". Haven't looked to see if there's an issue for this. Is it needed? Seems like a solution is so close in the minds of those in the know.

Sounds good to me.  It's certainly something to consider.  I also wonder how Gradle 8 will play into all this.

> if you add a table to show what JDK version to use for what gradle version we could link this issue from the NB 16 release page instead of having to explain it there again. (@neilcsmith-net would this be ok?)

Sounds good to me - @geertjanw tends to handle release pages.

**Comment by errael** [comment]
> > if you add a table to show what JDK version to use for what gradle version we could link this issue from the NB 16 release page instead of having to explain it there again. (@neilcsmith-net would this be ok?)
> 
> Again sounds good to me - @geertjanw tends to handle release pages.

@geertjanw I think this is it [Gradle's Java Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html#java), note that it doesn't cover gradle 7.6 - is Java-19. gradle-7.6 is currently a release candidate. I don't entirely understand the table, but at least for the one I'm familiar with, the JDK is a max.

**Comment by mbien** [comment]
i suppose gh didn't close this one because it was integrated indirectly via delivery
