### ISSUE TITLE
Error with springboot initializer

### ISSUE THREAD

**Issue by Snoopy137** [apache/netbeans#4974]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Netbeans is throwing I open the application related to the spring boot plugin and this is preventing the plugin initializer to create a new project.
The error shows the following

java.lang.ClassNotFoundException: org.springframework.core.convert.converter.ConverterRegistry
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: org.springframework.core.convert.converter.ConverterRegistry starting from ModuleCL@5b6bc285[com.github.alexfalappa.nb.springboot.plugin] with possible defining loaders null and declared parents [ModuleCL@3f2b8ac2[org.netbeans.modules.maven.embedder], ModuleCL@36cac714[org.netbeans.modules.parsing.api], ModuleCL@75c7c07e[org.netbeans.modules.java.source.base], ModuleCL@744c5211[org.netbeans.core.multiview], org.netbeans.JarClassLoader@7e276c4e, ModuleCL@579476e[org.netbeans.modules.java.sourceui], ModuleCL@5a9926e5[org.netbeans.modules.projectuiapi.base], ModuleCL@73c9d969[org.openide.explorer], ModuleCL@6d9c7516[org.netbeans.modules.projectuiapi], ModuleCL@7502fc08[org.openide.text], ...30 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
Caused: java.lang.NoClassDefFoundError: org/springframework/core/convert/converter/ConverterRegistry
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:287)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:246)
Caused: java.lang.NoClassDefFoundError: org/springframework/core/convert/converter/ConverterRegistry while loading org.springframework.format.FormatterRegistry; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:250)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:174)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:287)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:246)
Caused: java.lang.NoClassDefFoundError: org/springframework/core/convert/converter/ConverterRegistry while loading org.springframework.format.FormatterRegistry; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound while loading org.springframework.format.support.FormattingConversionService; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:250)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:174)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:287)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:246)
Caused: java.lang.NoClassDefFoundError: org/springframework/core/convert/converter/ConverterRegistry while loading org.springframework.format.FormatterRegistry; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound while loading org.springframework.format.support.FormattingConversionService; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound while loading org.springframework.boot.convert.ApplicationConversionService; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:250)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:174)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.DataTypeMismatchHighlightingTask.<init>(DataTypeMismatchHighlightingTask.java:57)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.CfgPropsHighlightingTaskFactory.create(CfgPropsHighlightingTaskFactory.java:38)
	at org.netbeans.modules.parsing.impl.SourceCache.createTasks(SourceCache.java:468)
	at org.netbeans.modules.parsing.impl.SourceCache.getAllEmbeddings(SourceCache.java:283)
	at org.netbeans.modules.parsing.api.ResultIterator.getEmbeddings(ResultIterator.java:140)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1T.run(RepositoryUpdater.java:3244)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.indexEmbedding(RepositoryUpdater.java:3268)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2861)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2626)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2625)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.lambda$scanSource$3(RepositoryUpdater.java:5735)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1400(RepositoryUpdater.java:135)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5770)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5443)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5075)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5842)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$3400(RepositoryUpdater.java:5855)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

Then if I try to create a new project I get

java.lang.ClassNotFoundException: org.springframework.http.client.ClientHttpRequestFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: org.springframework.http.client.ClientHttpRequestFactory starting from ModuleCL@5b6bc285[com.github.alexfalappa.nb.springboot.plugin] with possible defining loaders null and declared parents [ModuleCL@3f2b8ac2[org.netbeans.modules.maven.embedder], ModuleCL@36cac714[org.netbeans.modules.parsing.api], ModuleCL@75c7c07e[org.netbeans.modules.java.source.base], ModuleCL@744c5211[org.netbeans.core.multiview], org.netbeans.JarClassLoader@7e276c4e, ModuleCL@579476e[org.netbeans.modules.java.sourceui], ModuleCL@5a9926e5[org.netbeans.modules.projectuiapi.base], ModuleCL@73c9d969[org.openide.explorer], ModuleCL@6d9c7516[org.netbeans.modules.projectuiapi], ModuleCL@7502fc08[org.openide.text], ...30 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
Caused: java.lang.NoClassDefFoundError: org/springframework/http/client/ClientHttpRequestFactory
	at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectWizardPanel1.getInitializrMetadata(InitializrProjectWizardPanel1.java:119)
	at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectPanelVisual1.construct(InitializrProjectPanelVisual1.java:403)
	at org.openide.util.AsyncInitSupport.run(AsyncInitSupport.java:143)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### How to reproduce

Open NetBeans 15 and the error is thrown
Click new project, select Spring Boot Initializer project and the second error is thrown and project cannot be created

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Windows 10 pro Version 21H2

### JDK

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
If this is an error with the Spring Boot plugin, please report at https://github.com/AlexFalappa/nb-springboot/issues  That plugin is not currently verified above NB12.

**Comment by Snoopy137** [comment]
> If this is an error with the Spring Boot plugin, please report at https://github.com/AlexFalappa/nb-springboot/issues That plugin is not currently verified above NB12.

Posted there, thanks!

**Comment by neilcsmith-net** [comment]
Thanks @Snoopy137 Will close this for now, but comment back (or get the author to) if this tracks back to a problem in the IDE.
