### ISSUE TITLE
My 3-module application compiles with "Illegal/unsupported escape sequence".

### ISSUE THREAD

**Issue by dan2see** [apache/netbeans#4998]
### Apache NetBeans version

Apache NetBeans 15

### What happened

I am creating a 3-module application, using the code from the book "Java 9 Modularity" by Mak and Bakker. I started with their example in Chapter 3, "Easytext three modules", although I changed the package names.
I

### How to reproduce

I entered the module-info code by actually typing the requires etc keywords by hand. I entered the Java classes by copying the book's code directly in the Netbeans IDE. The application has 3 modules. When I had completed the first 2 (analysis and cli) I clicked the "clean and build" toolbar button.

The message in the Output window seemed to show everything compiling, and in fact it resolved some cross-file errors as it went along.
But then it printed this:
----------------------------------------------
C:\Users\Daniel\Programming\Java\Modularity\EasyText34\nbproject\build-impl.xml:1328: 
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 65
\QC:\Users\Daniel\Programming\Java\Modularity\EasyText34\build\modules\\E([^\\]+)\Q\\E.*\.class
	at java.base/java.util.regex.Pattern.error(Pattern.java:2038)
----------------------------------------------

I looked into that xml file at line 1328. I don't see a problem there, so it might have been the variable it was accessing. I don't know.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Window 10 home, 64-bit, version 10.0.19045 Build 19045

### JDK

18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I have packaged my project, as-is, in a zip. I can email it to you:
let me know at daniel-cohen@shaw.ca

I ran another 2-module program earlier today, and I was pleased with how well the project went together.

This is my 2nd project with modules. I can see where all the project files are, although I'm not that familiar with the NetBeans internal project flow.

The error on the Output window reports an illegal/unsupported escape sequence as part of a file name. I expect it's deeper.

The first time I saw this, I abandoned the project and created another new project, different name, same contents. The second time I saw exactly the same error.

I am not willing to submit a pull request.
I have been using NetBeans since its early days,
but I am not familiar enough with Git. Not yet.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by dan2see** [comment]
Today is the next day, and I did not give up.
My program actually runs correctly when I hit the "Run Project (F6)" button.

But if I "Build" or "Clean and Build", it crashes. Here is the error report for "Build":
----------------------------------------
ant -f C:\\Users\\Daniel\\Programming\\Java\\Modularity\\EasyText33 -Dnb.internal.action.name=build jar
init:
Deleting: C:\Users\Daniel\Programming\Java\Modularity\EasyText33\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Daniel\Programming\Java\Modularity\EasyText33\build\built-jar.properties
Copying resources from src
compile:
C:\Users\Daniel\Programming\Java\Modularity\EasyText33\nbproject\build-impl.xml:1330: 
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 65
\QC:\Users\Daniel\Programming\Java\Modularity\EasyText33\build\modules\\E([^\\]+)\Q\\E.*\.class
	at java.base/java.util.regex.Pattern.error(Pattern.java:2038)
	at java.base/java.util.regex.Pattern.escape(Pattern.java:2618)
	at java.base/java.util.regex.Pattern.atom(Pattern.java:2296)
... more ...
----------------------------------------
This is the consistent result. The xml error is the Ant build-file that NetBeans generates.

- Daniel

**Comment by dan2see** [comment]
Next effort: I have Java-18 installed, and I wondered if the version might matter.
I removed 18 and installed Java-17 because it is LTS.
But no change, same error.

**Comment by mbien** [comment]
account does no longer exist
