### ISSUE TITLE
java debug asserts at start up and crashes out

### ISSUE THREAD

**Issue by OS4** [apache/netbeans#5020]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Attempts to launch a Java debug session causes the following assert:

```
/home/owen/.cache/netbeans/dev/executor-snippets/debug.xml:31: 
java.lang.AssertionError
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.<init>(ParserManager.java:354)
	at org.netbeans.modules.parsing.api.ParserManager.parseWhenScanFinished(ParserManager.java:341)
	at org.netbeans.api.java.source.SourceUtils.waitScanFinished(SourceUtils.java:785)
	at org.netbeans.modules.java.source.usages.BuildArtifactMapperImpl$DefaultCompileOnSaveAction.performSync(BuildArtifactMapperImpl.java:743)
	at org.netbeans.modules.java.source.usages.BuildArtifactMapperImpl$DefaultCompileOnSaveAction.performAction(BuildArtifactMapperImpl.java:660)
	at org.netbeans.modules.java.preprocessorbridge.api.CompileOnSaveActionQuery$ProxyAction.lambda$performAction$3(CompileOnSaveActionQuery.java:130)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.netbeans.modules.java.preprocessorbridge.api.CompileOnSaveActionQuery$ProxyAction.performAction(CompileOnSaveActionQuery.java:128)
	at org.netbeans.modules.java.source.usages.BuildArtifactMapperImpl.ensureBuilt(BuildArtifactMapperImpl.java:168)
	at org.netbeans.modules.java.source.ant.TranslateClassPath.translateEntry(TranslateClassPath.java:130)
	at org.netbeans.modules.java.source.ant.TranslateClassPath.translate(TranslateClassPath.java:91)
	at org.netbeans.modules.java.source.ant.TranslateClassPath.execute(TranslateClassPath.java:80)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:573)
	at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:81)
BUILD FAILED (total time: 0 seconds)
```

then it does nothing else, no debug session nor any further output. I assume the debugger just crashes out at this point.

I'm using the default JRE, which I think is open JDK 11, on Ubuntu 22.10. I have tried Oracle's JDK 8 as well and it throws exactly the same exception, so maybe it's Netbeans rather than an issue with the JDK or platform it's running on.

### How to reproduce

Debug any Java application

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Ubuntu 22.10 on Intel i7 64 bit

### JDK

openjdk version "11.0.17" 2022-10-18 OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu2) OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu2, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Occurs every time

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
this is an ant project?

i just created a new java ant project, set a breakpoint and started debugging. Everything worked.

NetBeans requires JDK 11 or later to run on. JRE is not sufficient.
you can set the path directly in the config file if you want:
https://github.com/apache/netbeans#log-config-and-cache-locations

**Comment by OS4** [comment]
Yes, somewhere down the line this has been fixed, debug launches fine now
