### ISSUE TITLE
[JS] StackOverflowError when trying to see function declaration

### ISSUE THREAD

**Issue by qmegas** [apache/netbeans#5032]
### Apache NetBeans version

Apache NetBeans 15

### What happened

That is a general error that happens to me frequently when trying to navigate to declaration while working on JS code. I can't provide exact code to reproduce, but here is the stack:

```
java.lang.StackOverflowError
	at java.base/java.util.HashMap.hash(HashMap.java:340)
	at java.base/java.util.HashMap.getNode(HashMap.java:570)
	at java.base/java.util.LinkedHashMap.get(LinkedHashMap.java:441)
	at org.netbeans.modules.javascript2.model.api.Index.getCachedValue(Index.java:246)
	at org.netbeans.modules.javascript2.model.api.Index.query(Index.java:185)
	at org.netbeans.modules.javascript2.model.api.Index.findByFqn(Index.java:412)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:301)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	.... and so on many times
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by qmegas** [comment]
Another, slightly different call stack for same error:

```
java.lang.StackOverflowError
	at org.netbeans.modules.javascript2.model.api.Index.getCachedValue(Index.java:264)
	at org.netbeans.modules.javascript2.model.api.Index.query(Index.java:185)
	at org.netbeans.modules.javascript2.model.api.Index.findByFqn(Index.java:412)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:301)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	at org.netbeans.modules.javascript2.editor.navigation.DeclarationFinderImpl.findPropertyOfType(DeclarationFinderImpl.java:311)
	.... and so on many times
```

After that error a navigation window and variable highlighting stops working completely.

**Comment by qmegas** [comment]
Confirm that error exists on Netbeans 16.
