### ISSUE TITLE
không gọi được packages trong cùng một source packages

### ISSUE THREAD

**Issue by anhkiet2k3** [apache/netbeans#5036]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.startsWith(java.nio.file.Path)" because "path" is null
	at org.netbeans.modules.gradle.GradleModuleFileCache21$CachedArtifactVersion.<init>(GradleModuleFileCache21.java:143)
	at org.netbeans.modules.gradle.GradleModuleFileCache21.resolveCachedArtifactVersion(GradleModuleFileCache21.java:225)
	at org.netbeans.modules.gradle.api.GradleProjects.getSources(GradleProjects.java:50)
	at org.netbeans.modules.gradle.java.queries.GradleSourceForRepository.findSourceRoots2(GradleSourceForRepository.java:61)
	at org.netbeans.api.java.queries.SourceForBinaryQuery.findSourceRoots2(SourceForBinaryQuery.java:101)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.createResources(PathRegistry.java:728)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.getRootPathIds(PathRegistry.java:583)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.getSourceIdsFor(PathRegistry.java:441)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.isIncompleteRoot(PathRegistry.java:524)
	at org.netbeans.modules.parsing.impl.indexing.PathRegistry.isIncompleteRoot(PathRegistry.java:558)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$FileListWork.getDone(RepositoryUpdater.java:3800)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3422)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6200)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4400(RepositoryUpdater.java:5851)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6108)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6108)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### How to reproduce

không biết

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

JDK 16

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

mới đây

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
english

how to report issues:
https://netbeans.apache.org/participate/report-issue.html
