### ISSUE TITLE
NetBeans 16 doesn't redeploy project on Tomcat 9.

### ISSUE THREAD

**Issue by KempesGit** [apache/netbeans#5154]
### Apache NetBeans version

Apache NetBeans 16

### What happened

During project start I got error:

```
Starting Tomcat process...
Waiting for Tomcat...
Tomcat server started.
Incrementally deploying http://localhost:8080/Generator_Best
Completed incremental distribution of http://localhost:8080/Generator_Best
Incrementally redeploying http://localhost:8080/Generator_Best
C:\Users\artur\OneDrive\Documents\NetBeansProjects\Generator_Best\nbproject\build-impl.xml:1063: 
java.lang.NoSuchMethodError: java.net.URLEncoder.encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at org.netbeans.modules.tomcat5.deploy.TomcatManagerImpl.encodePath(TomcatManagerImpl.java:336)
	at org.netbeans.modules.tomcat5.deploy.TomcatManagerImpl.remove(TomcatManagerImpl.java:232)
	at org.netbeans.modules.tomcat5.optional.TomcatIncrementalDeployment.incrementalDeploy(TomcatIncrementalDeployment.java:99)
	at org.netbeans.modules.j2ee.deployment.impl.TargetServer.deploy(TargetServer.java:706)
	at org.netbeans.modules.j2ee.deployment.devmodules.api.Deployment.deploy(Deployment.java:221)
	at org.netbeans.modules.j2ee.deployment.devmodules.api.Deployment.deploy(Deployment.java:141)
	at org.netbeans.modules.j2ee.ant.Deploy.execute(Deploy.java:86)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:573)
	at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:81)
BUILD FAILED (total time: 15 seconds)
```

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Windows 10

### JDK

8.231

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Tomcat 9.0.68

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by cesarcip** [comment]
Same exception with Ubuntu 22.04, OpenJdk 11, Tomcat 10.1.4, Netbeans 16, when runing project deployed to Tomcat.

**Comment by matthiasblaesing** [comment]
Please have a look at the referenced PR. There is also a test build availble.

**Comment by cesarcip** [comment]
Tested Apache NetBeans IDE DEV (Build dev-426207b4622d355d5206e6e2c6e6085db1474b99). No error for me. Project deployed to Tomcat without errors.
