### ISSUE TITLE
NPE in Java hints PreconditionsChecker.java line 226

### ISSUE THREAD

**Issue by jjazzboss** [apache/netbeans#5202]
### Apache NetBeans version

Apache NetBeans 16

### What happened

I was editing a java file, I noticed the Exception appeared but not sure when exactly, and what I was doing when it happened.

### How to reproduce

I can't reproduce but I was editing the switch/case of the 2 methods of a single java file when it happened. I copied the 2 
methods below (if you need the whole file tell me).

```java
    @Override
    public void noteDragged(MouseEvent e, NoteView nvSource)
    {
        var neSource = nvSource.getModel();
        var point = e.getPoint();
        boolean overrideSnapSetting = isOverrideSnapSetting(e);
        Point editorPoint = SwingUtilities.convertPoint(nvSource, e.getPoint(), nvSource.getParent());
        editorPoint.x = Math.max(0, editorPoint.x);
        editorPoint.x = Math.min(nvSource.getParent().getWidth() - 1, editorPoint.x);
        float editorPointPos = editor.getPositionFromPoint(editorPoint);
        Quantization q = editor.getQuantization();
        
        
        if (!isDragging)
        {
            // Start dragging
            isDragging = true;
            dragStartPos = editorPointPos;
            dragNoteOffset = point;
            dragStartPitch = neSource.getPitch();
            mapSrcDragNotes.clear();

            // Adjust selection if required
            var selectedNotes = editor.getSelectedNotes();
            if (!selectedNotes.contains(neSource))
            {
                editor.unselectAll();
                nvSource.setSelected(true);
                // Create one drag note
                mapSrcDragNotes.put(neSource, neSource.clone());
            } else
            {
                // Create the drag notes for the selected notes
                selectedNotes.forEach(ne -> mapSrcDragNotes.put(ne, ne.clone()));
            }
            
            
            switch (state)
            {
                case EDITOR:
                case RESIZE_WEST:
                case RESIZE_EAST:
                    mapSrcDragNotes.keySet().forEach(ne -> spModel.replace(ne, mapSrcDragNotes.get(ne)));
                    break;
                case MOVE:
                case COPY:
                    
                    mapSrcDragNotes.values().forEach(ne -> spModel.add(ne));
                    dragNoteView = editor.getNoteView(mapSrcDragNotes.get(neSource));

                    // Listen to ctrl key
                    addControlKeyListener(dragNoteView);
                    
                    break;
                default:
                    throw new AssertionError(state.name());
            }
            
            
            LOGGER.log(Level.FINE, "\n----- noteDragged() ----- START ne={0}   state={1}  dragNoteStartPos={2}  mapSrcDragNotes={3}", new Object[]
            {
                neSource, state, dragStartPos, mapSrcDragNotes
            });
            
            
        } else
        {
            // Continue dragging


            // Quantize new position if required
            if ((editor.isSnapEnabled() && !overrideSnapSetting) || (!editor.isSnapEnabled() && overrideSnapSetting))
            {
                editorPointPos = Quantizer.getQuantized(q, editorPointPos);
            }
            
            
            switch (state)
            {
                case EDITOR:
                    break;
                case RESIZE_WEST:
                {
                    float dPos = editorPointPos - dragStartPos;
                    
                    for (var srcNe : mapSrcDragNotes.keySet())
                    {
                        float newPos = srcNe.getPositionInBeats() + dPos;
                        
                        if (newPos >= 0 && dPos < (srcNe.getDurationInBeats() - 0.05f))
                        {
                            var dragNe = mapSrcDragNotes.get(srcNe);
                            float newDur = srcNe.getDurationInBeats() - dPos;
                            var newNe = srcNe.getCopyDurPos(newDur, newPos);
                            spModel.replace(dragNe, newNe);
                            mapSrcDragNotes.put(srcNe, newNe);
                        }
                    }
                }
                break;
                case RESIZE_EAST:
                {
                    float dPos = editorPointPos - dragStartPos;
                    
                    for (var srcNe : mapSrcDragNotes.keySet())
                    {
                        float newDur = Math.max(srcNe.getDurationInBeats() + dPos, 0.05f);
                        if (Float.floatToIntBits(srcNe.getDurationInBeats()) != Float.floatToIntBits(newDur) && (srcNe.getPositionInBeats() + newDur) < spModel.getBeatRange().to)
                        {
                            var dragNe = mapSrcDragNotes.get(srcNe);
                            var newNe = srcNe.getCopyDur(newDur);
                            spModel.replace(dragNe, newNe);
                            mapSrcDragNotes.put(srcNe, newNe);
                        }
                    }
                }
                break;
                case COPY:
                case MOVE:
                {
                    // Pitch delta
                    int newPitch = editor.getPitchFromPoint(editorPoint);
                    int dPitch = newPitch - dragStartPitch;

                    // Position delta
                    float dPos = editorPointPos - dragStartPos;


                    // Apply to each note
                    for (var sne : mapSrcDragNotes.keySet())
                    {
                        var dragNe = mapSrcDragNotes.get(sne);

                        // Calculate pos/pitch changes
                        float newPos = sne.getPositionInBeats() + dPos;
                        newPos = Math.max(0, newPos);
                        if (newPos + sne.getDurationInBeats() >= spModel.getBeatRange().to)
                        {
                            newPos = spModel.getBeatRange().to - sne.getDurationInBeats();
                        }
                        newPitch = isConstantPitchModifier(e) ? sne.getPitch() : MidiUtilities.limit(sne.getPitch() + dPitch);
                        
                        
                        if (dragNe.getPitch() == newPitch && Float.floatToIntBits(dragNe.getPositionInBeats()) == Float.floatToIntBits(newPos))
                        {
                            
                            return;
                        }
                        LOGGER.log(Level.FINE, "\nnoteDragged() continue dragging newPitch={0} newPos={1}", new Object[]
                        {
                            newPitch, newPos
                        });
                        
                        
                        var newNe = spModel.move(dragNe, newPos);   // Does nothing if newPos unchanged                        
                        if (newNe.getPitch() != newPitch)
                        {
                            var newNePitch = newNe.getCopyPitch(newPitch);
                            spModel.replace(newNe, newNePitch);
                            newNe = newNePitch;
                        }
                        
                        mapSrcDragNotes.put(sne, newNe);
                    }
                    
                }
                break;
                default:
                    throw new AssertionError(state.name());
            }
        }
    }
    
    @Override
    public void noteReleased(MouseEvent e, NoteView nv)
    {
        if (!isDragging)
        {
            return;
        }
        
        var ne = nv.getModel();
        var container = nv.getParent();         // Save if nv is removed
        LOGGER.log(Level.FINE, "\nnoteReleased() -- state={0} ne={1} mapSrcDragNotes={2}", new Object[]
        {
            state, ne, mapSrcDragNotes
        });
        
        
        switch (state)
        {
            case EDITOR:
                // Nothing
                break;
            case RESIZE_WEST:
            case RESIZE_EAST:
            {
                // Restore original state before doing the undoable edit
                for (var srcNe : mapSrcDragNotes.keySet())
                {
                    var dragNe = mapSrcDragNotes.get(srcNe);
                    spModel.replace(dragNe, srcNe);
                }
                
                
                String undoText = ResUtil.getString(getClass(), "ResizeNote");
                editor.getUndoManager().startCEdit(undoText);
                
                for (var srcNe : mapSrcDragNotes.keySet())
                {
                    var dragNe = mapSrcDragNotes.get(srcNe);
                    spModel.replace(srcNe, dragNe);
                    editor.getNoteView(dragNe).setSelected(true);
                }
                
                editor.getUndoManager().endCEdit(undoText);
                break;
            }
            
            case MOVE:
            {
                removeControlKeyListener(dragNoteView);


                // Restore original state before doing the undoable edit
                mapSrcDragNotes.values().forEach(dragNe -> spModel.remove(dragNe));
                
                
                String undoText = ResUtil.getString(getClass(), "MoveNote");
                editor.getUndoManager().startCEdit(undoText);
                
                for (var srcNe : mapSrcDragNotes.keySet())
                {
                    var dragNe = mapSrcDragNotes.get(srcNe);
                    spModel.replace(srcNe, dragNe);
                    editor.getNoteView(dragNe).setSelected(true);
                }
                
                editor.getUndoManager().endCEdit(undoText);
                
                
                break;
            }
            case COPY:
            {
                removeControlKeyListener(dragNoteView);

                // Restore original state before doing the undoable edit
                mapSrcDragNotes.values().forEach(dragNe -> spModel.remove(dragNe));
                
                
                String undoText = ResUtil.getString(getClass(), "CopyNote");
                editor.getUndoManager().startCEdit(undoText);
                
                for (var srcNe : mapSrcDragNotes.keySet())
                {
                    var dragNe = mapSrcDragNotes.get(srcNe);
                    spModel.add(dragNe);
                    editor.getNoteView(dragNe).setSelected(true);
                    editor.getNoteView(srcNe).setSelected(false);
                }
                
                editor.getUndoManager().endCEdit(undoText);
                
                
                break;
            }
            default:
                throw new AssertionError(state.name());
            
        }
        isDragging = false;
        dragStartPos = -1;
        mapSrcDragNotes.clear();
        dragNoteOffset = null;
        dragNoteView = null;
        
        
        changeState(State.EDITOR, container);
    }
    
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win10 x64

### JDK

JDK 17 x64 Adoptium

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
what was the exception? It should be in the log.

**Comment by jjazzboss** [comment]
Sorry, I forgot to paste it yesterday.  I checked the yesterday's Netbeans log, it was still there, I copied the relevant part below. Strangely, exception origin in the log is in NBJavacTrees.java, but I'm quite sure yesterday, in the exception reporting Netbeans dialog (I did not check the log), it was in PreconditionsChecker...



...
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.org.apache.xpath.internal.operations.String ]
INFO [org.netbeans.modules.java.editor.imports.ComputeImports]: Cannot resolve type element "ElementHandle[kind=CLASS; sigs=com.sun.org.apache.xpath.internal.operations.String ]".
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = INTERFACE
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=INTERFACE; sigs=com.sun.tools.javac.jvm.PoolConstant$LoadableConstant ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.org.apache.xpath.internal.operations.String ]
INFO [org.netbeans.modules.java.editor.imports.ComputeImports]: Cannot resolve type element "ElementHandle[kind=CLASS; sigs=com.sun.org.apache.xpath.internal.operations.String ]".
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = INTERFACE
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=INTERFACE; sigs=com.sun.tools.javac.jvm.PoolConstant$LoadableConstant ]
INFO [org.netbeans.modules.java.hints.providers.code.CodeHintProviderImpl$WorkerImpl]: org.netbeans.modules.java.hints.jdk.mapreduce.ForLoopToFunctionalHint.computeWarning
java.lang.NullPointerException: Cannot invoke "com.sun.source.util.TreePath.getLeaf()" because "path" is null
	at org.netbeans.lib.nbjavac.services.NBJavacTrees.getElement(NBJavacTrees.java:66)
	at org.netbeans.lib.nbjavac.services.NBJavacTrees.getElement(NBJavacTrees.java:40)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.isLocalVariable(PreconditionsChecker.java:226)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitIdentifier(PreconditionsChecker.java:218)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitIdentifier(PreconditionsChecker.java:192)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2672)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:241)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitVariable(PreconditionsChecker.java:213)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitVariable(PreconditionsChecker.java:192)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1036)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1094)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.ErrorAwareTreeScanner.visitErroneous(ErrorAwareTreeScanner.java:34)
	at com.sun.tools.javac.tree.JCTree$JCErroneous.accept(JCTree.java:3348)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:502)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1594)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.visitEnhancedForLoop(TreeScanner.java:338)
	at com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1234)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker.getInnerVariables(PreconditionsChecker.java:90)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker.<init>(PreconditionsChecker.java:75)
	at org.netbeans.modules.java.hints.jdk.mapreduce.ForLoopToFunctionalHint.computeWarning(ForLoopToFunctionalHint.java:54)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[catch] at org.netbeans.modules.java.hints.providers.code.CodeHintProviderImpl$WorkerImpl.createErrors(CodeHintProviderImpl.java:315)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.runHint(HintsInvoker.java:794)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.access$400(HintsInvoker.java:89)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.runAndAdd(HintsInvoker.java:656)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scanDoNotGoDeeper(HintsInvoker.java:710)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeSuggestions(HintsInvoker.java:384)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:220)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:192)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:165)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:127)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:113)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:63)
	at org.netbeans.modules.java.source.JavaSourceAccessor$CancelableTaskWrapper.run(JavaSourceAccessor.java:273)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
SEVERE [org.openide.util.Exceptions]
java.lang.NullPointerException: Cannot invoke "com.sun.source.util.TreePath.getLeaf()" because "path" is null
	at org.netbeans.lib.nbjavac.services.NBJavacTrees.getElement(NBJavacTrees.java:66)
	at org.netbeans.lib.nbjavac.services.NBJavacTrees.getElement(NBJavacTrees.java:40)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.isLocalVariable(PreconditionsChecker.java:226)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitIdentifier(PreconditionsChecker.java:218)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitIdentifier(PreconditionsChecker.java:192)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2672)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:241)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitVariable(PreconditionsChecker.java:213)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.visitVariable(PreconditionsChecker.java:192)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1036)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1094)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.ErrorAwareTreeScanner.visitErroneous(ErrorAwareTreeScanner.java:34)
	at com.sun.tools.javac.tree.JCTree$JCErroneous.accept(JCTree.java:3348)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:502)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1594)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.visitEnhancedForLoop(TreeScanner.java:338)
	at com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1234)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker.getInnerVariables(PreconditionsChecker.java:90)
	at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker.<init>(PreconditionsChecker.java:75)
	at org.netbeans.modules.java.hints.jdk.mapreduce.ForLoopToFunctionalHint.computeWarning(ForLoopToFunctionalHint.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[catch] at org.netbeans.modules.java.hints.providers.code.CodeHintProviderImpl$WorkerImpl.createErrors(CodeHintProviderImpl.java:315)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.runHint(HintsInvoker.java:794)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.access$400(HintsInvoker.java:89)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.runAndAdd(HintsInvoker.java:656)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scanDoNotGoDeeper(HintsInvoker.java:710)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeSuggestions(HintsInvoker.java:384)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:220)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:192)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:165)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:127)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:113)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:63)
	at org.netbeans.modules.java.source.JavaSourceAccessor$CancelableTaskWrapper.run(JavaSourceAccessor.java:273)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
WARNING [org.netbeans.modules.java.source.parsing.VanillaPartialReparser]: Javac returned startpos: 11?295 > endpos: -1
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
WARNING [org.netbeans.modules.java.source.parsing.VanillaPartialReparser]: Javac returned startpos: 11?295 > endpos: -1
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 333?482 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 302 ms.
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 64?512 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 321 ms.
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 17?559 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 958 ms.
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 20?895 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 265 ms.
INFO [org.netbeans.api.java.source.ElementHandle]: Resolved type is null for kind = CLASS
INFO [org.netbeans.api.java.source.ElementHandle]: Cannot resolve: ElementHandle[kind=CLASS; sigs=com.sun.tools.javac.util.Names ]
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 80?049 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 359 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 17?599 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 68 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 0 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 64 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 28?412 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 0 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 0 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 0 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 2?385?721 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 0 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 180?690 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 297 ms.
suiteProject=D:\JeromeDocs\JJazzLab\src\JJazzLab-X@a74b2525:1cd0272c
WARNING [org.openide.text.CloneableEditorSupport]: org.netbeans.modules.xml.text.TextEditorSupport should override asynchronousOpen(). See http://bits.netbeans.org/dev/javadoc/org-openide-text/apichanges.html#CloneableEditorSupport.asynchronousOpen
suiteProject=D:\JeromeDocs\JJazzLab\src\JJazzLab-X@a74b2525:1cd0272c
INFO [null]: Last record repeated 3 more times.
INFO [null]: Last record repeated 5 more times.
WARNING [org.openide.util.actions.CallableSystemAction]: Warning - org.netbeans.modules.search.ui.OpenMatchingObjectsAction should override CallableSystemAction.asynchronous() to return false
INFO [org.netbeans.modules.parsing.impl.TaskProcessor]: Task: org.netbeans.modules.java.editor.semantic.SemanticHighlighter@3b9c3917 : class org.netbeans.modules.java.editor.semantic.SemanticHighlighter ignored cancel for 1?917 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 142?667 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 215 ms.

**Comment by mbien** [comment]
the NPE should be fixed by the PR linked above.
