### ISSUE TITLE
Unable to open gradle web project

### ISSUE THREAD

**Issue by soul-au** [apache/netbeans#5248]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Operation：new-project->Java with Gradle ->Web Application
Jdk version: java 11 2018-09-25
Server version：apache-tomcat-8.5.84
Error Message：
java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.netbeans.modules.gradle.GradleJavaCompatProblemsProvider.getJavaMajorVersion(GradleJavaCompatProblemsProvider.java:147)
	at org.netbeans.modules.gradle.GradleJavaCompatProblemsProvider.getJavaVersion(GradleJavaCompatProblemsProvider.java:128)
	at org.netbeans.modules.gradle.GradleJavaCompatProblemsProvider.getProblems(GradleJavaCompatProblemsProvider.java:91)
	at org.netbeans.spi.project.ui.support.UILookupMergerSupport$ProjectProblemsProviderImpl.getProblems(UILookupMergerSupport.java:274)
	at org.netbeans.api.project.ui.ProjectProblems.isBroken(ProjectProblems.java:58)
	at org.netbeans.modules.gradle.NbGradleProjectImpl$ProjectOpenedHookImpl.lambda$projectOpened$0(NbGradleProjectImpl.java:689)
	at org.netbeans.modules.gradle.NbGradleProjectImpl$ProjectOpenedHookImpl.projectOpened(NbGradleProjectImpl.java:696)
	at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:60)
	at org.netbeans.spi.project.ui.support.UILookupMergerSupport$OpenHookImpl.projectOpened(UILookupMergerSupport.java:219)
	at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:60)
[catch] at org.netbeans.modules.project.ui.OpenProjectList.notifyOpened(OpenProjectList.java:1321)
	at org.netbeans.modules.project.ui.OpenProjectList.doOpenProject(OpenProjectList.java:1402)
	at org.netbeans.modules.project.ui.OpenProjectList.open(OpenProjectList.java:848)
	at org.netbeans.modules.project.ui.OpenProjectList$6.run(OpenProjectList.java:672)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows11

### JDK

java 11 2018-09-25

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by soul-au** [comment]
I think it may be because I updated these two plug-ins, because the project can be opened after reinstalling the program

Gradle     Gradle Java Projects [1.20.0.1 -> 1.20.1.1] Gradle Editor Support     Gradle Projects [2.29 -> 2.29.1]

**Comment by soul-au** [comment]
I tried to update the plug-in and found that the project could not be opened again

**Comment by lkishalmi** [comment]
It seems the Gradle WebApplication plugin needs some love.
