### ISSUE TITLE
Latest upgrade of Gradle plugin fails to open project with Java 17 in Windows

### ISSUE THREAD

**Issue by epliskin** [apache/netbeans#5252]
### Apache NetBeans version

Apache NetBeans 16

### What happened

After upgrading the Gradle plugin to the latest version today I could not open my Gradle project running NetBeans on Java 17 on Windows. The following error message appears:

```
java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at org.netbeans.modules.gradle.GradleJavaCompatProblemsProvider.getJavaMajorVersion(GradleJavaCompatProblemsProvider.java:147)
	at org.netbeans.modules.gradle.GradleJavaCompatProblemsProvider.getJavaVersion(GradleJavaCompatProblemsProvider.java:128)
	at org.netbeans.modules.gradle.GradleJavaCompatProblemsProvider.getProblems(GradleJavaCompatProblemsProvider.java:91)
	at org.netbeans.spi.project.ui.support.UILookupMergerSupport$ProjectProblemsProviderImpl.getProblems(UILookupMergerSupport.java:274)
	at org.netbeans.api.project.ui.ProjectProblems.isBroken(ProjectProblems.java:58)
	at org.netbeans.modules.gradle.NbGradleProjectImpl$ProjectOpenedHookImpl.lambda$projectOpened$0(NbGradleProjectImpl.java:689)
	at org.netbeans.modules.gradle.NbGradleProjectImpl$ProjectOpenedHookImpl.projectOpened(NbGradleProjectImpl.java:696)
	at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:60)
	at org.netbeans.spi.project.ui.support.UILookupMergerSupport$OpenHookImpl.projectOpened(UILookupMergerSupport.java:219)
	at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:60)
[catch] at org.netbeans.modules.project.ui.OpenProjectList.notifyOpened(OpenProjectList.java:1321)
	at org.netbeans.modules.project.ui.OpenProjectList.doOpenProject(OpenProjectList.java:1402)
	at org.netbeans.modules.project.ui.OpenProjectList.open(OpenProjectList.java:848)
	at org.netbeans.modules.project.ui.OpenProjectList$6.run(OpenProjectList.java:672)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

After changing a line in the netbeans.conf file from 
`netbeans_jdkhome="C:\Program Files\Java\jdk-17"
`
to 
`netbeans_jdkhome="C:\Program Files\Java\jdk-18.0.1.1"
`
I could open the Gradle project as usual.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

17 OpenJDK

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
same exception got reported in #5248 which was also on windows

**Comment by lkishalmi** [comment]
Could you attach the `C:\Program Files\Java\jdk-17\release` file?

**Comment by epliskin** [comment]
C:\Program Files\Java\jdk-17\release
[release.txt](https://github.com/apache/netbeans/files/10388970/release.txt)

**Comment by lkishalmi** [comment]
Oh, no dots in the Java Version! What an oversight from me!

The fix is simple, if you would like to use Java 17, install something more recent. it will have `"17.0.x"` in `JAVA_VERSION`, so it would work.  Will be fixed in NB17.
