### ISSUE TITLE
Ctrl-click on java method does nothing and gives NPE in IDE log

### ISSUE THREAD

**Issue by makiam** [apache/netbeans#5256]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Ctrl-click on java method does nothing and gives NPE in IDE log.
Also Go-To Source is not working too.
The NPE is: 
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.name" is null
	at org.netbeans.api.java.source.SourceUtils$Match.apply(SourceUtils.java:686)
	at org.netbeans.api.java.source.SourceUtils.findMatchingChild(SourceUtils.java:631)
	at org.netbeans.api.java.source.SourceUtils.findSourceForBinary(SourceUtils.java:614)
	at org.netbeans.api.java.source.SourceUtils.getFile(SourceUtils.java:582)
	at org.netbeans.api.java.source.ui.ElementOpen.getOpenInfo(ElementOpen.java:444)
	at org.netbeans.api.java.source.ui.ElementOpen.open(ElementOpen.java:125)
	at org.netbeans.api.java.source.ui.ElementOpen.open(ElementOpen.java:120)
	at org.netbeans.modules.editor.java.GoToSupport$7.open(GoToSupport.java:1263)
	at org.netbeans.modules.editor.java.GoToSupport.performGoToImpl(GoToSupport.java:285)
	at org.netbeans.modules.editor.java.GoToSupport.access$100(GoToSupport.java:125)
	at org.netbeans.modules.editor.java.GoToSupport$3.run(GoToSupport.java:224)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$1.run(RunOffEDTImpl.java:146)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### How to reproduce

I reproduce this with my Gradle project.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Java: 18.0.2; Java HotSpot(TM) 64-Bit Server VM 18.0.2+9-61

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by ratcashdev** [comment]
Having the same issue without using lombok with the latest nightly.
