### ISSUE TITLE
"Extract source name from .class and use it to locate proper source" (#5152) breaks java source editing

### ISSUE THREAD

**Issue by matthiasblaesing** [apache/netbeans#5266]
### Body

Steps to reproduce:

1. Create a clone of the JNA repository. In a directory of your choosing run `git clone https://github.com/java-native-access/jna.git`
2. In your NetBeans Source Tree go to the last commit before your merge: `git checkout c07ee007fd18`
3. Ensure directory is clean: `git clean -f -x -d`
4. Build: `ant`
5. Run tryme: `ant tryme`
6. Open the JNA NetBeans project from the folder you cloned in step 1.
7. Open test file NativeLibraryTest.java (Package com.sun.jna), go to line 91, right click on `disposeAll`, choose  Navigate -> Goto Source
8. Observe, that you are taken to the Method `disposeAll` in `NativeLibrary.java`
9. Close NetBeans
10. Checkout your merge commit: `git checkout 2a9e190afaf799bd0c126f0ffc6c70c9f0f9a305`
11. Build: `ant`
12. Run tryme: `ant tryme`
13. Repeat Step 7
14. Observe, that you are **not** taken to the source, but an exception is reported:
```
java.lang.NullPointerException
	at org.netbeans.api.java.source.SourceUtils$Match.apply(SourceUtils.java:686)
	at org.netbeans.api.java.source.SourceUtils.findMatchingChild(SourceUtils.java:631)
	at org.netbeans.api.java.source.SourceUtils.findSourceForBinary(SourceUtils.java:614)
	at org.netbeans.api.java.source.SourceUtils.getFile(SourceUtils.java:582)
	at org.netbeans.api.java.source.ui.ElementOpen.getOpenInfo(ElementOpen.java:444)
	at org.netbeans.api.java.source.ui.ElementOpen.open(ElementOpen.java:125)
	at org.netbeans.api.java.source.ui.ElementOpen.open(ElementOpen.java:120)
	at org.netbeans.modules.editor.java.GoToSupport$7.open(GoToSupport.java:1263)
	at org.netbeans.modules.editor.java.GoToSupport.performGoToImpl(GoToSupport.java:285)
	at org.netbeans.modules.editor.java.GoToSupport.access$100(GoToSupport.java:125)
	at org.netbeans.modules.editor.java.GoToSupport$3.run(GoToSupport.java:224)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$1.run(RunOffEDTImpl.java:146)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:395)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl.runOffEventDispatchThreadImpl(RunOffEDTImpl.java:140)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl.runOffEventDispatchThread(RunOffEDTImpl.java:83)
	at org.netbeans.api.progress.BaseProgressUtils.runOffEventDispatchThread(BaseProgressUtils.java:90)
	at org.netbeans.api.progress.ProgressUtils.runOffEventDispatchThread(ProgressUtils.java:68)
	at org.netbeans.modules.editor.java.GoToSupport.performGoTo(GoToSupport.java:221)
	at org.netbeans.modules.editor.java.GoToSupport.goTo(GoToSupport.java:389)
	at org.netbeans.modules.editor.java.JavaKit$JavaGoToSourceAction.actionPerformed(JavaKit.java:731)
	at org.netbeans.editor.BaseAction.actionPerformed(BaseAction.java:322)
	at org.netbeans.spi.editor.AbstractEditorAction.actionPerformed(AbstractEditorAction.java:445)
	at org.netbeans.modules.editor.lib2.actions.PresenterUpdater.actionPerformed(PresenterUpdater.java:385)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[catch] at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Committer

- [X] I acknowledge that I am a maintainer/committer in the Apache NetBeans project.

**Comment by matthiasblaesing** [comment]
Debugging shows, that the filename in the `ElementHandle` is `null`:

![image](https://user-images.githubusercontent.com/2179736/211680437-da4e4154-429c-4ad3-880c-ed5a40cec294.png)

And this is passed down unchecked, until it blows in `SourceUtils$Match`.
