### ISSUE TITLE
Netbeans "Run File" doesn't work on JSP (Java Web Application)

### ISSUE THREAD

**Issue by Prashant2040** [apache/netbeans#5515]
### Apache NetBeans version

Apache NetBeans 16

### What happened

I am trying to make project on NetBeans IDE version 12.6 using JSP file but when I finished the code writing and tries to run it did nothing, no response at all I tried running file multiple times but still nothing happened there was no error, no console, no browser opening.
Then I restarted the IDE and made another project using JSP file again this time nothing happened as well.
then I tried to run program manually in browser using project address this time it worked fine but when I run on ide it not doing anything
Please share a solution if you find any.
I have downloaded and installed Netbeans IDE 12.6, JDK 18 and Apache Tomcat 10 (from the official sites).

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 

### JDK

18.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This Problem is only happening with JSP file only. I have recently made projects using servlet, java class and frame form they all are working fine but the problem is happening with JSP file only.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
NetBeans 12.6 is unsupported, and it did not support JDK 18.  Please try with a NetBeans 16 or 17~rc3.

**Comment by UmaidJawed** [comment]
Even in my system it is not working  as I am using JDK-17 and Netbeans IDE 21 latest version and it is compatible . But still after running the JSP file it is giving me this error:   
Exception in thread "main" java.lang.IllegalArgumentException: PWC6309: Illegal compilerSourceVM: 17 	at org.apache.jasper.JspC.setCompilerSourceVM(JspC.java:684) 	at org.netbeans.modules.web.project.ant.JspC.main(JspC.java:55) 	at org.netbeans.modules.web.project.ant.JspCSingle.main(JspCSingle.java:94) C:\Users\umaid\OneDrive\Documents\NetBeansProjects\ToDojsp\nbproject\build-impl.xml:921: Java returned: 1 BUILD FAILED (total time: 0 seconds)

**Comment by mbien** [comment]
closing due to inactivity

btw running JSPs seems to be working fine: I created a "Web Application" maven project, removed the index.html, added a jsp and pressed run file. Payara started and Hello World opened in the Browser.
