### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: start -2, end 0, length 0 ... org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)

### ISSUE THREAD

**Issue by dathyrius** [apache/netbeans#5574]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Problem occured while opening my project. 
java.lang.StringIndexOutOfBoundsException: start -2, end 0, length 0
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1724)
	at java.base/java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:863)
	at java.base/java.lang.StringBuilder.delete(StringBuilder.java:289)
	at com.github.philippefichet.sonarlint4netbeans.ui.SonarLintAnalyzerActionTopComponent.addDeepSonarLintAnalyze(SonarLintAnalyzerActionTopComponent.java:119)
	at com.github.philippefichet.sonarlint4netbeans.SonarLintAnalyzerAction.lambda$performAction$0(SonarLintAnalyzerAction.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
>System Info: 
  Product Version         = Apache NetBeans IDE 17
  Operating System        = Mac OS X version 13.0.1 running on aarch64
  Java; VM; Vendor        = 11.0.17; Java HotSpot(TM) 64-Bit Server VM 11.0.17+10-LTS-269; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 11.0.17+10-LTS-269
  Java Home               = /Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home
  System Locale; Encoding = de_DE (nb); UTF-8

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

MACOS

### JDK

11.0.17; Java HotSpot(TM) 64-Bit Server VM 11.0.17+10-LTS-269; Oracle Corporation

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
That appears to be a bug in the SonarLint plugin for NetBeans?  Please report the issue with them first https://github.com/philippefichet/sonarlint4netbeans
