### ISSUE TITLE
Pass from Mac to Windows SO, form gui file error 

### ISSUE THREAD

**Issue by asetyde** [apache/netbeans#5622]
### Apache NetBeans version

Apache NetBeans 17

### What happened

after passage from mac to windows my netbeans project with swing gui, give me error that i not find to resolve it or how

![8owCn](https://user-images.githubusercontent.com/6162152/223430210-15c5b539-3ec7-41a8-9df3-e3af4c4bad05.png)

![ajgnS](https://user-images.githubusercontent.com/6162152/223430232-bb4dfc58-05b3-4797-bdf0-7eed39158ec3.png)

Try to modify swing gui of each panel return jpanel or jframe empy but no exception

exc:

org.netbeans.modules.form.PersistenceException: Unknown property at org.netbeans.modules.form.GandalfPersistenceManager.loadProperty(GandalfPersistenceManager.java:2028) at org.netbeans.modules.form.GandalfPersistenceManager.loadComponentProperties(GandalfPersistenceManager.java:2001) at org.netbeans.modules.form.GandalfPersistenceManager.loadComponent(GandalfPersistenceManager.java:835) at org.netbeans.modules.form.GandalfPersistenceManager.loadForm(GandalfPersistenceManager.java:484) at org.netbeans.modules.form.GandalfPersistenceManager.loadForm(GandalfPersistenceManager.java:260) at org.netbeans.modules.form.FormEditor$2.run(FormEditor.java:327) at org.netbeans.modules.form.FormLAF$2.run(FormLAF.java:268) at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:123) at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:77) at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71) at org.openide.util.Mutex.readAccess(Mutex.java:232) at org.netbeans.modules.form.FormLAF.executeWithLookAndFeel(FormLAF.java:251) at org.netbeans.modules.form.FormEditor.loadFormData(FormEditor.java:324) at org.netbeans.modules.nbform.FormEditorSupport.loadOpeningForm(FormEditorSupport.java:436) at org.netbeans.modules.nbform.FormDesignerTC.loadForm(FormDesignerTC.java:256) at org.netbeans.modules.nbform.FormDesignerTC.access$300(FormDesignerTC.java:64) at org.netbeans.modules.nbform.FormDesignerTC$PreLoadTask$1.run(FormDesignerTC.java:245) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741) at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

1.7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by asetyde** [comment]
UPDATE :   
i'm tryng to reuse macos downloading neutrally code from git , seems not have problems, therefore is platform problem, absurd for java .. i'm testing in these days
