### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.web.indent.api.support.IndenterFormattingContext.setLastIndenter()" because "last" is null

### ISSUE THREAD

**Issue by nobodyhugh** [apache/netbeans#5665]
### Apache NetBeans version

Apache NetBeans 17

### What happened

PHP Editor's auto completion not work correctly.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS

### JDK

OpenJDK 19

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by stborchert** [comment]
After updating from Netbeans v16 to v17 on MacOS I also ran into this problem. Trying to format code results in a NullPointerException:
```
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.web.indent.api.support.IndenterFormattingContext.setLastIndenter()" because "last" is null
	at org.netbeans.modules.web.indent.api.support.AbstractIndenter.beforeReindent(AbstractIndenter.java:128)
	at org.netbeans.modules.web.indent.api.support.AbstractIndenter.reindent(AbstractIndenter.java:197)
	at org.netbeans.modules.html.editor.indent.HtmlIndentTask.reindent(HtmlIndentTask.java:49)
	at de.funfried.netbeans.plugins.external.formatter.ui.editor.ExternalFormatterIndentTaskFactory.formatWithNetBeansIndenter(ExternalFormatterIndentTaskFactory.java:151)
	at de.funfried.netbeans.plugins.external.formatter.ui.editor.ExternalFormatterIndentTaskFactory$2.reindent(ExternalFormatterIndentTaskFactory.java:96)
	at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.runTask(TaskHandler.java:548)
	at org.netbeans.modules.editor.indent.TaskHandler.runTasks(TaskHandler.java:309)
	at org.netbeans.modules.editor.indent.IndentImpl.reformat(IndentImpl.java:349)
	at org.netbeans.modules.editor.indent.api.Reformat.reformat(Reformat.java:129)
	at org.netbeans.editor.ActionFactory$FormatAction$1$1.run(ActionFactory.java:1862)
	at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:335)
	at org.netbeans.editor.ActionFactory$FormatAction$1.run(ActionFactory.java:1841)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$1.run(RunOffEDTImpl.java:146)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

Maybe #5650 is somehow related.

**Comment by skomisa1** [comment]
I get the same error message and a very similar stack trace in a different scenario: when creating an "_empty Web Application_" using **File > New Project... > Java with Ant > Java Web > Java Application**. The error message "_Cannot invoke "org.netbeans.modules.web.indent.api.support.IndenterFormattingContext.setLastIndenter()" because "last" is null_" is shown in the **New Project** window after clicking the **Finish** button. My configuration details from **Help > About** are: 

Product Version: Apache NetBeans IDE 17
Java: 20-ea; OpenJDK 64-Bit Server VM 20-ea+35-2342
Runtime: OpenJDK Runtime Environment 20-ea+35-2342
System: Windows 10 version 10.0 running on amd64; UTF-8; en_US (nb)

**Comment by skomisa1** [comment]
I still get the same problem when running NetBeans 17 with JDK 17.0.2 instead of JDK 20.

**Comment by funfried** [comment]
This seems to be a problem within my plugin "External Code Formatters for NetBeans", I just fixed it in the latest SNAPSHOT version and the fix should be published soon within the next release. It seems the ticket #5650 duplicates this issue.

Please see https://github.com/funfried/externalcodeformatter_for_netbeans/issues/245

This ticket can be closed.

**Comment by Quique02232217** [comment]
> Recibo el mismo mensaje de error y un seguimiento de pila muy similar en un escenario diferente: al crear una " _aplicación web vacía_ " usando **File > New Project... > Java with Ant > Java Web > Java Application** . El mensaje de error " _No se puede invocar "org.netbeans.modules.web.indent.api.support.IndenterFormattingContext.setLastIndenter()" porque "last" es nulo_ " se muestra en la ventana **Nuevo proyecto** después de hacer clic en el botón **Finalizar . **Mis detalles de configuración de **Ayuda > Acerca** de son:
> 
> Versión del producto: Apache NetBeans IDE 17 Java: 20-ea; Servidor OpenJDK de 64 bits VM 20-ea+35-2342 Tiempo de ejecución: OpenJDK Runtime Environment 20-ea+35-2342 Sistema: Windows 10 versión 10.0 ejecutándose en amd64; UTF-8; es_US (n.b.)
