### ISSUE TITLE
Can't continue install netbeans

### ISSUE THREAD

**Issue by kenjisoul** [apache/netbeans#5717]
### Apache NetBeans version

Apache NetBeans 17

### What happened

Can't continue to install netbeans just on License Agreement then click Next, but not load next page to continue install.

And this is some install log

> [2023-03-25 22:15:12.947]: NameResolver - to parse <html>
[2023-03-25 22:15:12.947]: NameResolver - to parse The installer will install the NetBeans IDE with the following packs and runtimes.<br>Click Customize to select the packs and runtimes to install.<br><br>
[2023-03-25 22:15:12.948]: NameResolver - to parse text/html
[2023-03-25 22:15:12.951]: NameResolver - to parse <html>
[2023-03-25 22:15:12.951]: NameResolver - to parse {0}<br>
[2023-03-25 22:15:12.952]: NameResolver - to parse {0}<br>
[2023-03-25 22:15:12.952]: NameResolver - to parse {0}<br>
[2023-03-25 22:15:12.952]: NameResolver - to parse {0}<br>
[2023-03-25 22:15:12.952]: NameResolver - to parse {0}<br>
[2023-03-25 22:15:12.952]: NameResolver - to parse </html>
[2023-03-25 22:15:12.952]: NameResolver - to parse text/html
[2023-03-25 22:15:12.956]: NameResolver - to parse &Customize...
[2023-03-25 22:15:12.961]: NameResolver - to parse Installation Size: {0}
[2023-03-25 22:15:12.963]: NameResolver - to parse Insufficient disk space for extracting the installation data. Additional {1} is required in {0}.
[2023-03-25 22:15:12.964]: NameResolver - to parse $N{install}/NetBeans-17
[2023-03-25 22:15:12.964]:       --- parsed to C:\Program Files/NetBeans-17
[2023-03-25 22:15:12.965]: NameResolver - to parse 1.8.0.0.0
[2023-03-25 22:15:12.965]: NameResolver - to parse 500.0.0
[2023-03-25 22:15:12.966]: NameResolver - to parse .*
[2023-03-25 22:15:12.967]: NameResolver - to parse false
[2023-03-25 22:15:12.968]: NameResolver - to parse false
[2023-03-25 22:15:12.969]: NameResolver - to parse false
[2023-03-25 22:15:12.970]: NameResolver - to parse false
[2023-03-25 22:15:12.970]: ... loading registry from resource:data/registry.xml
[2023-03-25 22:15:12.990]: entering -- org.netbeans.installer.product.Registry.loadProductRegistry():981
[2023-03-25 22:15:12.990]: validating previous installations
[2023-03-25 22:15:12.990]: ... validating installations finished
[2023-03-25 22:15:12.990]: exiting -- org.netbeans.installer.product.Registry.loadProductRegistry():981
[2023-03-25 22:15:12.990]: NameResolver - to parse false
[2023-03-25 22:15:12.991]: ... use Java from the first item in the overall list: C:\Program Files\Java\jdk-19
[2023-03-25 22:15:12.991]: ... use Java that is already selected for the product: C:\Program Files\Java\jdk-19
[2023-03-25 22:15:12.992]: NameResolver - to parse Insufficient disk space for extracting the installation data. Additional {1} is required in {0}.
[2023-03-25 22:15:13.001]: NameResolver - to parse <dummy description>
[2023-03-25 22:15:14.994]: NameResolver - to parse Insufficient disk space for extracting the installation data. Additional {1} is required in {0}.
[2023-03-25 22:15:15.616]: NameResolver - to parse Insufficient disk space for extracting the installation data. Additional {1} is required in {0}.
[2023-03-25 22:15:15.632]: NameResolver - to parse &Help!
[2023-03-25 22:15:15.635]: NameResolver - to parse < &Back
[2023-03-25 22:15:15.635]: NameResolver - to parse &Next >
[2023-03-25 22:15:15.635]: NameResolver - to parse Cancel
[2023-03-25 22:15:15.636]: NameResolver - to parse I &accept the terms in the license agreement
[2023-03-25 22:15:15.636]: NameResolver - to parse org/netbeans/installer/product/components/netbeans-license.txt
[2023-03-25 22:15:15.636]: NameResolver - to parse $R{org/netbeans/installer/product/components/netbeans-license.txt;UTF-8}
[2023-03-25 22:15:15.641]: NameResolver - to parse {0}
[2023-03-25 22:15:15.673]: NameResolver - to parse License Agreement
[2023-03-25 22:15:15.673]: NameResolver - to parse License Agreement
[2023-03-25 22:15:15.674]: NameResolver - to parse License Agreement
[2023-03-25 22:15:15.674]: NameResolver - to parse License Agreement
[2023-03-25 22:15:15.675]: NameResolver - to parse Please read the following license agreement carefully.
[2023-03-25 22:15:15.705]: NameResolver - to parse License Agreement
[2023-03-25 22:15:15.706]: NameResolver - to parse Please read the following license agreement carefully.
[2023-03-25 22:15:38.207]: NameResolver - to parse C:\Program Files\NetBeans-17
[2023-03-25 22:15:38.208]: NameResolver - to parse 1.8.0.0.0
[2023-03-25 22:15:38.208]: NameResolver - to parse 500.0.0
[2023-03-25 22:15:38.208]: NameResolver - to parse .*
[2023-03-25 22:15:38.208]: NameResolver - to parse false
[2023-03-25 22:15:38.210]: NameResolver - to parse false
[2023-03-25 22:15:38.211]: NameResolver - to parse false
[2023-03-25 22:15:38.212]: NameResolver - to parse false
[2023-03-25 22:15:38.212]: ... use Java that is already selected for the product: C:\Program Files\Java\jdk-19

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 11

### JDK

jdk-19

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Do you have enough disk space?  Not sure whether it always logs that message or whether it's a sign of the problem.

If it's not disk space, you could also try the community installers - they're based on a completely different installation framework.

**Comment by ofgrenudo** [comment]
Im also having a similar issue.

```
[2023-06-01 07:58:20.341]:         ... saving legal artifacts if required
[2023-06-01 07:58:20.341]:         ... running installation logic
[2023-06-01 07:58:20.341]:         NameResolver - to parse C:\Program Files\NetBeans-17
[2023-06-01 07:58:20.341]:         java.lang.NullPointerException
[2023-06-01 07:58:20.341]:         	at java.io.File.<init>(Unknown Source)
[2023-06-01 07:58:20.341]:         	at org.netbeans.installer.products.nb.all.ConfigurationLogic.install(ConfigurationLogic.java:76)
[2023-06-01 07:58:20.341]:         	at org.netbeans.installer.product.components.Product.install(Product.java:338)
[2023-06-01 07:58:20.341]:         	at org.netbeans.installer.wizard.components.actions.InstallAction.execute(InstallAction.java:135)
[2023-06-01 07:58:20.341]:         	at org.netbeans.installer.wizard.components.WizardAction$1.run(WizardAction.java:103)
[2023-06-01 07:58:20.341]:         NameResolver - to parse Unknown Error
[2023-06-01 07:58:20.341]:         NameResolver - to parse Could not install {0}, since the installation of {1} failed
[2023-06-01 07:58:20.341]:         NameResolver - to parse Could not install {0}, since the installation of {1} failed
[2023-06-01 07:58:20.341]:         NameResolver - to parse Could not install {0}, since the installation of {1} failed
[2023-06-01 07:58:20.341]:         NameResolver - to parse Could not install {0}, since the installation of {1} failed
[2023-06-01 07:58:20.341]:         NameResolver - to parse Could not install {0}, since the installation of {1} failed
[2023-06-01 07:58:20.341]:         NameResolver - to parse Canceling, rolling back {0}...
[2023-06-01 07:58:20.341]:         Start rollback of Base IDE(nb-all/17.0.0.230214.0)
[2023-06-01 07:58:20.341]:             ... running uninstallation logic
```

When I run the installer gui though, it says that I am missing the JDK (which is true). I will try to get that installed in a few minutes and report back if there was any success after.


[apachenetbeans-v17-06012023.log](https://github.com/apache/netbeans/files/11624916/apachenetbeans-v17-06012023.log)

**Comment by ofgrenudo** [comment]
After installing the JDK-20 from https://www.oracle.com/java/technologies/downloads/#jdk20-windows and running the silent install, it seemed to work without issues.

**Comment by neilcsmith-net** [comment]
@ofgrenudo yes, a system installed JDK is required, unless you use the [community installers](https://www.codelerity.com/netbeans/) which include a private JDK runtime for the IDE.

**Comment by k-str50** [comment]
Hello, I also have tis problem, but it doesn't work even after installind JDK20.
I think there is some garbage on windows. I cannot find any solution. That's very annoying.
Is there any help?
