### ISSUE TITLE
Support for WildFly 28

### ISSUE THREAD

**Issue by jheider** [apache/netbeans#5947]
### Description

Deploying to WildFly 28 is currently not working. It stops with port already in use, so it seems NetBeans can't determine running state of WildFly in deployment phase and tries to start the server again. I have tried with IntelliJ IDEA which also fails but gives at least an exception in log.
Regarding to this, i found these changes, which may be related for this:
https://github.com/wildfly/wildfly-core/commit/76f331ad5be63798cccf81a630b05eeae95cd646

### Use case/motivation

Use latest WildFly version which supports Jakarta EE

### Are you willing to submit a pull request?

No

**Comment by asbachb** [comment]
From NetBeans 18-rc3 when starting WildFly 28.
```
java.lang.NoSuchMethodException: org.jboss.as.controller.client.ModelControllerClient$Factory.create(java.lang.String,int,javax.security.auth.callback.CallbackHandler,javax.net.ssl.SSLContext,int,java.util.Map)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyManagementAPI.createClient(WildflyManagementAPI.java:57)
[catch] at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.getClient(WildflyClient.java:243)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.executeAsync(WildflyClient.java:342)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.isServerRunning(WildflyClient.java:289)
	at org.netbeans.modules.javaee.wildfly.ide.WildflyStartServer$1.run(WildflyStartServer.java:215)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)

```

**Comment by asbachb** [comment]
I just gave most recent master a try. The Exception is gone but nor WildFly is detected is running after starting up, neither it's possible to deploy a simple war project.

**Comment by asbachb** [comment]
Occurs when checking if server is running:
```
WARNING [org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient]
java.lang.NoSuchMethodException: org.jboss.as.controller.client.ModelControllerClient$Factory.create(java.lang.String,int,javax.security.auth.callback.CallbackHandler,javax.net.ssl.SSLContext,int,java.util.Map)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyManagementAPI.createClient(WildflyManagementAPI.java:57)
[catch] at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.getClient(WildflyClient.java:243)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.executeAsync(WildflyClient.java:342)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.isServerRunning(WildflyClient.java:289)
	at org.netbeans.modules.javaee.wildfly.ide.WildflyStartServer$1.run(WildflyStartServer.java:215)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

**Comment by asbachb** [comment]
I'm not 100% sure if I'm missing something, but it seems that we cannot connect to `WildFly` admin interface:

```java
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.executeAsync(WildflyClient.java:347)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.isServerRunning(WildflyClient.java:289)
	at org.netbeans.modules.javaee.wildfly.ide.WildflyStartServer$1.run(WildflyStartServer.java:215)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
Caused by: java.lang.RuntimeException: java.net.ConnectException: WFLYPRT0053: Could not connect to remote+http://localhost:9990. The connection failed
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeAsync(AbstractModelControllerClient.java:104)
	... 11 more
Caused by: java.net.ConnectException: WFLYPRT0053: Could not connect to remote+http://localhost:9990. The connection failed
	at org.jboss.as.protocol.ProtocolConnectionUtils.checkFuture(ProtocolConnectionUtils.java:142)
	at org.jboss.as.protocol.ProtocolConnectionUtils.connectSync(ProtocolConnectionUtils.java:122)
	at org.jboss.as.protocol.ProtocolConnectionManager$EstablishingConnection.connect(ProtocolConnectionManager.java:259)
	at org.jboss.as.protocol.ProtocolConnectionManager.connect(ProtocolConnectionManager.java:70)
	at org.jboss.as.protocol.mgmt.ManagementClientChannelStrategy$Establishing.getChannel(ManagementClientChannelStrategy.java:167)
	at org.jboss.as.controller.client.impl.RemotingModelControllerClient.getOrCreateChannel(RemotingModelControllerClient.java:129)
	at org.jboss.as.controller.client.impl.RemotingModelControllerClient$2.getChannel(RemotingModelControllerClient.java:82)
	at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:135)
	at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:110)
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeRequest(AbstractModelControllerClient.java:263)
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:168)
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeAsync(AbstractModelControllerClient.java:101)
	... 11 more
Caused by: javax.security.sasl.SaslException: Authentication failed: all available authentication mechanisms failed:
   DIGEST-MD5: javax.security.sasl.SaslException: DIGEST-MD5: Server rejected authentication
	at org.jboss.remoting3.remote.ClientConnectionOpenListener.allMechanismsFailed(ClientConnectionOpenListener.java:109)
	at org.jboss.remoting3.remote.ClientConnectionOpenListener$Capabilities.handleEvent(ClientConnectionOpenListener.java:445)
	at org.jboss.remoting3.remote.ClientConnectionOpenListener$Capabilities.handleEvent(ClientConnectionOpenListener.java:244)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
	at ...asynchronous invocation...(Unknown Source)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:600)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:561)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:549)
	at org.jboss.as.protocol.ProtocolConnectionUtils.connect(ProtocolConnectionUtils.java:224)
	at org.jboss.as.protocol.ProtocolConnectionUtils.connectSync(ProtocolConnectionUtils.java:118)
	... 21 more
	Suppressed: javax.security.sasl.SaslException: DIGEST-MD5: Server rejected authentication
		at org.jboss.remoting3.remote.ClientConnectionOpenListener$Authentication.handleEvent(ClientConnectionOpenListener.java:760)
		at org.jboss.remoting3.remote.ClientConnectionOpenListener$Authentication.handleEvent(ClientConnectionOpenListener.java:602)
		at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
		at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
		at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
		at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
```
