### ISSUE TITLE
Unable to add Tomcat Server to NetBeans 12.4

### ISSUE THREAD

**Issue by RitaShp** [apache/netbeans#5988]
### Apache NetBeans version

Apache NetBeans 17

### What happened

I had tomcat server added to the Netbeans, but it stopped working. I deleted it and tried to add again, but got folloiwing error:
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "input" is null
	at org.netbeans.modules.payara.tooling.data.PayaraPlatformVersion.getVersions(PayaraPlatformVersion.java:103)
	at org.netbeans.modules.payara.common.PayaraPlatformDetails.getInstantiatingIterator(PayaraPlatformDetails.java:58)
	at org.netbeans.modules.payara.common.wizards.PayaraWizardProvider.getInstantiatingIterator(PayaraWizardProvider.java:79)
	at org.netbeans.modules.server.ui.wizard.ServerWizardVisual$WizardListModel.resultChanged(ServerWizardVisual.java:376)
	at org.netbeans.modules.server.ui.wizard.ServerWizardVisual$WizardListModel.<init>(ServerWizardVisual.java:347)
	at org.netbeans.modules.server.ui.wizard.ServerWizardVisual.initComponents(ServerWizardVisual.java:261)
	at org.netbeans.modules.server.ui.wizard.ServerWizardVisual.<init>(ServerWizardVisual.java:73)
	at org.netbeans.modules.server.ui.wizard.ServerWizardPanel.getComponent(ServerWizardPanel.java:50)
	at org.netbeans.modules.server.ui.wizard.ServerWizardPanel.getVisual(ServerWizardPanel.java:95)
	at org.netbeans.modules.server.ui.wizard.ServerWizardPanel.readSettings(ServerWizardPanel.java:61)
	at org.openide.WizardDescriptor.updateStateOpen(WizardDescriptor.java:843)
	at org.openide.WizardDescriptor.updateState(WizardDescriptor.java:797)
	at org.netbeans.modules.server.ui.wizard.AddServerInstanceWizard.updateState(AddServerInstanceWizard.java:213)
	at org.openide.WizardDescriptor._updateState(WizardDescriptor.java:775)
	at org.openide.WizardDescriptor.initialize(WizardDescriptor.java:450)
	at org.netbeans.modules.server.ui.wizard.AddServerInstanceWizard.<init>(AddServerInstanceWizard.java:95)
	at org.netbeans.modules.server.ui.wizard.AddServerInstanceWizard.showAddServerInstanceWizard(AddServerInstanceWizard.java:179)
	at org.netbeans.modules.server.ui.wizard.AddServerInstanceWizard.showAddServerInstanceWizard(AddServerInstanceWizard.java:105)
	at org.netbeans.modules.server.ui.node.AddServerInstanceAction.actionPerformed(AddServerInstanceAction.java:34)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:174)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:177)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### How to reproduce

Click on Servers, click on Add Server 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows Server 2012 R2 version 6.3 running on amd64; Cp1252; en_US (nb)

### JDK

16.0.2; Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

**Comment by RitaShp** [comment]
12.4, is there anyway to fix it without upgrade?

**Comment by neilcsmith-net** [comment]
We only support the latest release.
