### ISSUE TITLE
changing project group shows an exception in the log

### ISSUE THREAD

**Issue by wumpz** [apache/netbeans#6011]
### Apache NetBeans version

Apache NetBeans 18

### What happened

I changed the project group from one to another and this exception occurred:

```
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because "pwnr" is null
	at org.netbeans.modules.project.ui.ProjectUtilities$1.doClose(ProjectUtilities.java:155)
	at org.netbeans.modules.project.ui.ProjectUtilities$1.close(ProjectUtilities.java:116)
	at org.netbeans.modules.project.ui.ProjectUtilities.closeAllDocuments(ProjectUtilities.java:480)
	at org.netbeans.modules.project.ui.OpenProjectList.close(OpenProjectList.java:923)
	at org.netbeans.modules.project.ui.groups.Group.open(Group.java:586)
	at org.netbeans.modules.project.ui.groups.Group.setActiveGroup(Group.java:180)
	at org.netbeans.modules.project.ui.groups.ManageGroupsPanel$2$1.run(ManageGroupsPanel.java:80)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

### How to reproduce

I don't know. After a restart of Netbeans I am able to switch project groups without this exception.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Thanks for the report.  Have seen this too when testing builds.  Should be fine after restart.

**Comment by mbien** [comment]
might have found the cause for this by accident. will link the PR with this issue once done.
