### ISSUE TITLE
[VSCode extension] Allow setting 'netbeans.jdkhome' on a per-workspace basis.

### ISSUE THREAD

**Issue by JornVernee** [apache/netbeans#6111]
### Description

Allow setting `netbeans.jdkhome` on a per-workspace basis in the VSCode extension.

### Use case/motivation

I use different jdks for different work spaces. However, currently it is only possible to set the used jdk globally, which means I have to change the setting every time I switch to working on a project which uses a different jdk.

When I try to set it in the settings of a workspace I get the message: "This setting can only be applied in user settings..." (see image)

![image](https://github.com/apache/netbeans/assets/5962029/1497870f-728f-49e2-b022-01313f32bdad)

### Are you willing to submit a pull request?

No

**Comment by JornVernee** [comment]
Seems like this should do it:

```
diff --git a/java/java.lsp.server/vscode/package.json b/java/java.lsp.server/vscode/package.json
index d7fef35353..d4c9fbc2d3 100644
--- a/java/java.lsp.server/vscode/package.json
+++ b/java/java.lsp.server/vscode/package.json
@@ -101,7 +101,7 @@
                                        ],
                                        "default": null,
                                        "description": "Specifies JDK for the Apache NetBeans Language Server",
-                                       "scope": "machine"
+                                       "scope": "machine-overridable"
                                },
                                "netbeans.verbose": {
                                        "type": "boolean",
```

I'm not sure if the current limitation is intentional though.

I tried to run the build locally but it fails to find `npm` for some reason, even though that's on the path.

<details>
<summary>Stack trace</summary>

```
H:\Projects-new\netbeans\java\java.lsp.server\build.xml:80: Execute failed: java.io.IOException: Cannot run program "npm" (in directory "H:\Projects-new\netbeans\java\java.lsp.server\vscode"): CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1140)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1074)
        at java.base/java.lang.Runtime.exec(Runtime.java:647)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1111)
        ... 23 more
```
</details>

I think it needs to call `npm.bat` explicitly instead (I'm on Windows).
