### ISSUE TITLE
Unable to copy/cut/past the content

### ISSUE THREAD

**Issue by govindcooperrosedigital** [apache/netbeans#6128]
### Apache NetBeans version

Apache NetBeans 18

### What happened

[messages.log](https://github.com/apache/netbeans/files/11879385/messages.log)

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

WIndows 11

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
only in HTML files or everywhere? There were several html lexer exceptions in your log.
```
java.lang.IndexOutOfBoundsException: index=5 >= size()=5
	at org.netbeans.lib.lexer.JoinTokenList.tokenList(JoinTokenList.java:170)
	at org.netbeans.lib.lexer.JoinLexerInputOperation.tokenList(JoinLexerInputOperation.java:190)
	at org.netbeans.lib.lexer.JoinLexerInputOperation.fetchActiveTokenList(JoinLexerInputOperation.java:183)
	at org.netbeans.lib.lexer.JoinLexerInputOperation.createJoinToken(JoinLexerInputOperation.java:247)
	at org.netbeans.lib.lexer.JoinLexerInputOperation.createDefaultTokenInstance(JoinLexerInputOperation.java:212)
	at org.netbeans.lib.lexer.LexerInputOperation.createToken(LexerInputOperation.java:294)
	at org.netbeans.spi.lexer.TokenFactory.createToken(TokenFactory.java:81)
	at org.netbeans.spi.lexer.TokenFactory.createToken(TokenFactory.java:65)
	at org.netbeans.lib.html.lexer.HtmlLexer.token(HtmlLexer.java:1544)
	at org.netbeans.lib.html.lexer.HtmlLexer.token(HtmlLexer.java:1482)
	at org.netbeans.lib.html.lexer.HtmlLexer.resolveValueToken(HtmlLexer.java:1465)
	at org.netbeans.lib.html.lexer.HtmlLexer.nextToken(HtmlLexer.java:1393)
	at org.netbeans.lib.lexer.LexerInputOperation.nextToken(LexerInputOperation.java:191)
	at org.netbeans.lib.lexer.JoinTokenList.init(JoinTokenList.java:666)
	at org.netbeans.lib.lexer.JoinTokenList.create(JoinTokenList.java:74)
	at org.netbeans.lib.lexer.TokenListList.checkCreateJoinTokenList(TokenListList.java:147)
	at org.netbeans.lib.lexer.TokenListList.<init>(TokenListList.java:106)
	at org.netbeans.lib.lexer.TokenHierarchyOperation.tokenListList(TokenHierarchyOperation.java:478)
	at org.netbeans.lib.lexer.TokenSequenceList.<init>(TokenSequenceList.java:84)
	at org.netbeans.lib.lexer.TokenHierarchyOperation.tokenSequenceList(TokenHierarchyOperation.java:430)
	at org.netbeans.api.lexer.TokenHierarchy.tokenSequenceList(TokenHierarchy.java:204)
	at org.netbeans.spi.debugger.ui.EditorContextDispatcher.getMIMETypesOnLine(EditorContextDispatcher.java:327)
	at org.netbeans.spi.debugger.ui.EditorContextDispatcher.getMIMETypesOnCurrentLine(EditorContextDispatcher.java:286)
Caused: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[catch] at org.netbeans.spi.debugger.ActionsProvider$ContextAware.isCurrentMIMETypeIn(ActionsProvider.java:382)
	at org.netbeans.spi.debugger.ActionsProvider$ContextAware.isEnabled(ActionsProvider.java:253)
	at org.netbeans.api.debugger.ActionsManager.isEnabled(ActionsManager.java:327)
	at org.netbeans.api.debugger.ActionsManager.fireActionStateChanged(ActionsManager.java:471)
	at org.netbeans.api.debugger.ActionsManager.lambda$new$0(ActionsManager.java:118)
	at org.netbeans.spi.debugger.ActionsProviderSupport.fireActionStateChanged(ActionsProviderSupport.java:86)
	at org.netbeans.spi.debugger.ActionsProviderSupport.setEnabled(ActionsProviderSupport.java:73)
	at org.netbeans.modules.php.dbgp.breakpoints.BreakpointActionProvider.propertyChange(BreakpointActionProvider.java:104)
	at org.openide.util.WeakListenerImpl$PropertyChange.propertyChange(WeakListenerImpl.java:189)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at org.netbeans.spi.debugger.ui.EditorContextDispatcher.firePropertyChange(EditorContextDispatcher.java:593)
	at org.netbeans.spi.debugger.ui.EditorContextDispatcher.access$2000(EditorContextDispatcher.java:101)
	at org.netbeans.spi.debugger.ui.EditorContextDispatcher$EventFirer.run(EditorContextDispatcher.java:990)
	at org.netbeans.spi.debugger.ui.EditorContextDispatcher$EditorRegistryListener$1.run(EditorContextDispatcher.java:787)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

**Comment by govindcooperrosedigital** [comment]
Only HTML.
________________________________
