### ISSUE TITLE
NumberFormatException with auto-complete when editing pom.xml

### ISSUE THREAD

**Issue by bernard01** [apache/netbeans#6180]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Edited pom.xml of an old project with the aim to find newest version of a dependency.

Changed from originally 3.3 to 3.6.1, then undo to 3.3, then added this comment, then removed version string and invoked auto-complete.

See code snippet:

```xml
    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <!-- Changed from originally 3.3 to 3.6.1, then undo to 3.3, then added this comment, then removed version string and invoked auto-complete -->
            <version>3.6.1</version>
        </dependency>
    </dependencies>
```

Getting an exception as follows:
```

java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.netbeans.modules.maven.hints.pom.UpdateDependencyHint.noTimestamp(UpdateDependencyHint.java:178)
	at org.netbeans.modules.maven.hints.pom.UpdateDependencyHint.addHintsTo(UpdateDependencyHint.java:128)
	at org.netbeans.modules.maven.hints.pom.UpdateDependencyHint.getErrorsForDocument(UpdateDependencyHint.java:85)
	at org.netbeans.modules.maven.hints.pom.PomModelUtils.findHints(PomModelUtils.java:166)
	at org.netbeans.modules.maven.hints.pom.MavenFileHintsTask.run(MavenFileHintsTask.java:55)
	at org.netbeans.modules.maven.hints.pom.MavenFileHintsTask.run(MavenFileHintsTask.java:45)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)

```

### How to reproduce

See above.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 7

### JDK

Java: 14; Java HotSpot(TM) 64-Bit Server VM 14+36-1461

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I have seen this the first time. But that does not seem to matter much. What seems to matter is that the number of errors appearing in the notifications is getting smaller with every release, and now I pay more attention to what is left. It does not seem to have an impact, but fixing it would mean that more important issues could get focused on better.
[SampleProject.zip](https://github.com/apache/netbeans/files/12024803/SampleProject.zip)
[messages.log](https://github.com/apache/netbeans/files/12024812/messages.log)

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
you probably mean `NumberFormatException` and not `NullPointerException`, right?
The messages.log is mostly empty, looks like it rotated so I couldn't check.

The linked PR should fix it. Thanks for the report.

**Comment by bernard01** [comment]
> you probably mean `NumberFormatException` and not `NullPointerException`, right? The messages.log is mostly empty, looks like it rotated so I couldn't check.
> 
> The linked PR should fix it. Thanks for the report.

You are right. Attached test case should be reproducible. Thanks.

**Comment by mbien** [comment]
> You are right. Attached test case should be reproducible. 

yeah I could reproduce it. I was just wondering if you saw two issues.

once CI is done the job should produce a dev build on the bottom of the summary page: https://github.com/apache/netbeans/actions/runs/5531766701?pr=6184
