### ISSUE TITLE
ArtifactResolutionExceptions when working with certain maven projects

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#6222]
### Apache NetBeans version

Apache NetBeans 19 rc 1

### What happened

Tried to open the parent project of https://github.com/apache/maven-indexer/ and got several exceptions. The exceptions already start before the project is open, as soon it is selected in the project open dialog (NB is loading the model to try to find sub projects).

Once the project is open the exceptions will keep showing up while working with the pom etc.

```
[org.netbeans.modules.project.ui.ProjectChooserAccessory$ModelUpdater] INFO org.eclipse.aether.internal.impl.DefaultArtifactResolver - Artifact org.apache:apache:pom:29 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [apache.snapshots (https://repository.apache.org/snapshots, default, snapshots)]
SEVERE [org.openide.util.Exceptions]
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache:apache:pom:29
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:450)
Caused: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache:apache:pom:29 (present, but unavailable): Could not find artifact org.apache:apache:pom:29
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:242)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:277)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:197)
Caused: org.apache.maven.artifact.resolver.ArtifactNotFoundException: The following artifacts could not be resolved: org.apache:apache:pom:29 (present, but unavailable): Could not find artifact org.apache:apache:pom:29

  org.apache:apache:pom:29

from the specified remote repositories:
  apache.snapshots (https://repository.apache.org/snapshots, releases=false, snapshots=true)

	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:200)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveAlways(DefaultArtifactResolver.java:152)
	at org.netbeans.modules.maven.embedder.MavenEmbedder.resolve(MavenEmbedder.java:380)
[catch] at org.netbeans.modules.maven.embedder.NBRepositoryModelResolver.resolveModel(NBRepositoryModelResolver.java:74)
	at org.netbeans.modules.maven.embedder.NBRepositoryModelResolver.resolveModel(NBRepositoryModelResolver.java:88)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1009)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:801)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:327)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
	at org.netbeans.modules.maven.embedder.impl.NBModelBuilder.build(NBModelBuilder.java:53)
	at org.netbeans.modules.maven.embedder.MavenEmbedder.executeModelBuilder(MavenEmbedder.java:445)
	at org.netbeans.modules.maven.NbMavenProjectImpl.getRawModel(NbMavenProjectImpl.java:216)
	at org.netbeans.modules.maven.api.NbMavenProject.getRawModel(NbMavenProject.java:392)
	at org.netbeans.modules.maven.MavenProjectPropsImpl.lambda$get$0(MavenProjectPropsImpl.java:93)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.modules.maven.MavenProjectPropsImpl.get(MavenProjectPropsImpl.java:78)
	at org.netbeans.modules.maven.MavenProjectPropsImpl.get(MavenProjectPropsImpl.java:74)
	at org.netbeans.modules.maven.MavenProjectPropsImpl$PackagingProviderImpl.packaging(MavenProjectPropsImpl.java:306)
	at org.netbeans.modules.maven.api.NbMavenProject.getPackagingType(NbMavenProject.java:378)
	at org.netbeans.modules.maven.NbMavenProjectImpl$PackagingTypeDependentLookup.check(NbMavenProjectImpl.java:1050)
	at org.netbeans.modules.maven.NbMavenProjectImpl$PackagingTypeDependentLookup.<init>(NbMavenProjectImpl.java:1008)
	at org.netbeans.modules.maven.NbMavenProjectImpl.<init>(NbMavenProjectImpl.java:274)
	at org.netbeans.modules.maven.NbMavenProjectFactory.loadProject(NbMavenProjectFactory.java:98)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:376)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:69)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:289)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:218)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.openide.util.Mutex.readAccess(Mutex.java:232)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:218)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:142)
	at org.netbeans.modules.project.ui.OpenProjectList.fileToProject(OpenProjectList.java:1257)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.getProject(ProjectChooserAccessory.java:363)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.access$000(ProjectChooserAccessory.java:67)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory$1.run(ProjectChooserAccessory.java:236)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

### How to reproduce

open the above mentioned project

### Did this work correctly in an earlier version?

18

### Operating System

linux

### JDK

20

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Maybe

**Comment by mbien** [comment]
reverting back to maven 3.9.1 didn't change anything (cddb4280f495f612f763ed1acaee3a56f62c8857 f99716e5061825933779cad0c5c296543a14da2d)

lets take a look at https://github.com/apache/netbeans/commit/ad99e85b260eb029462b4c3ae2cef022b1541b61 again
