### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by amryounis** [apache/netbeans#6341]
### Apache NetBeans version

Apache NetBeans 18

### What happened

installed PlantUML Version: 1.12 Source: NetBeans Plugin Portal
within an open Java project, file -> new file -> PlantUML (PlantUML from existing Java sources.) -> (enter required fields) -> click finish

in the notifications window, i receive an exception

### How to reproduce

installed PlantUML Version: 1.12 Source: NetBeans Plugin Portal
within an open Java project, file -> new file -> PlantUML (PlantUML from existing Java sources.) -> (enter required fields) -> click finish

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 11

### JDK

Oracle JDK 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by amryounis** [comment]
java.lang.ClassNotFoundException: org.apache.tools.ant.types.FileSet starting from ModuleCL@2527bdf1[org.netbeans.modules.plantumlnb] with possible defining loaders null and declared parents [org.netbeans.JarClassLoader@56f425d9, ModuleCL@166e2b6a[org.netbeans.modules.queries], ModuleCL@534c480d[org.openide.windows], ModuleCL@3d3e9bd4[org.openide.filesystems.nb], ModuleCL@7ff7595c[org.openide.awt], ModuleCL@1aca20cd[org.netbeans.modules.java.project.ui], ModuleCL@e7c9ce1[org.netbeans.modules.editor.errorstripe.api], ModuleCL@22a3b578[org.netbeans.api.annotations.common], ModuleCL@15ad385e[org.netbeans.modules.editor.completion], ModuleCL@5cb181c0[org.openide.nodes], ...17 more]
Caused: java.lang.NoClassDefFoundError: org/apache/tools/ant/types/FileSet
	at net.sourceforge.plantumldependency.commoncli.utils.fileset.FileSetUtils.createFileSet(FileSetUtils.java:58)
	at net.sourceforge.plantumldependency.commoncli.option.argument.impl.filepattern.IncludeFilePatternOptionArgumentImpl.parseArgument(IncludeFilePatternOptionArgumentImpl.java:85)
	at net.sourceforge.plantumldependency.commoncli.option.argument.impl.filepattern.IncludeFilePatternOptionArgumentImpl.parseArgument(IncludeFilePatternOptionArgumentImpl.java:44)
	at net.sourceforge.plantumldependency.commoncli.option.AbstractOptionWithArgument.getDefaultArgumentIfOptionNotSpecified(AbstractOptionWithArgument.java:168)
	at net.sourceforge.plantumldependency.commoncli.option.AbstractOptionWithArgument.findAndParseArgumentOrGetDefaultArgument(AbstractOptionWithArgument.java:149)
	at net.sourceforge.plantumldependency.cli.main.option.output.PlantUMLDependencyOutputOption.parseCommandLine(PlantUMLDependencyOutputOption.java:279)
	at net.sourceforge.plantumldependency.commoncli.program.impl.JavaProgramImpl.parseCommandLine(JavaProgramImpl.java:801)
	at org.netbeans.modules.plantumlnb.generate.PlantUMLDependencyService.generate(PlantUMLDependencyService.java:94)
	at org.netbeans.modules.plantumlnb.generate.PlantUMLDependencyService.generate(PlantUMLDependencyService.java:85)
	at org.netbeans.modules.plantumlnb.ui.wizard.PlantUMLWizardIterator.instantiate(PlantUMLWizardIterator.java:116)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1050)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:223)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:135)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1605)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
	at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)

**Comment by junichi11** [comment]
@amryounis Please report it to the plugin's issue tracker or the plugin owner. We can't do anything.
