### ISSUE TITLE
Error in RequestProcessor org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerIterator

### ISSUE THREAD

**Issue by thilinajayamini** [apache/netbeans#6394]
### Apache NetBeans version

Apache NetBeans 18

### What happened

jpa controller created with no methods .

### How to reproduce

create jpa controller from entity class . 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerIterator$1
java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.ExecutableElement.getSimpleName()" because "derivedIdGetterElement" is null
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerGenerator$3.run(JpaControllerGenerator.java:248)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerGenerator$3.run(JpaControllerGenerator.java:229)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:675)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:665)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:686)
	at 

### Are you willing to submit a pull request?

No

**Comment by thilinajayamini** [comment]
db driver h2-2.2.222.jar

**Comment by linkStrack** [comment]
I have same problema in netbenas 19, 20 and 21
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 122,291 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 601 ms.
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 12,100 ms.
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerIterator$$Lambda/0x0000019036c7f938
java.lang.IllegalArgumentException: Type jakarta.persistence.EntityManagerFactory cannot be found
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerUtil$TreeMakerUtils.createType(JpaControllerUtil.java:1074)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerUtil$TreeMakerUtils.addVariable(JpaControllerUtil.java:915)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerUtil$TreeMakerUtils.addVariable(JpaControllerUtil.java:923)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerGenerator.lambda$generateJpaController$2(JpaControllerGenerator.java:340)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:675)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:665)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:686)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerGenerator.generateJpaController(JpaControllerGenerator.java:247)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerGenerator.generateJpaController(JpaControllerGenerator.java:143)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerIterator.generateJpaControllers(JpaControllerIterator.java:251)
	at org.netbeans.modules.j2ee.persistence.wizard.jpacontroller.JpaControllerIterator.lambda$instantiate$1(JpaControllerIterator.java:105)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
