### ISSUE TITLE
After installing the editor I got this error

### ISSUE THREAD

**Issue by Bassam1132** [apache/netbeans#6396]
### Apache NetBeans version

Apache NetBeans 18

### What happened

![لقطة شاشة 2023-08-31 110617](https://github.com/apache/netbeans/assets/108855005/8e0d486f-7828-41b6-aa99-aa942fecbc62)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Window 11

### JDK

JDK-19

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by Bassam1132** [comment]
This Error :
((
java.lang.IllegalArgumentException: failed to parse:application/x-java-openide-dataobjectdnd;class=org.openide.loaders.DataObject;mask=١
	at java.datatransfer/java.awt.datatransfer.DataFlavor.<init>(DataFlavor.java:476)
	at org.openide.loaders.LoaderTransfer.createDndFlavor(LoaderTransfer.java:213)
	at org.openide.loaders.LoaderTransfer.transferable(LoaderTransfer.java:92)
	at org.openide.loaders.DataNode.clipboardCopy(DataNode.java:697)
	at org.openide.loaders.DataFolder$FolderNode.createNodeTransferable(DataFolder.java:1422)
	at org.openide.loaders.DataFolder$FolderNode.createPasteTypes(DataFolder.java:1395)
	at org.openide.nodes.AbstractNode.getPasteTypes(AbstractNode.java:518)
	at org.openide.nodes.FilterNode.getPasteTypes(FilterNode.java:666)
	at org.netbeans.modules.openide.explorer.ExplorerActionsImpl.updatePasteTypes(ExplorerActionsImpl.java:373)
	at org.netbeans.modules.openide.explorer.ExplorerActionsImpl.updatePasteAction(ExplorerActionsImpl.java:316)
	at org.netbeans.modules.openide.explorer.ExplorerActionsImpl.updateActions(ExplorerActionsImpl.java:257)
	at org.netbeans.modules.openide.explorer.ExplorerActionsImpl$ActionStateUpdater.run(ExplorerActionsImpl.java:824)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)

))

**Comment by neilcsmith-net** [comment]
Please follow the instructions in the dialog from the screenshot and attach the messages.log to this issue. Thanks!
