### ISSUE TITLE
Run Test Method Action Annotation doesn't show anymore

### ISSUE THREAD

**Issue by albilu** [apache/netbeans#6452]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Run Test Method Action Annotation doesn't show anymore:
See pictures. 
On Left: Apache 17 under JDK 17 
On Right Apache 19 Under JDK 17
![image](https://github.com/apache/netbeans/assets/35330562/cdbd664a-043a-46f4-b8e5-671cc94aa2cc)

### How to reproduce

1. Create a simple maven project
2. create a Test for the main class (Tools -> Create/Update Tests)

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Linux/Windows

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Working fine here. What is the error in your test file?

**Comment by albilu** [comment]
> Working fine here. What is the error in your test file?

Even without the error in the file i am not getting the Annotation.
Here is the log:
```
java.lang.NullPointerException: null AnnotationType for:org-netbeans-modules-gsf-testrunner-runnable-test-annotation allTypes size: 174
	at org.netbeans.editor.AnnotationTypes.getType(AnnotationTypes.java:300)
	at org.netbeans.editor.AnnotationDesc.updateAnnotationType(AnnotationDesc.java:167)
	at org.netbeans.modules.editor.NbEditorDocument$AnnotationDescDelegate.<init>(NbEditorDocument.java:300)
	at org.netbeans.modules.editor.NbEditorDocument.addAnnotation(NbEditorDocument.java:215)
	at org.openide.text.NbDocument.addAnnotation(NbDocument.java:493)
	at org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController.setTestMethodsImpl(TestMethodController.java:75)
	at org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController.lambda$setTestMethods$0(TestMethodController.java:44)
	at org.netbeans.editor.GuardedDocument.runAtomic(GuardedDocument.java:296)
	at org.openide.text.NbDocument.runAtomic(NbDocument.java:411)
	at org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController.setTestMethods(TestMethodController.java:43)
	at org.netbeans.modules.java.testrunner.ui.ComputeTestMethodsImpl$TaskImpl.lambda$run$0(ComputeTestMethodsImpl.java:106)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```
[netbeans.log](https://github.com/apache/netbeans/files/12613452/netbeans.log)

**Comment by neilcsmith-net** [comment]
Still cannot reproduce.  Can you try running with a clean userdir?  eg. `netbeans --userdir /tmp/testannotations`. And without importing any settings or plugins.  Are there any other exceptions earlier than the shared log that might be relevant?  ie. around gsf-testrunner or annotation loading.  It could be possible that something else is failing to load during annotation types registration that's leaving the types registry corrupted.

**Comment by albilu** [comment]
@neilcsmith-net issue was indeed caused by an external plugin. Thanks for your feedbacks
