### ISSUE TITLE
A java.lang.NullPointerException has occurred.

### ISSUE THREAD

**Issue by h312ry** [apache/netbeans#6532]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Get Error A java.lang.NullPointerException has occurred, on instal framework CI ver 4 (netbeans 19)

detail:
java.lang.NullPointerException
	at org.netbeans.core.startup.preferences.NbPreferences.put(NbPreferences.java:154)
	at org.netbeans.core.startup.preferences.NbPreferences.put(NbPreferences.java:149)
	at org.nbphpcouncil.modules.php.ci.ui.options.CIOptions.putEntries(CIOptions.java:141)
	at org.nbphpcouncil.modules.php.ci.ui.options.CategoryArchiveFiles.store(CategoryArchiveFiles.java:377)
	at org.nbphpcouncil.modules.php.ci.ui.options.CIOptionsPanel.store(CIOptionsPanel.java:161)
	at org.nbphpcouncil.modules.php.ci.ui.options.CIOptionsPanelController.applyChanges(CIOptionsPanelController.java:78)
	at org.netbeans.modules.php.api.ui.options.FrameworksPanel.applyChanges(FrameworksPanel.java:265)
	at org.netbeans.modules.php.api.ui.options.FrameworksOptionsPanelController.applyChanges(FrameworksOptionsPanelController.java:73)
	at org.netbeans.modules.options.TabbedController.applyChanges(TabbedController.java:111)
	at org.netbeans.modules.options.CategoryModel$Category.applyChanges(CategoryModel.java:379)
	at org.netbeans.modules.options.CategoryModel$Category.access$1100(CategoryModel.java:302)
	at org.netbeans.modules.options.CategoryModel.save(CategoryModel.java:198)
	at org.netbeans.modules.options.OptionsPanel.save(OptionsPanel.java:288)
	at org.netbeans.modules.options.OptionsDisplayerImpl$OptionsPanelListener$3.run(OptionsDisplayerImpl.java:515)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:252)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
INFO [org.netbeans.modules.php.project.ui.options.PhpAnnotationsPanelController]: Resolving of deprecated PHP elements: false

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 

### JDK

JDK 12

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

Yes

**Comment by junichi11** [comment]
The cause is plugin. So, we can't do anything.
