### ISSUE TITLE
"Run File" no longer working in NetBeans 19 and later

### ISSUE THREAD

**Issue by pressing-buttons** [apache/netbeans#6586]
### Apache NetBeans version

Apache NetBeans 19

### What happened

When using Gradle together with a Spring Boot application "Run File" stopped working in NetBeans 19. 

For the same project, running a class with a main method (which is not the main class of the project") fails with an error in Gradle using NetBeans 19, but works in NetBeans 18

### How to reproduce

Open the attached project. Open the class "RunMe", then use "Run File" to run this class. 
Works in NetBeans 18, fails in NetBeans 19 (and 20-rc1) with the following error: 

    org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'RunFileDemo'.
      at org.gradle.execution.TaskNameResolver.getExistingTask(TaskNameResolver.java:116)
      ...
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
    Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':runSingle'.
      at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:715)
      ...
      at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
      at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
    Caused by: org.gradle.tooling.BuildException: Could not find "run" task to execute. Please upgrade your configuration to use standard run-style tasks instead of deprecated runSingle
      at org.netbeans.modules.gradle.tooling.NetBeansRunSinglePlugin.lambda$addTask$2(NetBeansRunSinglePlugin.java:107)
      ... 157 more

[RunFileDemo.zip](https://github.com/apache/netbeans/files/13031210/RunFileDemo.zip)

Tried with Gradle 7.6 and 8.2

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows 10

### JDK

JDK 17, Adoptium

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
The fix merged to delivery from #6618 makes it possible to run the provided sample. @pressing-buttons please check the latest nightly: https://nightlies.apache.org/netbeans/candidate/netbeans/.
