### ISSUE TITLE
Viewing git history can throw an exception with new JGit

### ISSUE THREAD

**Issue by neilcsmith-net** [apache/netbeans#6592]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Using show history on a larger git repository (eg. NetBeans' sources) throws an exception in JGit and just shows `No Results Yet - Search in Progress`.

```
WARNING [org.netbeans.libs.git.jgit.commands.LogCommand]: Out of available flags for branches: 236
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.git.ui.history.SearchExecutor
java.lang.IllegalArgumentException: 24 flags already created.
	at org.eclipse.jgit.revwalk.RevWalk.allocFlag(RevWalk.java:1360)
	at org.eclipse.jgit.revwalk.RevWalk.newFlag(RevWalk.java:1354)
	at org.netbeans.libs.git.jgit.commands.LogCommand.run(LogCommand.java:124)
	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:56)
	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:53)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at org.netbeans.libs.git.jgit.commands.GitCommand.execute(GitCommand.java:53)
	at org.netbeans.libs.git.GitClient.log(GitClient.java:981)
	at org.netbeans.modules.git.client.GitClient$39.call(GitClient.java:613)
	at org.netbeans.modules.git.client.GitClient$39.call(GitClient.java:609)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1$1.call(GitClient.java:933)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1.call(GitClient.java:956)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethodIntern(GitClient.java:968)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:897)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:875)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.access$400(GitClient.java:869)
	at org.netbeans.modules.git.client.GitClient.log(GitClient.java:609)
	at org.netbeans.modules.git.ui.history.SearchExecutor.search(SearchExecutor.java:186)
	at org.netbeans.modules.git.ui.history.SearchExecutor.perform(SearchExecutor.java:167)
	at org.netbeans.modules.git.client.GitProgressSupport.performIntern(GitProgressSupport.java:92)
	at org.netbeans.modules.git.client.GitProgressSupport.run(GitProgressSupport.java:85)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Ubuntu 22.04

### JDK

JDK 21

**Comment by mbien** [comment]
what happens if `load all revisions` is turned off in git history settings?

**Comment by neilcsmith-net** [comment]
It is off. Seems related to number of branches.

**Comment by mbien** [comment]
if `markBranchFlags` leaves one spare flag, `run` can use the spare and it seems to work.
```diff
diff --git a/ide/libs.git/src/org/netbeans/libs/git/jgit/commands/LogCommand.java b/ide/libs.git/src/org/netbeans/libs/git/jgit/commands/LogCommand.java
index cb9460b..ffef113 100644
--- a/ide/libs.git/src/org/netbeans/libs/git/jgit/commands/LogCommand.java
+++ b/ide/libs.git/src/org/netbeans/libs/git/jgit/commands/LogCommand.java
@@ -210,7 +210,7 @@
                     }
                 } else {
                     usedFlags.add(flagId);
-                    if (i < 25) {
+                    if (i < 24) {
                         i = i + 1;
                         RevFlag flag = walk.newFlag(flagId);
                         List<GitBranch> branches = new ArrayList<>(allBranches.size());

```
crisis averted?
