### ISSUE TITLE
Error notification - Symbol$CompletionFailure: cannot find symbol java.lang

### ISSUE THREAD

**Issue by neilcsmith-net** [apache/netbeans#6599]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Testing 20-rc1 on some other work projects, and consistently seeing error notifications with `Symbol$CompletionFailure` cannot find symbol `package java.lang`. Stack trace seems to always show this in `NPECheck` hint.

<details><summary>Full stack trace ...</summary>

```
com.sun.tools.javac.code.Symbol$CompletionFailure: cannot find symbol
  symbol: package java.lang
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.netbeans.lib.nbjavac.services.NBClassFinder.lambda$getCompleter$1(NBClassFinder.java:104)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:682)
	at com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:1178)
	at com.sun.tools.javac.code.Symbol$ModuleSymbol.getEnclosedElements(Symbol.java:1083)
	at com.sun.tools.javac.code.Symbol$ModuleSymbol.getEnclosedElements(Symbol.java:962)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.visitMethod(NPECheck.java:1158)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.visitMethod(NPECheck.java:546)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:948)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreeScanner.scan(CancellableTreeScanner.java:69)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.scan(NPECheck.java:648)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.scan(NPECheck.java:546)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.CancellableTreeScanner.scan(CancellableTreeScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:855)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreeScanner.scan(CancellableTreeScanner.java:69)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.scan(NPECheck.java:648)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.scan(NPECheck.java:546)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.CancellableTreeScanner.scan(CancellableTreeScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:623)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreeScanner.scan(CancellableTreeScanner.java:69)
	at org.netbeans.modules.java.hints.bugs.NPECheck$VisitorImpl.scan(NPECheck.java:648)
	at org.netbeans.modules.java.hints.bugs.NPECheck.computeExpressionsState(NPECheck.java:503)
	at org.netbeans.modules.java.hints.bugs.NPECheck.methodInvocation(NPECheck.java:308)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[catch] at org.netbeans.modules.java.hints.providers.code.CodeHintProviderImpl$WorkerImpl.createErrors(CodeHintProviderImpl.java:315)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.runHint(HintsInvoker.java:794)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.access$400(HintsInvoker.java:89)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.runAndAdd(HintsInvoker.java:656)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:675)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:609)
	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:503)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1611)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:681)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:609)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1104)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:681)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:609)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:948)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:681)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:609)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:855)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:69)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:681)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:609)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at org.netbeans.api.java.source.support.CancellableTreePathScanner.scan(CancellableTreePathScanner.java:78)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:623)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker$ScannerImpl.scan(HintsInvoker.java:700)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHintsImpl(HintsInvoker.java:244)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:227)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:192)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:165)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:127)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:113)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:63)
	at org.netbeans.modules.java.source.JavaSourceAccessor$CancelableTaskWrapper.run(JavaSourceAccessor.java:273)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```
</details>

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Ubuntu 22.04

### JDK

JDK 21 (Zulu)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by MartinBalin** [comment]
Don't see this in VSNetBeans 20.0.0 build. Running on GraalVM 23.0 JDK17 and same JDK used for project as well. This can be the reason you see with JDK 21.

**Comment by neilcsmith-net** [comment]
cc/ @jlahoda - what are the possible causes of `java.lang` not being found in `NbClassFinder::getCompleter`?  I seem to be getting notifications from the code you added in #2947 a lot running on JDK 21 only, both with NB20 release candidates, and with another project based on NB17.

**Comment by lahodaj** [comment]
So, under normal circumstances, this code was meant to throw a meaningful CompletionFailure, which would produce a meaningful error, when java.lang does not contain anything (as opposed to normal javac behavior which will simply stop the compilation). Normally, CF should be get outside of javac, but there is apparently a hole here for ModuleSymbol.getEnclosedElements. And, apparently, javac thinks there's an empty java.lang package in the given module (which could be potentially caused by multiple things).

I think I'll need to try to:
 - fix ModuleSymbol.getEnclosedElements is javac (at least as long as I can find a way to reproduce)
 - fix NBClassFinder to only throw new CF for java.lang from java.base.
