### ISSUE TITLE
20rc2: maven project properties window does not open

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#6622]
### Apache NetBeans version

Apache NetBeans 20 release candidate 2

### What happened

```
SEVERE [global]
java.lang.NullPointerException: Cannot invoke "org.apache.maven.project.MavenProject.getGroupId()" because "prj" is null
	at org.netbeans.modules.maven.modelcache.MavenProjectCache.isFallbackproject(MavenProjectCache.java:475)
	at org.netbeans.modules.maven.api.NbMavenProject.isErrorPlaceholder(NbMavenProject.java:674)
	at org.netbeans.modules.maven.customizer.BasicInfoPanel.initValues(BasicInfoPanel.java:70)
	at org.netbeans.modules.maven.customizer.BasicInfoPanel.<init>(BasicInfoPanel.java:60)
	at org.netbeans.modules.maven.customizer.BasicPanelProvider.createComponent(BasicPanelProvider.java:50)
	at org.netbeans.spi.project.ui.support.ProjectCustomizer$DelegateCategoryProvider.create(ProjectCustomizer.java:604)
	at org.netbeans.modules.project.uiapi.CustomizerPane.setCategory(CustomizerPane.java:234)
	at org.netbeans.modules.project.uiapi.CustomizerPane.<init>(CustomizerPane.java:111)
	at org.netbeans.spi.project.ui.support.ProjectCustomizer.createCustomizerPane(ProjectCustomizer.java:253)
	at org.netbeans.spi.project.ui.support.ProjectCustomizer.createCustomizerDialog(ProjectCustomizer.java:155)
	at org.netbeans.spi.project.ui.support.ProjectCustomizer.createCustomizerDialog(ProjectCustomizer.java:239)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl$1.run(CustomizerProviderImpl.java:158)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:97)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:72)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:66)
	at org.openide.util.Mutex.readAccess(Mutex.java:242)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:150)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:118)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:113)
	at org.netbeans.modules.project.ui.actions.CustomizeProject$1$1.run(CustomizeProject.java:135)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### How to reproduce

- started NB 20 rc2, 
- opened maven project
- right click on project -> properties

### Did this work correctly in an earlier version?

Apache NetBeans 20rc1

### Operating System

linux

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
likely #6514 since it was the only PR in that area since rc1
