### ISSUE TITLE
CCE in JavaCompletionTask

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#6663]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

saw this Exception today, not sure how to reproduce unfortunately:

```
java.lang.ClassCastException: class com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to class javax.lang.model.element.ExecutableElement (com.sun.tools.javac.code.Symbol$ClassSymbol and javax.lang.model.element.ExecutableElement are in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @712ffa7c)
	at org.netbeans.modules.java.completion.JavaCompletionTask.getSmartTypesImpl(JavaCompletionTask.java:5815)
	at org.netbeans.modules.java.completion.JavaCompletionTask.getSmartTypes(JavaCompletionTask.java:5547)
	at org.netbeans.modules.java.completion.JavaCompletionTask.addLocalMembersAndVars(JavaCompletionTask.java:3500)
	at org.netbeans.modules.java.completion.JavaCompletionTask.insideMethodInvocation(JavaCompletionTask.java:2072)
	at org.netbeans.modules.java.completion.JavaCompletionTask.resolve(JavaCompletionTask.java:372)
	at org.netbeans.modules.java.completion.BaseTask.run(BaseTask.java:96)
	at org.netbeans.modules.java.completion.JavaCompletionTask.run(JavaCompletionTask.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:186)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
[catch] at org.netbeans.modules.editor.java.JavaCompletionProvider$JavaCompletionQuery.query(JavaCompletionProvider.java:193)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```
since it is in NB code this can be probably fixed

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

linux

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
cc/ @jlahoda @dbalek any thoughts on this?

**Comment by mbien** [comment]
closing since I can't remember this happening again
