### ISSUE TITLE
Git cherry-pick failure

### ISSUE THREAD

**Issue by vitsuchanek** [apache/netbeans#6668]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Unable to cherry-pick a revision committed into master branch.

![step1_git_select_revision_dialog](https://github.com/apache/netbeans/assets/18000258/189b6a86-1e56-46cb-883a-5171222443a4)
![step2_git_apply_cherry_pick](https://github.com/apache/netbeans/assets/18000258/451ea0da-3eca-41dd-b647-11ba2f7eb582)

Stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jgit.merge.ResolveMerger.addToCheckout(ResolveMerger.java:994)
	at org.eclipse.jgit.merge.ResolveMerger.processEntry(ResolveMerger.java:1178)
	at org.netbeans.libs.git.jgit.commands.CherryPickCommand$FailuresDetectRecurciveStrategy$1.mergeTreeWalk(CherryPickCommand.java:433)
	at org.eclipse.jgit.merge.ResolveMerger.mergeTrees(ResolveMerger.java:1866)
	at org.eclipse.jgit.merge.ResolveMerger.mergeImpl(ResolveMerger.java:915)
	at org.eclipse.jgit.merge.Merger.merge(Merger.java:233)
	at org.eclipse.jgit.merge.Merger.merge(Merger.java:186)
	at org.eclipse.jgit.merge.ThreeWayMerger.merge(ThreeWayMerger.java:95)
	at org.eclipse.jgit.api.CherryPickCommand.call(CherryPickCommand.java:148)
	at org.netbeans.libs.git.jgit.commands.CherryPickCommand.applySteps(CherryPickCommand.java:215)
	at org.netbeans.libs.git.jgit.commands.CherryPickCommand.run(CherryPickCommand.java:108)
	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:56)
	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:53)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at org.netbeans.libs.git.jgit.commands.GitCommand.execute(GitCommand.java:53)
	at org.netbeans.libs.git.GitClient.cherryPick(GitClient.java:445)
	at org.netbeans.modules.git.client.GitClient$7.call(GitClient.java:272)
	at org.netbeans.modules.git.client.GitClient$7.call(GitClient.java:268)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1$1.call(GitClient.java:933)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1.call(GitClient.java:956)
	at org.netbeans.modules.git.FilesystemInterceptor.runWithoutExternalEvents(FilesystemInterceptor.java:473)
	at org.netbeans.modules.git.Git.runWithoutExternalEvents(Git.java:259)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethodIntern(GitClient.java:966)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:893)
	at org.netbeans.modules.git.client.GitClient$CommandInvoker.access$300(GitClient.java:869)
	at org.netbeans.modules.git.client.GitClient.cherryPick(GitClient.java:268)
	at org.netbeans.modules.git.ui.branch.CherryPickAction$1$1.call(CherryPickAction.java:172)
	at org.netbeans.modules.git.ui.branch.CherryPickAction$1$1.call(CherryPickAction.java:165)
	at org.netbeans.modules.versioning.indexingbridge.Bridge$1.call(Bridge.java:41)
	at org.netbeans.modules.parsing.api.indexing.IndexingManager.runProtected(IndexingManager.java:360)
	at org.netbeans.modules.versioning.indexingbridge.Bridge.runWithoutIndexing(Bridge.java:36)
	at org.netbeans.modules.versioning.util.IndexingBridge.runWithoutIndexing(IndexingBridge.java:116)
	at org.netbeans.modules.versioning.util.IndexingBridge.runWithoutIndexing(IndexingBridge.java:79)
	at org.netbeans.modules.git.utils.GitUtils.runWithoutIndexing(GitUtils.java:896)
	at org.netbeans.modules.git.ui.branch.CherryPickAction$1.perform(CherryPickAction.java:165)
	at org.netbeans.modules.git.client.GitProgressSupport.performIntern(GitProgressSupport.java:92)
	at org.netbeans.modules.git.client.GitProgressSupport.run(GitProgressSupport.java:85)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

### How to reproduce

I have a Java Maven project with local git repository. I try to do a cherry-pick using a context menu Git -> Branch/Tag -> Cherry Pick. I use a revision selector to select a proper revision. However a few seconds after using Apply button I can see an error. Git cherry-pick command fails, is not applied.

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; cs_CZ (nb)

### JDK

20.0.2; Java HotSpot(TM) 64-Bit Server VM 20.0.2+9-78

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Verified!  Thanks for the report.  Can reproduce, and definitely a regression from NB19.

**Comment by neilcsmith-net** [comment]
If possible, please try the dev-build zip from https://github.com/apache/netbeans/actions/runs/6809899634?pr=6672 (under the graph in the artifacts section) and see if it fixes this for you.

**Comment by vitsuchanek** [comment]
Hi Neil, I've just tested a git cherry-pick (and git push) - it works fine with the dev-build. Thanks for the fast fix! Vít

**Comment by neilcsmith-net** [comment]
@vitsuchanek thanks for testing!
