### ISSUE TITLE
Netbeans 19 does not statrs on MacOS 14

### ISSUE THREAD

**Issue by mailer** [apache/netbeans#6761]
### Apache NetBeans version

Apache NetBeans 19

### What happened

Could not start IDE. I tried to start it from terminal and got:
```
Alexanders-MacBook-Pro:~ mailer67$ /Applications/Apache\ NetBeans.app/Contents/Resources/netbeans/bin/netbeans 
WARNING: package sun.awt.X11 not in java.desktop
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
java.lang.RuntimeException: Permission denied
	at org.eclipse.osgi.framework.internal.core.Framework.<init>(Framework.java:194)
	at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.internalInit(EquinoxLauncher.java:67)
	at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.init(EquinoxLauncher.java:37)
	at org.eclipse.osgi.launch.Equinox.init(Equinox.java:178)
	at org.netbeans.modules.netbinox.Netbinox.init(Netbinox.java:63)
	at org.netbeans.core.netigso.Netigso.prepare(Netigso.java:146)
	at org.netbeans.NetigsoHandle.turnOn(NetigsoHandle.java:115)
	at org.netbeans.ModuleManager.doEnable(ModuleManager.java:1495)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1350)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1275)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:316)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:252)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:173)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:142)
	at org.netbeans.core.startup.Main.start(Main.java:303)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.io.IOException: Permission denied
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(File.java:2170)
	at org.eclipse.osgi.storagemanager.StorageManager.initializeInstanceFile(StorageManager.java:188)
	at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:708)
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.initFileManager(BaseStorage.java:226)
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.initialize(BaseStorage.java:160)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.initializeStorage(BaseAdaptor.java:123)
	at org.eclipse.osgi.framework.internal.core.Framework.<init>(Framework.java:192)
	... 17 more
```
In System Settings -> Privacy & Security, application has full disk access
[messages.log](https://github.com/apache/netbeans/files/13493356/messages.log)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Sonoma 14.1.1

### JDK

Oracle JDK 17.0.9

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mailer** [comment]
Incorrect access rights to the user's cache directory. ~/Library/Caches/NetBeans owned by root not by user. All works fine after correction.
