### ISSUE TITLE
java lang NullPointerException

### ISSUE THREAD

**Issue by pepiuox** [apache/netbeans#6779]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

java.lang.NullPointerException
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at org.web3d.x3d.config.X3DEditKeyStoreProvider.getKeyStore(X3DEditKeyStoreProvider.java:70)
	at org.netbeans.modules.autoupdate.services.Utilities.getKeyStore(Utilities.java:126)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl.verifyNbm(InstallSupportImpl.java:1073)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl.doValidate(InstallSupportImpl.java:852)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl.doValidate(InstallSupportImpl.java:805)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl.access$900(InstallSupportImpl.java:75)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl$2.call(InstallSupportImpl.java:247)
	at org.netbeans.modules.autoupdate.services.InstallSupportImpl$2.call(InstallSupportImpl.java:220)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused: java.util.concurrent.ExecutionException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[catch] at org.netbeans.modules.autoupdate.services.InstallSupportImpl.doValidate(InstallSupportImpl.java:263)
	at org.netbeans.api.autoupdate.InstallSupport.doValidate(InstallSupport.java:108)
	at org.netbeans.modules.autoupdate.ui.wizards.InstallStep.handleValidation(InstallStep.java:504)
	at org.netbeans.modules.autoupdate.ui.wizards.InstallStep.doDownloadAndVerificationAndInstall(InstallStep.java:245)
	at org.netbeans.modules.autoupdate.ui.wizards.InstallStep.access$500(InstallStep.java:89)
	at org.netbeans.modules.autoupdate.ui.wizards.InstallStep$3.run(InstallStep.java:219)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.openide.util.RequestProcessor$Processor.doEvaluate(RequestProcessor.java:2088)
	at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1652)
	at org.netbeans.modules.autoupdate.ui.wizards.InstallStep$2.propertyChange(InstallStep.java:196)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8722)
	at org.netbeans.modules.autoupdate.ui.wizards.OperationPanel.access$200(OperationPanel.java:44)
	at org.netbeans.modules.autoupdate.ui.wizards.OperationPanel$1.run(OperationPanel.java:82)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

### How to reproduce

when starting the netbeans 20 platform. it starts with that error

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

the error appears when starting the platform

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
The stackrace points to the X3D plugin:

```
at org.web3d.x3d.config.X3DEditKeyStoreProvider.getKeyStore(X3DEditKeyStoreProvider.java:70)
```

I had a quick look at the plugin and it seems they decided to manipulate system properties to hold their own keystore. This fails.
