### ISSUE TITLE
org.netbeans.lib.nbjavac.services.CancelAbort

### ISSUE THREAD

**Issue by sysmat** [apache/netbeans#6790]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

```
org.netbeans.lib.nbjavac.services.CancelAbort
	at org.netbeans.lib.nbjavac.services.CancelService.abortIfCanceled(CancelService.java:53)
	at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser.classDeclaration(NBParserFactory.java:115)
	at com.sun.tools.javac.parser.JavacParser.classOrRecordOrInterfaceOrEnumDeclaration(JavacParser.java:4209)
	at com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:4198)
	at com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:4005)
	at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser.parseCompilationUnit(NBParserFactory.java:89)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:652)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:629)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:689)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1036)
	at com.sun.tools.javac.main.JavaCompiler$InitialFileParser.parse(JavaCompiler.java:1973)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1023)
	at com.sun.tools.javac.api.JavacTaskImpl.parseInternal(JavacTaskImpl.java:258)
	at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at com.sun.tools.javac.api.JavacTaskImpl.parse(JavacTaskImpl.java:248)
Caused: java.lang.IllegalStateException
	at com.sun.tools.javac.api.JavacTaskImpl.parse(JavacTaskImpl
```

### How to reproduce

just work with IDE, every few minut error happend

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

win 11

### JDK

jdk 17-20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
what is the rest of the stack trace?

**Comment by mbien** [comment]
just happened to me too, during scanning right after NB start, haven't touched anything yet:
```
WARNING [org.netbeans.modules.java.source.indexing.JavaIndex]: VanillaCompileWorker caused an exception
File: file:/home/mbien/NetBeansProjects/netbeans/java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/MoveMembersTransformer.java
Root: /home/mbien/NetBeansProjects/netbeans/java/refactoring.java/src
Bootpath: /home/mbien/NetBeansProjects/netbeans/java/libs.javacapi/external/nb-javac-jdk-21u-api.jar:/home/mbien/NetBeansProjects/netbeans/java/libs.javacapi/external/nb-javac-jdk-21u.jar:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.base/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.compiler/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.datatransfer/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.desktop/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.instrument/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.logging/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.management/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.management.rmi/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.naming/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.net.http/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.prefs/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.rmi/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.scripting/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.se/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.security.jgss/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.security.sasl/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.smartcardio/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.sql/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.sql.rowset/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.transaction.xa/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.xml/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/java.xml.crypto/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.accessibility/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.aot/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.attach/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.charsets/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.compiler/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.crypto.cryptoki/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.crypto.ec/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.dynalink/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.editpad/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.hotspot.agent/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.httpserver/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.ed/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.jvmstat/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.le/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.opt/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.vm.ci/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.vm.compiler/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.internal.vm.compiler.management/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jartool/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.javadoc/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jcmd/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jconsole/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jdeps/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jdi/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jdwp.agent/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jfr/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jlink/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jshell/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jsobject/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.jstatd/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.localedata/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.management/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.management.agent/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.management.jfr/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.naming.dns/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.naming.ldap/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.naming.rmi/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.net/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.pack/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.rmic/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.scripting.nashorn/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.scripting.nashorn.shell/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.sctp/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.security.auth/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.security.jgss/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.unsupported/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.unsupported.desktop/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.xml.dom/:nbjrt:file:/home/mbien/dev/java/jdk-11.0.21.9.1-corretto/!/modules/jdk.zipfs/
Classpath: /home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-api-annotations-common.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-api-java.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-api-java-classpath.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-api-lsp.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-api-progress.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-api-progress-nb.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-libs-javacapi.jar:/home/mbien/NetBeansProjects/netbeans/java/libs.javacapi/external/nb-javac-jdk-21u-api.jar:/home/mbien/NetBeansProjects/netbeans/java/libs.javacapi/external/nb-javac-jdk-21u.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-editor-document.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-editor-lib.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-editor-lib2.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-modules-editor-mimelookup.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-editor-settings.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-editor-util.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-gototest.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-file-launcher.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-lexer.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-platform.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-project.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-project-ui.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-source.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-source-base.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-modules-java-sourceui.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-modules-javahelp.jar:/home/mbien/NetBeansProjects/netbeans/platform/javahelp/external/jhall-2.0_05.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-lexer.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-parsing-api.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-parsing-indexing.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-projectapi.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-projectuiapi-base.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-modules-queries.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-modules-refactoring-api.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/ide/modules/org-netbeans-spi-editor-hints.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/java/modules/org-netbeans-spi-java-hints.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-swing-outline.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-netbeans-swing-plaf.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-actions.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-awt.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-dialogs.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-explorer.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/core/org-openide-filesystems.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-loaders.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/lib/org-openide-modules.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-nodes.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-text.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/lib/org-openide-util.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/lib/org-openide-util-lookup.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/lib/org-openide-util-ui.jar:/home/mbien/NetBeansProjects/netbeans/nbbuild/netbeans/platform/modules/org-openide-windows.jar
Sourcepath: /home/mbien/NetBeansProjects/netbeans/java/refactoring.java/src:/home/mbien/NetBeansProjects/netbeans/java/refactoring.java/build/classes-generated
org.netbeans.lib.nbjavac.services.CancelAbort
	at org.netbeans.lib.nbjavac.services.CancelService.abortIfCanceled(CancelService.java:53)
	at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser.classDeclaration(NBParserFactory.java:115)
	at com.sun.tools.javac.parser.JavacParser.classOrRecordOrInterfaceOrEnumDeclaration(JavacParser.java:4209)
	at com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:4198)
	at com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:4005)
	at org.netbeans.lib.nbjavac.services.NBParserFactory$NBJavacParser.parseCompilationUnit(NBParserFactory.java:89)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:652)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:629)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:689)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1036)
	at com.sun.tools.javac.main.JavaCompiler$InitialFileParser.parse(JavaCompiler.java:1973)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1023)
	at com.sun.tools.javac.api.JavacTaskImpl.parseInternal(JavacTaskImpl.java:258)
	at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at com.sun.tools.javac.api.JavacTaskImpl.parse(JavacTaskImpl.java:248)
Caused: java.lang.IllegalStateException
	at com.sun.tools.javac.api.JavacTaskImpl.parse(JavacTaskImpl.java:252)
[catch] at org.netbeans.modules.java.source.indexing.VanillaCompileWorker.compile(VanillaCompileWorker.java:216)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:360)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:274)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2749)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2626)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2625)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.lambda$scanSource$3(RepositoryUpdater.java:5735)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1400(RepositoryUpdater.java:135)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5770)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5443)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5075)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5842)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$3400(RepositoryUpdater.java:5855)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

**Comment by matthiasblaesing** [comment]
@lahodaj this might be a bug in javac. `com.sun.tools.javac.util.Abort` (super class of `CancelAbort`) says:

> Throwing an instance of this class causes (silent) termination of the main compiler method.

I see though:

https://github.com/openjdk/jdk/blob/34351b7a7950a3b563748f40f2619374f62f9b16/src/jdk.compiler/share/classes/com/sun/tools/javac/api/JavacTaskImpl.java#L247-L253

Line 252 wraps the `CancelAbort`/`Abort` we are prepared to handle into an `IllegalStateException`, which hits the hard error path.

Given the description in `Abort`, I would expect something like this:

```
    @Override @DefinedBy(Api.COMPILER_TREE)
    public Iterable<? extends CompilationUnitTree> parse() {
        Pair<Iterable<? extends CompilationUnitTree>, Throwable> result =  invocationHelper(this::parseInternal);
        if (result.snd == null) {
            return result.fst;
        } else if(result.snd instanceof Abort) {
            throw (Abort) result.snd;
        } else {
            throw new IllegalStateException(result.snd);
        }
    }
```

The alternative would be to check the exception chain in `VanillaCompileWorker` and see if either the original throwable is `CancelAbort` or one of the causes higher up in the chain is. If `CancelAbort` is found, the same behavior would be invoked, that the current direct catch of `CancelAbort` shows.

What do you think?

**Comment by matthiasblaesing** [comment]
@sysmat can you reproduce the problem? It would be helpful if you could check if #6865 fixes the issue. A test built is available from the checks page https://github.com/apache/netbeans/actions/runs/7267688377 or directly: https://github.com/apache/netbeans/actions/runs/7267688377/artifacts/1125245931
@lahodaj #6865 implements my second suggestion (fixing the issue in NetBeans) by scanning the exception hierarchy. What do you think about the approach?
