### ISSUE TITLE
java.lang.AssertionError: Unexpected tree error

### ISSUE THREAD

**Issue by luvunix** [apache/netbeans#6822]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Started NetBeans 20 and was notified of an exception.
[messages.log](https://github.com/apache/netbeans/files/13624987/messages.log)
[CollectionsCache_3.zip](https://github.com/apache/netbeans/files/13624990/CollectionsCache_3.zip)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Microsoft JDK 17.0.9+8 (x64)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Experienced the issue in NetBeans 19 so updated to 20.  Same issue occurred.

### Are you willing to submit a pull request?

No

**Comment by luvunix** [comment]
Just realized that attempting to access Javadoc ([Ctrl]-mouse hover) in this specific source file does not work and throws this exception.  It does not matter whether I am trying to access JavaDoc defined within the source file or within the JDK (e.g., attempting to access the Collections Javadoc).

**Comment by luvunix** [comment]
Also, code completion works, but syntax errors are not highlighted.

**Comment by palaashatri** [comment]
Based on a quick overview of the error message, it looks like the folder it's trying to access is already being read by some other thread, which has locked the files inside it..

Are you running two instances of Netbeans, or is the file already under lock by some other process?

**Comment by luvunix** [comment]
First, my apologies on how ugly the code is.  I did not realize how much I depended on syntax highlighting.  I cleaned the code up and then started playing around with it, seeing if I could find a way to trigger the error intentionally, and I did.

What I found is that I can use the generic to declare the Collection and to get and set the collection.  But the moment I change the parameter in the `addEntry()`, `doesEntryExist()`, and `removeEntry()` methods from a concrete class to the generic, the exception gets triggered and I lose syntax highlighting and Javadoc access.

For example, the following declaration will not trigger the exception (although it does create an error in the method) :

`public boolean addEntry( String entry ) throws IllegalArgumentException`

Changing the declaration to the following then triggers the exception immediately:

`public boolean addEntry( <?> entry ) throws IllegalArgumentException`

Messages log and code attached.  Thanks again for your help.

[messages.log](https://github.com/apache/netbeans/files/13628696/messages.log)
[CollectionsCache.zip](https://github.com/apache/netbeans/files/13628697/CollectionsCache.zip)

**Comment by mbien** [comment]
@luvunix if you would manage to create a small reproducer for this exception - that would be great. We might have to file this against OpenJDK.


exception from the log for copy/paste convenience:
```
Caused: java.lang.AssertionError: Unexpected tree: (ERROR) ? (ERROR) > entry : (ERROR) with kind: CONDITIONAL_EXPRESSION within: (ERROR) ? (ERROR) > entry : (ERROR) with kind: CONDITIONAL_EXPRESSION
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.validateAnnotatedType(Attr.java:5918)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitVarDef(Attr.java:5764)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1022)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:58)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitMethodDef(Attr.java:5754)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:916)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitClassDef(Attr.java:5817)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:814)
	at com.sun.tools.javac.comp.Attr.validateTypeAnnotations(Attr.java:5714)
	at com.sun.tools.javac.code.TypeAnnotations.lambda$validateTypeAnnotationsSignatures$1(TypeAnnotations.java:144)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:200)
	at com.sun.tools.javac.comp.Annotate.unblockAnnotations(Annotate.java:144)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:157)
	at com.sun.tools.javac.main.JavaCompiler.enterDone(JavaCompiler.java:1820)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1074)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:345)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:748)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:541)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:142)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

**Comment by luvunix** [comment]
As requested (if I am understanding the request).  Create an class with the following method:

`public void addEntry( <?> entry ) {`
`    // "<?> in the parameter declaration triggers the bug`
`}`

Change the "<?>" to "String", and things are normal.  Change back to "<?>" and the exception is triggered immediately.
