### ISSUE TITLE
java.lang.AssertionError

### ISSUE THREAD

**Issue by thetigergo** [apache/netbeans#6840]
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened
```

java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:62)
	at com.sun.tools.javac.comp.Modules.allModules(Modules.java:1223)
	at com.sun.tools.javac.model.JavacElements.getAllModuleElements(JavacElements.java:128)
	at org.netbeans.modules.java.source.ElementUtils.getTypeElementByBinaryName(ElementUtils.java:49)
	at org.netbeans.api.java.source.ElementHandle.getTypeElementByBinaryName(ElementHandle.java:663)
	at org.netbeans.api.java.source.ElementHandle.resolveImpl(ElementHandle.java:162)
	at org.netbeans.api.java.source.ElementHandle.resolve(ElementHandle.java:131)
	at org.netbeans.modules.web.el.completion.ELJavaCompletionItem$ElementHandleAdapter$1.run(ELJavaCompletionItem.java:315)
	at org.netbeans.modules.web.el.completion.ELJavaCompletionItem$ElementHandleAdapter$1.run(ELJavaCompletionItem.java:311)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:60)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:364)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:347)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:318)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:433)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.web.el.completion.ELJavaCompletionItem$ElementHandleAdapter.document(ELJavaCompletionItem.java:311)
	at org.netbeans.modules.web.el.completion.ELCodeCompletionHandler.documentElement(ELCodeCompletionHandler.java:729)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionDoc.<init>(GsfCompletionDoc.java:91)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionDoc.create(GsfCompletionDoc.java:108)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionProvider$JavaCompletionQuery.resolveDocumentation(GsfCompletionProvider.java:528)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionProvider$JavaCompletionQuery$1.run(GsfCompletionProvider.java:315)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionProvider$JavaCompletionQuery.query(GsfCompletionProvider.java:320)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

JDK 11.0.20

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by thetigergo** [comment]
Product Version: Apache NetBeans IDE 20
Java: 11.0.20; Java HotSpot(TM) 64-Bit Server VM 11.0.20+9-LTS-256
Runtime: Java(TM) SE Runtime Environment 11.0.20+9-LTS-256
System: Windows 11 version 10.0 running on amd64; Cp1252; en_US (nb)
User directory: C:\Users\USER\AppData\Roaming\NetBeans\20
Cache directory: C:\Users\USER\AppData\Local\NetBeans\Cache\20

**Comment by mbien** [comment]
how is this reproducible?
