### ISSUE TITLE
PHP: NullPointerException after opening any php project

### ISSUE THREAD

**Issue by troizet** [apache/netbeans#6880]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Throws a NullPointerException exception after opening any php project.
```
java.lang.NullPointerException: Cannot invoke "org.netbeans.api.java.classpath.ClassPath.addPropertyChangeListener(java.beans.PropertyChangeListener)" because "this.compilePath" is null
```

In the logs before the stack trace there is such a line:
```
WARNING [org.netbeans.modules.java.source.indexing.JavaIndex]: Exception while checking cache validity for root: nbfs://nbhost/SystemFileSystem/PHP/RuntimeLibraries/
```

### Language / Project Type / NetBeans Component

PHP project

### How to reproduce

Just open any php project.

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

Debian GNU/Linux 12 (bookworm)

### JDK

OpenJDK Runtime Environment 17.0.9+9-Debian-1deb12u1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Stack trace:
```
java.lang.NullPointerException: Cannot invoke "org.netbeans.api.java.classpath.ClassPath.addPropertyChangeListener(java.beans.PropertyChangeListener)" because "this.compilePath" is null
	at org.netbeans.modules.java.source.indexing.APTUtils.<init>(APTUtils.java:138)
	at org.netbeans.modules.java.source.indexing.APTUtils.create(APTUtils.java:231)
	at org.netbeans.modules.java.source.indexing.APTUtils.get(APTUtils.java:179)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer$MetadataCheck.call(JavaCustomIndexer.java:1499)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer$MetadataCheck.call(JavaCustomIndexer.java:1486)
[catch] at org.openide.util.RequestProcessor$WaitableCallable.call(RequestProcessor.java:1280)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

### Are you willing to submit a pull request?

No

**Comment by troizet** [comment]
Probably related to this PR: https://github.com/apache/netbeans/pull/6329

**Comment by junichi11** [comment]
@lahodaj Could you please have a look at this?

**Comment by matthiasblaesing** [comment]
I tested with the same setup as #6881 and indeed reverting 192bb526a9f535485905998674460c1aaafb9b20 also fixes this problem.
