### ISSUE TITLE
Unexpected Exception - Malformed \uxxxx encoding

### ISSUE THREAD

**Issue by JQL** [apache/netbeans#6942]
### Apache NetBeans version

Apache NetBeans 20

### What happened

On starting Netbeans 20, just after the background scanning external files ends, I am getting the exception. Netbeans seems to be functioning correctly.

### Language / Project Type / NetBeans Component

PHP

### How to reproduce

Start Netbeans 20 with two open PHP projects

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Linux Mint 19.3 Cinnamon (5.4.0-150-generic) - Linux version 5.4.0-150-generic running on amd64; UTF-8; en_GB (nb)

### JDK

OpenJDK Runtime Environment 17.0.7+7-Ubuntu-0ubuntu118.04

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Unexpected Exception Category: Error
```
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
  at java.base/java.util.Properties.loadConvert(Properties.java:662)
  at java.base/java.util.Properties.load0(Properties.java:455)
  at java.base/java.util.Properties.load(Properties.java:408)
  at org.netbeans.modules.lsp.client.bindings.CustomIndexerImpl.handleStoredFiles(CustomIndexerImpl.java:83)
  at org.netbeans.modules.lsp.client.bindings.CustomIndexerImpl.access$000(CustomIndexerImpl.java:46)
  at org.netbeans.modules.lsp.client.bindings.CustomIndexerImpl$FactoryImpl.filesDeleted(CustomIndexerImpl.java:122)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.delete(RepositoryUpdater.java:2595)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.lambda$scanSource$3(RepositoryUpdater.java:5728)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
  at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1400(RepositoryUpdater.java:135)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5770)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5443)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5075)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5842)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$3400(RepositoryUpdater.java:5855)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
  at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
  at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
  at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
  at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
  at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
  at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
  at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
  at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
  at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
  at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I take a look at this

**Comment by JQL** [comment]
I have located the project which is causing the problem. Unfortunately, I can't find a problem in the project itself, yet. Can anyone point me towards what might be causing the problem please?

**Comment by mbien** [comment]
@JQL the file isn't in your project, it is a properties file (key=value) which netbeans wrote during indexing. For some reason it contains illegal characters. I changed the code in the PR linked above so that it would reset the file if it got corrupted and log the exception with file location etc.

it is one of the `index.properties` files in `~/.cache/netbeans/20/index`. To fix this you could remove the index folder while NB is closed and start NB again. This will create a fresh index.
