### ISSUE TITLE
java.lang.NullPointerException: Passed null to FileOwnerQuery.getOwner(FileObject)

### ISSUE THREAD

**Issue by Javier-Viramontes** [apache/netbeans#6993]
### Apache NetBeans version

Apache NetBeans 20

### What happened
```

java.lang.NullPointerException: Passed null to FileOwnerQuery.getOwner(FileObject)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:84)
	at org.netbeans.modules.web.jsf.api.JsfComponentUtils.isMavenBased(JsfComponentUtils.java:214)
	at org.netbeans.modules.web.jsf.JSFFrameworkProvider.createWebModuleExtender(JSFFrameworkProvider.java:301)
	at org.netbeans.modules.maven.j2ee.ui.customizer.impl.CustomizerFrameworks.jButtonAddActionPerformed(CustomizerFrameworks.java:368)
	at org.netbeans.modules.maven.j2ee.ui.customizer.impl.CustomizerFrameworks.access$500(CustomizerFrameworks.java:71)
	at org.netbeans.modules.maven.j2ee.ui.customizer.impl.CustomizerFrameworks$4.actionPerformed(CustomizerFrameworks.java:267)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1069)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1114)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1092)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:104)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:123)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:77)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1076)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl$1.run(CustomizerProviderImpl.java:169)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:97)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:72)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:66)
	at org.openide.util.Mutex.readAccess(Mutex.java:242)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:150)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:118)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:113)
	at org.netbeans.modules.project.ui.actions.CustomizeProject$1$1.run(CustomizeProject.java:135)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### Language / Project Type / NetBeans Component

Java Maven Web application project

### How to reproduce

ProjectName -> Properties -> Frameworks -> JavaServer Faces
![2024-01-24 14_56_56-ISPCenter-web-1 0 - Apache NetBeans IDE 20](https://github.com/apache/netbeans/assets/7283174/3e56b7a4-a771-4793-b4b8-693f550a68a5)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

![2024-01-24 14_56_56-ISPCenter-web-1 0 - Apache NetBeans IDE 20](https://github.com/apache/netbeans/assets/7283174/84d8c466-a2f8-4556-a0a8-b220250c3804)

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
This is not reproducible for me. Please create a minimal sample that reproduces your problem and give detailed steps to reproduce. The code may have problems, but looks ok in general, unless the setup is broken.

**Comment by Javier-Viramontes** [comment]
I resolved the issue by manually adding the "src-main-java, resources, WEB-INF" folders and then added the framework using the wizard.
Anyways, thanks a lot.
