### ISSUE TITLE
Netbeans 20 not recognizing it has started Wildfly 31.0.0

### ISSUE THREAD

**Issue by dstutz** [apache/netbeans#6997]
### Apache NetBeans version

Apache NetBeans 20

### What happened

Right click and start and I see the server fully starting in the output log 
```
05:54:35,466 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 31.0.0.Final (WildFly Core 23.0.1.Final) started in 2971ms - Started 329 of 571 services (333 services are lazy, passive or on-demand) - Server configuration file in use: standalone-full.xml
```
but I get an exception:

```
java.lang.NoSuchMethodException: org.jboss.as.controller.client.ModelControllerClient$Factory.create(java.lang.String,int,javax.security.auth.callback.CallbackHandler,javax.net.ssl.SSLContext,int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyManagementAPI.createClient(WildflyManagementAPI.java:70)
[catch] at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.getClient(WildflyClient.java:243)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.executeAsync(WildflyClient.java:342)
	at org.netbeans.modules.javaee.wildfly.ide.commands.WildflyClient.isServerRunning(WildflyClient.java:289)
	at org.netbeans.modules.javaee.wildfly.ide.WildflyStartServer$1.run(WildflyStartServer.java:215)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

```
and now NB doesn't realize that it's running and you can't stop it nor will a project deploy.  Clicking refresh server status will make the above Exception show up again.

Since NB doesn't realize it has started it, if you try to start again you get an Error window with `<Server name> Start Failed. HTTP Connector port <port #> is already in use.`

This seems related/similar to #5947 (fixed by #6138).

### Language / Project Type / NetBeans Component

Wildfly support

### How to reproduce

Unzip Wildfly 31.0.0, add to Servers, Start server

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 64

### JDK

Temurin jdk-21.0.1.12-hotspot

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
@WaveWall you can check yourself if you can fix it. The code is here:

https://github.com/apache/netbeans/blob/681aa7656757ed9ddc7c2f19af8360f85dcfdf66/enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/commands/WildflyManagementAPI.java#L51-L72

but the other methods in that class should also be checked if they still work. Feel free to open a PR.
