### ISSUE TITLE
Unable to create an NetBeans Application WITH sample on NB21rc2

### ISSUE THREAD

**Issue by trixon** [apache/netbeans#7018]
### Apache NetBeans version

Apache NetBeans 21 release candidate

### What happened

The new project dialog is unable to create a new NetBeans Application _with_ a sample module, _without_ works just fine.

With maven that is.

```
WARNING [org.openide.WizardDescriptor]
java.lang.NullPointerException: Cannot invoke "java.util.Properties.stringPropertyNames()" because "properties" is null
	at org.netbeans.modules.maven.NbMavenProjectImpl.loadMavenProject(NbMavenProjectImpl.java:316)
	at org.netbeans.modules.maven.api.NbMavenProject.loadAlternateMavenProject(NbMavenProject.java:317)
	at org.netbeans.modules.maven.apisupport.NbmWizardIterator.instantiate(NbmWizardIterator.java:183)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1050)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.netbeans.modules.project.ui.NewProjectWizard.handleInstantiate(NewProjectWizard.java:51)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:223)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:135)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1605)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

### Language / Project Type / NetBeans Component

NetBeans Application

### How to reproduce

Use the new project dialog to create a new NetBeans Application, check sample.

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

Linux version 6.5.0-15-generic running on amd64; UTF-8; sv_SE (nb)

### JDK

21.0.2; OpenJDK 64-Bit Server VM 21.0.2+13-LTS

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
This issue looks like it stems from #6789   The earlier code had a check for `properties` being `null` at https://github.com/apache/netbeans/blame/release210/java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java#L313

Should the `null` check go back in @sdedic Or is calling this with `null` a sign of an issue elsewhere?  I'm not sure which other Maven wizards might be affected.

**Comment by sdedic** [comment]
@neilcsmith-net  will fix with NPE guards. The original header made no assumption on null-ness.

**Comment by neilcsmith-net** [comment]
@sdedic could we get a PR tomorrow?  Or I can if you can confirm that the correct behaviour is to ignore the properties when `null` rather than fill in any defaults?  Would like to get this fixed in 21-rc3 as that will hopefully be our actual release version. Thanks!

**Comment by sdedic** [comment]
Sorry, was busy elsewhere and forgot about this one. Yes, I'll try to prepare a PR early morning (CET).

**Comment by neilcsmith-net** [comment]
This should be fixed in 21-rc3.  Please test that when it's out and comment here if you still see any issues.
