### ISSUE TITLE
java.lang.IllegalStateException: No builtin diff provider

### ISSUE THREAD

**Issue by coffeebeantraining** [apache/netbeans#7052]
### Apache NetBeans version

Apache NetBeans 20

### What happened

java.lang.IllegalStateException: No builtin diff provider
	at org.netbeans.modules.diff.DiffModuleConfig.getBuiltinProvider(DiffModuleConfig.java:253)
	at org.netbeans.modules.diff.DiffModuleConfig.setOptions(DiffModuleConfig.java:235)
	at org.netbeans.modules.diff.options.DiffOptionsController.applyChanges(DiffOptionsController.java:62)
	at org.netbeans.modules.options.advanced.Model$DelegatingController.applyChanges(Model.java:295)
	at org.netbeans.modules.options.advanced.Model.applyChanges(Model.java:178)
	at org.netbeans.modules.options.advanced.AdvancedPanel.applyChanges(AdvancedPanel.java:83)
	at org.netbeans.modules.options.advanced.AdvancedPanelController.applyChanges(AdvancedPanelController.java:53)
	at org.netbeans.modules.options.CategoryModel$Category.applyChanges(CategoryModel.java:379)
	at org.netbeans.modules.options.CategoryModel$Category.access$1100(CategoryModel.java:302)
	at org.netbeans.modules.options.CategoryModel.save(CategoryModel.java:198)
	at org.netbeans.modules.options.OptionsPanel.save(OptionsPanel.java:288)
	at org.netbeans.modules.options.OptionsDisplayerImpl$OptionsPanelListener$3.run(OptionsDisplayerImpl.java:515)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:252)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

### Language / Project Type / NetBeans Component

IDE itself

### How to reproduce

nothing to reproduce.  The IDE just threw the exception.
java.lang.IllegalStateException: No builtin diff provider
	at org.netbeans.modules.diff.DiffModuleConfig.getBuiltinProvider(DiffModuleConfig.java:253)
	at org.netbeans.modules.diff.DiffModuleConfig.setOptions(DiffModuleConfig.java:235)
	at org.netbeans.modules.diff.options.DiffOptionsController.applyChanges(DiffOptionsController.java:62)
	at org.netbeans.modules.options.advanced.Model$DelegatingController.applyChanges(Model.java:295)
	at org.netbeans.modules.options.advanced.Model.applyChanges(Model.java:178)
	at org.netbeans.modules.options.advanced.AdvancedPanel.applyChanges(AdvancedPanel.java:83)
	at org.netbeans.modules.options.advanced.AdvancedPanelController.applyChanges(AdvancedPanelController.java:53)
	at org.netbeans.modules.options.CategoryModel$Category.applyChanges(CategoryModel.java:379)
	at org.netbeans.modules.options.CategoryModel$Category.access$1100(CategoryModel.java:302)
	at org.netbeans.modules.options.CategoryModel.save(CategoryModel.java:198)
	at org.netbeans.modules.options.OptionsPanel.save(OptionsPanel.java:288)
	at org.netbeans.modules.options.OptionsDisplayerImpl$OptionsPanelListener$3.run(OptionsDisplayerImpl.java:515)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:252)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 7 Ultimate

### JDK

jdk-21.0.2

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
based on the trace this looks like you changed the settings in `options -> fonts and colors -> diff` and pressed ok. For some reason no `BuiltInDiffProvider` was found.

I am not sure how this can be possible since the provider is in the same module, so it has to be loaded at this point.
