### ISSUE TITLE
Problem using Java with Ant projects

### ISSUE THREAD

**Issue by NttCAD** [apache/netbeans#7244]
### Apache NetBeans version

Apache NetBeans 21

### What happened

1) Use NetBeans 20 (21 doesn't work)

2) Create new java with Ant library class project, and create the class Jlib:

package jlib;

public class Jlib {

	public void printMessage() {
		System.out.print("Ciao!");
	}
	
}

3) Create new Java applicationant project with a Main Class:

package japp;

import jlib.Jlib;

public class Japp {

	public static void main(String[] args) {
		Jlib jlib = new Jlib();
		jlib.printMessage();
	}
	
}

4) Right click property of Japp and add Jlib to the Classpath

5) Compile the projects and run.

### Language / Project Type / NetBeans Component

Java application and library with Ant

### How to reproduce

6) This is what I see into the output window: 

run:
Exception in thread "main" java.lang.RuntimeException: Uncompilable code - cannot find symbol
  symbol:   class Jlib
  location: class japp.Japp
	at japp.Japp.main(Japp.java:1)
/home/luca/.cache/netbeans/20/executor-snippets/run.xml:111: The following error occurred while executing this line:
/home/luca/.cache/netbeans/20/executor-snippets/run.xml:68: Java returned: 1
BUILD FAILED (total time: 2 seconds)

7) Also the editor does not see Jlib.

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

Ubunt 22.04

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by ebarboni** [comment]
Do you have the log eventually ?

**Comment by pedro-w** [comment]
I made a zip with 2 projects (nttjapp and nttjlib) in it. You can use it with `File | Import Project | From Zip...` . When I do this, I can just select the 'nttjapp' project and press Run Project, then NB will compile both projects and run the app. Please can you try and report what happens - if it doesn't work, look at the log as Eric has suggested.
[ntt.zip](https://github.com/apache/netbeans/files/14995050/ntt.zip)

```
ant -f D:\\temp\\ntt\\nttjapp -Dnb.internal.action.name=run run
init:
deps-jar:
Created dir: D:\temp\ntt\nttjapp\build
Updating property file: D:\temp\ntt\nttjapp\build\built-jar.properties
nttjlib.init:
nttjlib.deps-jar:
Created dir: D:\temp\ntt\nttjlib\build
Updating property file: D:\temp\ntt\nttjapp\build\built-jar.properties
Created dir: D:\temp\ntt\nttjlib\build\classes
Created dir: D:\temp\ntt\nttjlib\build\empty
Created dir: D:\temp\ntt\nttjlib\build\generated-sources\ap-source-output
Compiling 1 source file to D:\temp\ntt\nttjlib\build\classes
nttjlib.compile:
Created dir: D:\temp\ntt\nttjlib\dist
Building jar: D:\temp\ntt\nttjlib\dist\nttjlib.jar
nttjlib.deploy:
nttjlib.jar:
Created dir: D:\temp\ntt\nttjapp\build\classes
Created dir: D:\temp\ntt\nttjapp\build\empty
Created dir: D:\temp\ntt\nttjapp\build\generated-sources\ap-source-output
Compiling 1 source file to D:\temp\ntt\nttjapp\build\classes
compile:
run:
Ciao!BUILD SUCCESSFUL (total time: 2 seconds)
```

**Comment by NttCAD** [comment]
Your project works! But if I create this project with my NB 21 on my Linux Ubuntu, it doesn't work.

**Comment by NttCAD** [comment]
In my opinion you should try tu create the projects on Ubuntu.

**Comment by matthiasblaesing** [comment]
I'm on Ubuntu 23.10, with Amazon Corretto 21 and this is not reproducible. @NttCAD did you compile the library project?

**Comment by NttCAD** [comment]
Maybe you don't belive me, but YES

**Comment by matthiasblaesing** [comment]
@NttCAD please check my comment again. Before you answered I had already checked, that compilation of the projects does not change anything. But if you added the library project to the module path of the application project and not to the classpath of the project, then I can reproduce your observation.
If you really added the project to the module path, then this is not a NetBeans issue, but a misunderstand what the module path is and how it differs from the classpath.
@pedro-w did the right thing by sharing the project he created. Please do so too.

**Comment by NttCAD** [comment]
Into the "projet properties" window of my java ant application, "Compile" tab, I added my java library projet to the "Classpath"; not "Module" (I don't use any module). I'm using NB 21, downloaded Binaries (Platform Independent) on ubuntu linux.

**Comment by NttCAD** [comment]
provided zip file and some screenshot

**Comment by pedro-w** [comment]
I see filenames with '!' in them, e.g.  `/dati/!/prjs/Japp` - could this cause a problem in the NB editor but not in javac?

**Comment by NttCAD** [comment]
Incredible... changing folder name it works!! 

Created dir: /dati/test/Japp/dist
Copying 1 file to /dati/test/Japp/build
Copy libraries to /dati/test/Japp/dist/lib.
Building jar: /dati/test/Japp/dist/Japp.jar
To run this application from the command line without Ant, try:
java -jar "/dati/test/Japp/dist/Japp.jar"
deploy:
jar:
BUILD SUCCESSFUL (total time: 3 seconds)

run:
Ciao!BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by neilcsmith-net** [comment]
Good catch @pedro-w - I assume this is caused somewhere by a conflict with use of `!` as separator in JAR URLs.  Not sure how easily this would be fixable, or even how desirable it would be to do so?

**Comment by pedro-w** [comment]
A smoking gun perhaps Neil?

I can confirm that this also affects Windows and Mac (i.e. having projects in a subdirectory of `!`) and if you turn off Compile on Save then you can build & run projects from the IDE but the editor still puts red squiggles under the classes from the other project.

**Comment by NttCAD** [comment]
But I don't understand: this bug is into NetBeans or into JDK? Because I'm using java.util.ResourceBundle class from inside a Jar file, ang I had java.util.MissingResourceException. Now I need to rename the folder "!" and works. 

ant -f /dati/!/prjs/nttcad/ant.xml "run cad"
run cad:
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name nttcad/nttcad/resources/RB, locale it_IT
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2059)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1697)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1600)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1555)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:861)
	at nttcad.common.util.RBObject.<init>(Unknown Source)
	at nttcad.nttcad.resources.RB.msg(Unknown Source)
	at nttcad.nttcad.main.About.show(Unknown Source)
	at nttcad.nttcad.main.MainListener.createJFrame(Unknown Source)
	at nttcad.nttcad.Main.createJFrame(Unknown Source)
	at nttcad.nttcad.Main.createJFrame(Unknown Source)
	at nttcad.cad.Cad.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: IllegalName: nttcad/nttcad/resources/RB
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:901)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1025)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3184)
	at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3165)
	at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1998)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1784)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1670)
	... 10 more

**Comment by pedro-w** [comment]
I think this may be unrelated, but that's only a guess without seeing more code.

> Caused by: java.lang.NoClassDefFoundError: IllegalName: nttcad/nttcad/resources/RB

That name should be a class name, not a path, so it should look more like `nttcad.nttcad.resources.RB`, see for example [here](https://bugs.openjdk.org/browse/JDK-4986512). Have a look at `nttcad.common.util.RBObject` specifically around the call to `getBundle`.

This might be better on the mailing list, have you subscribed to it?

The issue you reported at the top is a bug in NB, I believe, the the JDK itself does not have a problem with `!` in the path.

**Comment by neilcsmith-net** [comment]
> This might be better on the mailing list, have you subscribed to it?

Or GitHub discussions, which we can migrate issues to.  Am going to migrate this.  I think there might be an issue to narrow down from this discussion - feel free to open one that's more targeted once we're clearer where the bug is, and whether it's even in NetBeans.
