### ISSUE TITLE
Error refreshing Docker images

### ISSUE THREAD

**Issue by ksilha-mhi** [apache/netbeans#7275]
### Apache NetBeans version

Apache NetBeans 21

### What happened

Under Services, I added a Docker Instance installed on a server which is connected to my local network. 'Test Connection' passed. I am able to pull images and build containers, however when I try to refresh images I receive the following error notification and the image listing hangs on the hourglass icon saying "Please Wait..."

java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.json.simple.JSONObject.get(Object)" is null
	at org.netbeans.modules.docker.api.DockerAction.getImages(DockerAction.java:153)
	at org.netbeans.modules.docker.ui.node.DockerImagesChildFactory.createKeys(DockerImagesChildFactory.java:89)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:202)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

### Language / Project Type / NetBeans Component

Docker service management tool

### How to reproduce

Refresh Images

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows

### JDK

22

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by lukaz-sampaio** [comment]
I'm with the same problem. I saw the problem is the response. Doesn't have JSON attribute "VirtualSize" causing NullPointerException. I compile the coding with `System.out.println()` in [src.org.netbeans.modules.docker.api.DockerAction.java#L144](https://github.com/apache/netbeans/blob/master/ide/docker.api/src/org/netbeans/modules/docker/api/DockerAction.java#L144) and the response is:

```
[
  {
    "ParentId": "",
    "RepoDigests": [
      "hello-world@sha256:266b191e926f65542fa8daaec01a192c4d292bff79426f47300a046e1bc576fd"
    ],
    "SharedSize": -1,
    "RepoTags": [
      "hello-world:latest"
    ],
    "Size": 13256,
    "Containers": -1,
    "Labels": null,
    "Id": "sha256:d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a",
    "Created": 1683046167
  }
]
```

Don't have "VirtualSize" attribute referenced in [DockerAction.java#L153](https://github.com/apache/netbeans/blob/master/ide/docker.api/src/org/netbeans/modules/docker/api/DockerAction.java#L153) that's causing NullPointerException.

![DockerAction java#L153](https://github.com/apache/netbeans/assets/12944221/7f63114a-6329-4ece-bd93-a206806561c2)


To test, I just put any long value and it worked. Now you just have to see if this "VirtualSize" attribute is important or if it's not there. My computer is limited and the build time here took more than 22 minutes.

**Comment by lukaz-sampaio** [comment]
Researching a little more about how Netbeans reads images, I arrived at the [Docker Engine] documentation (https://docs.docker.com/engine/api/v1.24/#32-images) and did another test specifying the version on the endpoint used in the [DockerAction.doGetRequest()](https://github.com/apache/netbeans/blob/master/ide/docker.api/src/org/netbeans/modules/docker/api/DockerAction.java#L1108) changing to

```java
public List<DockerImage> getImages() {
   try {
       JSONArray value = (JSONArray) doGetRequest("/v1.24/images/json", // version from docker engine added
               Collections.singleton(HttpURLConnection.HTTP_OK));
       List<DockerImage> ret = new ArrayList<>(value.size());
       for (Object o : value) {
           JSONObject json = (JSONObject) o;
           JSONArray repoTags = (JSONArray) json.get("RepoTags");
           String id = (String) json.get("Id");
           long created = (long) json.get("Created");
           long size = (long) json.get("Size");
           long virtualSize = (long) json.get("VirtualSize");
           ret.add(new DockerImage(instance, repoTags, id, created, size, virtualSize));
       }
       return ret;
   } catch (DockerException ex) {
       LOGGER.log(Level.INFO, null, ex);
   }
   return Collections.emptyList();
}
```

And the "VirtualSize" attribute was there.

![Screenshot 2024-06-28 at 14-47-13 WhatsApp](https://github.com/apache/netbeans/assets/12944221/ee356118-8be1-4060-bc63-128aed4db4c1)


Now you just have to see which approach is better.

**Comment by lukaz-sampaio** [comment]
One more thing. Doing a test communicating with the docker socket via cURL also does not have the "VirtualSize" attribute.

```curl
➤ curl --unix-socket /var/run/docker.sock http:/v1.24/images/json
```

![WhatsApp Image 2024-06-28 at 15 13 36](https://github.com/apache/netbeans/assets/12944221/fb357d8d-2105-41b5-8d33-f97646c1a31c)

**Comment by lukaz-sampaio** [comment]
Difference between Size and Virtual Size.

https://github.com/docker/docs/issues/1520#issuecomment-305179362

**Comment by matthiasblaesing** [comment]
Should be fixed by #7533
