### ISSUE TITLE
[PHP]NB not see any classes form project 

### ISSUE THREAD

**Issue by mzawodzinski** [apache/netbeans#7600]
### Apache NetBeans version

Apache NetBeans 22

### What happened

NB22 did not detect any classes from the project in autocomplete, only native are available 

NB22
![obraz](https://github.com/user-attachments/assets/5d967ed4-312a-4155-9f4d-c377e498cd31)

NB14
![obraz](https://github.com/user-attachments/assets/ee2ff7ea-37e9-44ab-81f2-e75471089071)

I tried remove nbproject and ~/.cache/netbeans/22
Without changes

### Language / Project Type / NetBeans Component

PHP

### How to reproduce

Create new empty project, add new file 
write simple code like this 
```
<?php
class someClass{
    private int $x;

    public function __construct()
    {
        $this->(ctral+space)
    }


}
```

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

Debian testing

### JDK

openjdk 23-ea

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Install from official deb file.
That's why I only have 14 of the earlier versions

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment]
Umm, I cannot reproduce it.

![nb-php-gh-7600-1](https://github.com/user-attachments/assets/565495b0-6802-4e72-b412-b0f7143dbf60)

```
Product Version: Apache NetBeans IDE 22
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-0ubuntu322.04
Runtime: OpenJDK Runtime Environment 19.0.2+7-Ubuntu-0ubuntu322.04
System: Linux version 6.5.0-44-generic running on amd64; UTF-8;
```

**Comment by mzawodzinski** [comment]
Is there any option to record this? There are no exceptions, but maybe it can be registered somehow differently?

**Comment by junichi11** [comment]
Did you try checking your IDE log? If you have already checked, I have no idea.
Please try using another Java version.

**Comment by mzawodzinski** [comment]
I installed jdk 22, it works for now.

An error occurred during the first start

![obraz](https://github.com/user-attachments/assets/e31d0d08-704c-49da-bcfb-7ddd071788c8)
from log
```
SEVERE [org.openide.util.Exceptions]

msg
Caused: java.io.SyncFailedException: /home/michal/.cache/netbeans/22/index/s1/lsp-indexer/0/index.properties
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.createData(FolderObj.java:377)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.createDataImpl(FolderObj.java:324)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj$1.call(FolderObj.java:290)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj$1.call(FolderObj.java:288)
	at org.netbeans.modules.masterfs.filebasedfs.FileBasedFileSystem.runAsInconsistent(FileBasedFileSystem.java:98)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.createData(FolderObj.java:293)
	at org.openide.filesystems.FileObject.createData(FileObject.java:1045)
[catch] at org.netbeans.modules.lsp.client.bindings.CustomIndexerImpl.handleStoredFiles(CustomIndexerImpl.java:103)
	at org.netbeans.modules.lsp.client.bindings.CustomIndexerImpl.index(CustomIndexerImpl.java:60)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:274)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2749)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2626)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2625)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.lambda$scanSource$3(RepositoryUpdater.java:5735)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1400(RepositoryUpdater.java:135)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5770)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5443)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5075)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$3400(RepositoryUpdater.java:5855)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
ALL [null]: Cannot create file index.properties in folder /home/michal/.cache/netbeans/22/index/s1/lsp-indexer/0.
```
