### ISSUE TITLE
Not showing errors on Java code

### ISSUE THREAD

**Issue by bobbyw2345** [apache/netbeans#7735]
### Apache NetBeans version

Apache NetBeans 22

### What happened

The following class does not show errors.

I'm pasting the dump produced by Netbeans.
Sorry, I'm not using the latest Netbeans, I'm using Apache Netbeans 16.

```
/*
 * 
 * 
 *   COPYRIGHT 2015 (c)  by  Ansaldo STS
 *   All Rights Reserved.
 * 
 *   This software is furnished under a license and may be used and copied
 *   only in accordance  with the terms of  such license   and with the
 *   copies thereof may not be provided or otherwise made available to any
 *   other person.  no title to and ownership of  the  software is hereby
 *   transferred.
 * 
 *   The information in this software is  subject to change without notice
 *   and  should  not  be  construed as  a commitment by Ansaldo STS
 * 
 *   Ansaldo STS  assumes no responsibility for the use  or
 *   reliability of its software on equipment which is not supplied by
 *   Ansaldo STS.
 * 
 * 
 */
package com.ansaldosts.resto.periodmng.main;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import com.ansaldosts.spp.resto.dao.ConnectionProvider;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import org.slf4j.LoggerFactory;

/**
 *
 *
 *
 * @author Roberto Bianchi roberto.bianchi@ansaldo-sts.com
 */
@Slf4j
public class PeriodMngMain {

    /**
     * Switch per lo schema del DB.
     */
    private final static String SCHEMA = "schema";

    /**
     * Switch per l'url del DB.
     */
    private final static String URL = "url";

    private Connection connection;

    private Properties properties;

    private PeriodMngMain(String[] args) {
        properties = new Properties();
        processArgs(args);
    }

    /**
     * Main.
     *
     * @param args vedi createOptions
     * @throws Exception on error
     */
    public static void main(String[] args)
            throws Exception {
        PeriodMngMain main = new PeriodMngMain(args);

        main.doExport();
    }

    private void doExport() {

        for (Object p : properties.keySet()) {
            log.info("{}:{}", p.toString(), properties.getProperty(p.toString()));
        }
        ConnectionProvider cp
                = new ConnectionProvider(properties.getProperty(SCHEMA),
                        properties.getProperty(SCHEMA), properties.getProperty(URL));

        try {
            connection = cp.getConnection();
            connection.close();

        } catch (Exception ex) {
            log.error("", ex);
            throw new RuntimeException(ex);
        }
    }

    private Options createOptions() {
        Options options = new Options();
        Option o;
        o = Option.builder("v").argName("verbose")
                .desc("sii verboso").build();
        options.addOption(o);
        o = Option.builder().argName(SCHEMA)
                .longOpt(SCHEMA)
                .required()
                .desc("Schema del DB, default SEZIONEDC")
                .hasArgs().build();
        options.addOption(o);

        o = Option.builder().argName(URL)
                .longOpt(URL)
                .desc("url DB ")
                .hasArgs().build();
        options.addOption(o);

        return options;
    }

    private Properties processArgs(String[] args) {
        CommandLineParser parser = new DefaultParser();

        Options options = createOptions();

        Properties retValue = new Properties();
        try {
            CommandLine line = parser.parse(options, args);
            properties.setProperty(SCHEMA, line.getOptionValue(SCHEMA));

            if (line.hasOption(URL)) {
                properties.setProperty(URL, line.getOptionValue(URL));
            }

            Logger root;
            root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
            if (line.hasOption("v")) {
                root.setLevel(Level.DEBUG);
            } else {
                root.setLevel(Level.INFO);
            }
        } catch (ParseException ex) {
            log.error("", ex.getMessage());

            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp(this.getClass().getSimpleName(), options);

            log.info("Esempio di chiamata:sqlExporter.sh --schema RETE --url jdbc:oracle:thin:@192.168.225.206:1521:scc --output /tmp/sqlexporter.sql --tables=\"LOCALITA,TRATTE\"");
            System.exit(1);
        }
        return retValue;
    }

}

----- Classpath: ---------------------------------------------
bootPath: /home/resto/targets/jdk/jdk1.8.0_131/jre/lib/resources.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/rt.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/sunrsasign.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/jsse.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/jce.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/charsets.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/jfr.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/classes:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/jaccess.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/jfxrt.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/sunpkcs11.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/nashorn.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/localedata.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/sunec.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/sunjce_provider.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/zipfs.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/dnsns.jar:/home/resto/targets/jdk/jdk1.8.0_131/jre/lib/ext/cldrdata.jar
classPath: /home/resto/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar:/home/resto/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar:/home/resto/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar:/home/resto/.m2/repository/com/ansaldo-sts/spp/resto-dao/9.2-SNAPSHOT/resto-dao-9.2-SNAPSHOT.jar:/home/resto/.m2/repository/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar:/home/resto/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/home/resto/.m2/repository/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar:/home/resto/.m2/repository/org/projectlombok/lombok/1.16.2/lombok-1.16.2.jar:/home/resto/workspace-bw/RESTO/modules/PeriodMng/target/classes
sourcePath: /home/resto/workspace-bw/RESTO/modules/PeriodMng/src/main/java:/home/resto/workspace-bw/RESTO/modules/PeriodMng/src/main/resources
----- Original exception ---------------------------------------------
com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.ExceptionInInitializerError
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:735)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:815)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:909)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2300(JavacProcessingEnvironment.java:113)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1252)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1367)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:62)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1133)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:747)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:540)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:141)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: java.lang.ExceptionInInitializerError
	at lombok.javac.handlers.HandleGetter.<clinit>(HandleGetter.java:298)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:170)
	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:155)
	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
	at lombok.javac.apt.Processor.init(Processor.java:86)
	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:973)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:686)
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:366)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at lombok.javac.JavacTreeMaker$SchroedingerType.getFieldCached(JavacTreeMaker.java:156)
	at lombok.javac.JavacTreeMaker$TypeTag.typeTag(JavacTreeMaker.java:244)
	at lombok.javac.Javac.<clinit>(Javac.java:154)
	... 38 more
```

### Language / Project Type / NetBeans Component

Java Maven project

### How to reproduce

Just open the file and fill it some errors

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Archlinux

### JDK

1.8.0.131

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

The problem appears always

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
NB 16 is not supported anymore.

You are using lombok. Lombok hooks deep into the java compiler process and must be kept uptodate (sometimes you even need to wait for lombok updates) and often breaks the javac.

**Comment by bobbyw2345** [comment]
Yes, It seems that lombok is the issue.
I'll update.
Thank you very much.
Cheers

Il giorno gio 5 set 2024 alle ore 21:08 Matthias Bläsing <
***@***.***> ha scritto:
