### ISSUE TITLE
NetBeans shows dependency errors in Gradle projects that are successfully built

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#7738]
### Apache NetBeans version

Apache NetBeans 22

### What happened

After successful building entire Gradle project (JavaFX) NB shows dependency errors.

### Language / Project Type / NetBeans Component

Java Gradle project with JPMS 

### How to reproduce

git clone https://github.com/openjdk/jfx
cd jfx
git checkout tags/22+1

In NB File -> Open project -> path to jfx folder.
JFX project -> right click -> Properties -> Build -> Gradle execution -> select JDK up to 19 version
Resolve all erros
JFX project -> right click -> Open in Terminal -> $./gradlew build -x test -Dorg.gradle.java.home=/opt/jdk-17.0.2

Now if you open any module, for example javafx.controls you will get:
![Screenshot from 2024-09-07 12-28-45](https://github.com/user-attachments/assets/bba85e46-b222-4c35-9072-570e03ae3699)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.6 LTS

### JDK

Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1+8-16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by jerry-apl** [comment]
Have similar issue with Netbeans 27, java 24,gradle 9. Where netbeans can run the gradle build successfully but 
shows missing imports on some dependencies when editing. But for me it does find javafx ok, as I put the javafx libraries as a file tree in the dependencies. It seems netbeans is not able to resolve the files gradle caches in its cache.

**Comment by wrprice** [comment]
@jerry-apl could you try a nightly build?  There have been some dependency resolution fixes for Gradle 9 projects since the NB27 release.

**Comment by jerry-apl** [comment]
@wrprice I have tried the nightly build, and it fixes my problem. Thanks for the tip.

**Comment by wrprice** [comment]
@jerry-apl thanks for confirming.

I think the original issue from @PavelTurk is different from yours.  My system isn't set up to build JavaFX as I'm having a hard time getting the fonts to compile, so even Gradle on the CLI outside of NetBeans isn't building successfully for me due to issues with native code.

I did notice PavelTurk's screenshot that there's a notification bubble in the bottom right.  If you can still reproduce could you click that and find the exception + stack trace it's reporting?

On my machine, I get different stack traces depending on the Java version.  On JDK 17, I get:

<details>
  <summary>JDK 17 AssertionError</summary>

```stacktrace
java.lang.AssertionError: the result of hiddenInInternal() can't be null
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.util.Assert.check(Assert.java:95)
	at com.sun.tools.javac.code.Symbol.hiddenIn(Symbol.java:590)
	at com.sun.tools.javac.code.Symbol.isMemberOf(Symbol.java:578)
	at com.sun.tools.javac.comp.TransTypes.addBridgeIfNeeded(TransTypes.java:335)
	at com.sun.tools.javac.comp.TransTypes.addBridges(TransTypes.java:414)
	at com.sun.tools.javac.comp.TransTypes.addBridges(TransTypes.java:428)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:1214)
	at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:471)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:859)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:450)
	at com.sun.tools.javac.comp.TransTypes.visitNewClass(TransTypes.java:974)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1915)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:450)
	at com.sun.tools.javac.comp.TransTypes.visitExec(TransTypes.java:892)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1647)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:172)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1136)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:450)
	at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:485)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:960)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:144)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:1211)
	at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:471)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:859)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:450)
	at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:1233)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1661)
	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.desugar(NBJavaCompiler.java:89)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1505)
	at com.sun.tools.javac.api.JavacTaskImpl$2.process(JavacTaskImpl.java:475)
	at com.sun.tools.javac.api.JavacTaskImpl$Filter.run(JavacTaskImpl.java:519)
	at com.sun.tools.javac.api.JavacTaskImpl.generate(JavacTaskImpl.java:478)
	at org.netbeans.modules.java.source.indexing.VanillaCompileWorker.lambda$compile$3(VanillaCompileWorker.java:371)
	at org.netbeans.modules.java.source.parsing.FileManagerTransaction.runConcurrent(FileManagerTransaction.java:180)
[catch] at org.netbeans.modules.java.source.indexing.VanillaCompileWorker.compile(VanillaCompileWorker.java:360)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:363)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:274)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2749)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2626)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:579)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2625)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$scanFiles$2(RepositoryUpdater.java:3332)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.scanFiles(RepositoryUpdater.java:3290)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$FileListWork.getDone(RepositoryUpdater.java:3832)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
```

</details>

And on newer JDKs (i.e., 21) -- which might not be compatible with the tagged version of JavaFX in this report -- it's different:

<details>
  <summary>JDK 21 AssertionError</summary>

```stacktrace
java.lang.AssertionError: Method parameter without PARAMETER flag
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.util.Assert.check(Assert.java:95)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2504)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:960)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:2449)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:859)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitNewClass(Flow.java:3057)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1915)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:2335)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitLambda(Flow.java:3083)
	at com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:2038)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:2335)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExprs(Flow.java:2347)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitApply(Flow.java:3029)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1860)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:226)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1647)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:58)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitBlock(Flow.java:2609)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1136)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2512)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:960)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:2449)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:859)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:461)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2090)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:3246)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:3228)
	at com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:230)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1406)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1380)
	at com.sun.tools.javac.api.JavacTaskImpl$1.process(JavacTaskImpl.java:409)
	at com.sun.tools.javac.api.JavacTaskImpl$Filter.run(JavacTaskImpl.java:519)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:412)
[catch] at org.netbeans.modules.java.source.indexing.VanillaCompileWorker.compile(VanillaCompileWorker.java:288)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:363)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:274)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2749)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$index$0(RepositoryUpdater.java:2626)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:579)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2625)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.lambda$scanFiles$2(RepositoryUpdater.java:3332)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.lambda$runInContext$4(RepositoryUpdater.java:2119)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2117)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2098)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.scanFiles(RepositoryUpdater.java:3290)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$FileListWork.getDone(RepositoryUpdater.java:3832)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3452)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6197)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.lambda$call$0(RepositoryUpdater.java:6116)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6116)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6112)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)

```

</details>

I do note that both assertions are deep within the `javac` internal classses.

**Comment by jerry-apl** [comment]
I gave it a try, but was not able to recreate the problem. I am not sure what changed. As for javafx, I run with a local copy as I have had little luck with the plugins or getting the dependency via maven or gradle. I am also somewhat new to both maven and gradle and even netbeans. I have used eclipse for a long time. But recently got frustrated with it as I tried to move my projects from windows to Mac, and decided to give netbeans a try. I build netbeans from the source distribution and that gives me some comfort.

I dislike to many dependencies. As it always makes build a challenge. I am amazed at how many samples I have tried from GitHub that do not build at first try even though the dependencies are all explicit, given toolchain support. Still looks like a lot of work to be done to solve those problems.
