### ISSUE TITLE
Method parameter without PARAMETER flag

### ISSUE THREAD

**Issue by OlexYarm** [apache/netbeans#7752]
### Apache NetBeans version

Apache NetBeans 22

### What happened

I launched Apache NetBeans as usual on my Windows 11 desktop and Exception was reported.

### Language / Project Type / NetBeans Component

JPMS

### How to reproduce

It happened first time and error message said "Please report a bug against java/source and attach dump file".

Annotation: An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\JfxFileContentEditorMenuController.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\JfxFileContentEditorMenuController_2.dump'.
Annotation: An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\JfxFileContentEditorMenuController.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\JfxFileContentEditorMenuController_2.dump'.
Annotation: An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\JfxFileContentEditorMenuController.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\JfxFileContentEditorMenuController_2.dump'.
An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\JfxFileContentEditorMenuController.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\JfxFileContentEditorMenuController_2.dump'.
An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\JfxFileContentEditorMenuController.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\JfxFileContentEditorMenuController_2.dump'.
Caused: java.lang.AssertionError: Method parameter without PARAMETER flag
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.util.Assert.check(Assert.java:95)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2432)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:916)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:2384)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:814)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitNewClass(Flow.java:2985)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1871)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:2270)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitVarDef(Flow.java:2525)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1022)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:58)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitBlock(Flow.java:2537)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1092)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2440)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:916)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:2384)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:814)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:463)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:2013)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:3174)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:3156)
	at com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:231)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1426)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1390)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
	at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
Caused: java.lang.IllegalStateException
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:765)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:536)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:140)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

[JfxFileContentEditorMenuController_2.zip](https://github.com/user-attachments/files/17000079/JfxFileContentEditorMenuController_2.zip)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Oracle JDK 22

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

It happened first time

### Are you willing to submit a pull request?

No

**Comment by OlexYarm** [comment]
[FileContentEditor_2.zip](https://github.com/user-attachments/files/27654932/FileContentEditor_2.zip)

The issue still exists in Apache NetBeans 29 (Java 26, Windows 11):

Annotation: An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\FileContentEditor.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\FileContentEditor_2.dump'.
Annotation: An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\FileContentEditor.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\FileContentEditor_2.dump'.
An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\FileContentEditor.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\FileContentEditor_2.dump'.
An error occurred during parsing of 'F:\ProjectsJavaFX\JfxFileContentEditor\src\main\java\com\olexyarm\jfxfilecontenteditor\FileContentEditor.java'. Please report a bug against java/source and attach dump file 'C:\NetBeansCacheDir\var\log\FileContentEditor_2.dump'.
Caused: java.lang.AssertionError: Method parameter without PARAMETER flag
	at com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at com.sun.tools.javac.util.Assert.check(Assert.java:95)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2010)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:967)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:1961)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:866)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitNewClass(Flow.java:2553)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1931)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:1850)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExprs(Flow.java:1862)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitApply(Flow.java:2525)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1876)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:226)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1663)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:58)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitBlock(Flow.java:2106)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1152)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitIf(Flow.java:2457)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1632)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:58)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitBlock(Flow.java:2106)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1152)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2018)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:967)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:1961)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:866)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:445)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1605)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2742)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2724)
	at com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:216)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1420)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1384)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$0(JavacTaskImpl.java:379)
	at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
Caused: java.lang.IllegalStateException
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:765)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:536)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:140)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:330)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2012)

**Comment by epyne-titanium** [comment]
I have run into a similar issue but I am unable to share the source code that caused this
```
java.lang.IllegalStateException: java.lang.AssertionError: Method parameter without PARAMETER flag
        at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:386)
        at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:765)
        at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:536)
        at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:140)
        at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
        at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
        at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
        at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
        at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:330)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1370)
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1981)
Caused by: java.lang.AssertionError: Method parameter without PARAMETER flag
        at com.sun.tools.javac.util.Assert.error(Assert.java:162)
        at com.sun.tools.javac.util.Assert.check(Assert.java:95)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2064)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:972)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
        at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:452)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1659)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:2015)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:871)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
        at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:452)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1659)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitNewClass(Flow.java:2607)
        at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1940)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
        at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:452)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1659)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scanExpr(Flow.java:1904)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitVarDef(Flow.java:2151)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1091)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
        at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:452)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1659)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.lambda$visitClassDef$0(Flow.java:1986)
        at com.sun.tools.javac.comp.Flow$BaseAnalyzer.forEachInitializer(Flow.java:493)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:1985)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:871)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:50)
        at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:452)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1659)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2796)
        at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2778)
        at com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:223)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1409)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1373)
        at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:407)
        at com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$0(JavacTaskImpl.java:382)
        at com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:154)
        at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:382)
        ... 15 more
```

I am running Fedora 44 and installed NetBeans through the codelerity RPM. I have noticed this on NB versions 30 and 31. The project targets Java 17 via Maven properties in the pom.xml file and builds on Java 26. 

Lowering the build Java version to 17, removing the netbeans cache at `~/.cache/netbeans`, running `mvn clean` and then restarting NetBeans did not resolve the issue for me.

**Comment by epyne-titanium** [comment]
I was able to resolve my issue by cleaning out my local maven cache (`~/.m2/repository`) as well as rebuilding another project that a transitive dependency of this project that NetBeans was aware of. By "aware of", I mean that when navigating into a dependency of that project, NetBeans opened up my local source file instead of from the sources archive and I was also able to open the project directly from the source file.

**Comment by epyne-titanium** [comment]
I ran into this issue again, but this time I was able to narrow down the reason for this instance. I happened to have a `inteface` and an `enum` with the same name and the `enum` had a constructor. I have created a reproducer and have simplified it as much as possible
```java
public class MissingParameterTest {

    public interface SomeName {

    }

    public enum SomeName {
        TEST(null);

        private SomeName(String arg) {
        }
    }
}
```
