### ISSUE TITLE
A org.apache.maven.artifact.InvalidArtifactRTException has occurred.

### ISSUE THREAD

**Issue by imadbougataya** [apache/netbeans#7760]
### Apache NetBeans version

Apache NetBeans 22

### What happened

[messages.log](https://github.com/user-attachments/files/17027467/messages.log)
an exception occured after Netbeans start 

### Language / Project Type / NetBeans Component

Java Maven Web application project

### How to reproduce

just started the IDE and the exception happened

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 11

### JDK

21 x86

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
so there are several variations of this exception in the log

```
WARNING [org.netbeans.modules.java.source.indexing.JavaIndex]: Exception while checking cache validity for root: file:/C:/Java/Projets/ETPQv3/jhipster_upgrade/src/main/resources/
org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework.boot:spring-boot-configuration-processor:null:jar}: The version cannot be empty.
	at org.apache.maven.artifact.DefaultArtifact.validateIdentity(DefaultArtifact.java:162)
	at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:142)
	at org.netbeans.modules.maven.api.PluginPropertyUtils.getPluginPathProperty(PluginPropertyUtils.java:812)
	at org.netbeans.modules.maven.classpath.AnnotationProcClassPathImpl.getCompileArtifacts(AnnotationProcClassPathImpl.java:94)
	at org.netbeans.modules.maven.classpath.AnnotationProcClassPathImpl.createPath(AnnotationProcClassPathImpl.java:67)
	at org.netbeans.modules.maven.classpath.AbstractProjectClassPathImpl.getPath(AbstractProjectClassPathImpl.java:153)
	at org.netbeans.modules.maven.classpath.AbstractProjectClassPathImpl.getResources(AbstractProjectClassPathImpl.java:144)
	at org.netbeans.api.java.classpath.ClassPath.entries(ClassPath.java:363)
	at org.netbeans.modules.maven.classpath.ClassPathProviderImpl$AnnotationPathSelector.getActiveClassPath(ClassPathProviderImpl.java:685)
	at org.netbeans.spi.java.classpath.support.MuxClassPathImplementation.getActiveClassPath(MuxClassPathImplementation.java:156)
	at org.netbeans.spi.java.classpath.support.MuxClassPathImplementation.getResources(MuxClassPathImplementation.java:89)
	at org.netbeans.api.java.classpath.ClassPath.entries(ClassPath.java:363)
	at org.netbeans.api.java.classpath.ClassPath.getRoots(ClassPath.java:248)
	at org.netbeans.modules.java.source.indexing.APTUtils.listenOnProcessorPath(APTUtils.java:343)
	at org.netbeans.modules.java.source.indexing.APTUtils.listen(APTUtils.java:329)
	at org.netbeans.modules.java.source.indexing.APTUtils.create(APTUtils.java:234)
	at org.netbeans.modules.java.source.indexing.APTUtils.get(APTUtils.java:181)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer$MetadataCheck.call(JavaCustomIndexer.java:1499)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer$MetadataCheck.call(JavaCustomIndexer.java:1486)
[catch] at org.openide.util.RequestProcessor$WaitableCallable.call(RequestProcessor.java:1280)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

before that there were some TopComponent persistence exceptions, which are _usually_ harmless but they can indicate that a opened project was moved or removed and NB can't find it anymore.

Does your project specify an annotation processor somewhere without setting the version of that artifact?

**Comment by matthiasblaesing** [comment]
This should be fixed in master by https://github.com/apache/netbeans/commit/54ae9f3, @sdedic added that improvement in august.
