### ISSUE TITLE
CDNJS update library throws exception

### ISSUE THREAD

**Issue by ltheussl** [apache/netbeans#7783]
### Apache NetBeans version

Apache NetBeans 23

### What happened

In a php project when choosing Properties -> JavaScript Libraries -> CDNJS, trying to Update a library has no effect, and following exception is thrown:

```
java.lang.IllegalArgumentException: Invalid prefix or suffix
    at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:60)
    at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:125)
    at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
    at java.base/java.nio.file.Files.createTempFile(Files.java:923)
    at org.netbeans.modules.javascript.cdnjs.LibraryProvider.downloadLibraryFile(LibraryProvider.java:252)
    at org.netbeans.modules.javascript.cdnjs.LibraryCustomizer$StoreListener.updateLibraries(LibraryCustomizer.java:175)
    at org.netbeans.modules.javascript.cdnjs.LibraryCustomizer$StoreListener.run(LibraryCustomizer.java:117)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
```

### Language / Project Type / NetBeans Component

PHP project with javascript libraries

### How to reproduce

Create a php project and add a javascripr library from Properties -> JavaScript Libraries -> CDNJS. Close the dialog and manually set the version to a lower value in project.xml. Then try to update the version in the CDNJS properties.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro 22H2

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This used to work some time ago, but not in Netbeans 22 and 23

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
What is the name of the library you tried to update? The code does not look that broken, but it would break, if there would be a slash inside the name. Is that the case?

**Comment by ltheussl** [comment]
Thanks for the comment and sorry, - I should have mentioned this. It's pdfmake which I try to upgrade from 0.2.10 to 0.2.12. There is indeed a slash in some dependencies (eg Roboto-Italic.ttf).
Following your comment I tried to ugrade a different library (jszip) and that worked... however, also pdfmake used to work some time ago. Unfortunately I can't say when exactly, probably around netbeans 16.

**Comment by matthiasblaesing** [comment]
@ltheussl thanks for the info. With that this is trivial to reproduce. I created a PR, that should fix the problem (tested locally). It would be great if you could test the nightly build: 

[Checkpage](https://github.com/apache/netbeans/pull/7796/checks), [direct download](https://github.com/apache/netbeans/suites/28847143361/artifacts/1978890373)

**Comment by ltheussl** [comment]
Excellent, thanks for the quick turn-around! I confirm that it works with your build.
Cheers, -Lukas

**Comment by matthiasblaesing** [comment]
Thanks for testing!
