### ISSUE TITLE
Unexpected Exception

### ISSUE THREAD

**Issue by thetigergo** [apache/netbeans#7792]
### Apache NetBeans version

Apache NetBeans 23

### What happened

It just occurred during I remove the remaining character on each occurrence or much character during find and replace.

I am developing a web application with primefaces in server faces page. I modify the reference bean on a page and I also remove few characters in each few methods. I just only found out there was a error shown below.

### How to reproduce

This problem is not yet resolved in several previous versions.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

JDK 17

### Apache NetBeans packaging

Other

### Anything else

java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:62)
	at com.sun.tools.javac.comp.Modules.allModules(Modules.java:1226)
	at com.sun.tools.javac.model.JavacElements.getAllModuleElements(JavacElements.java:132)
	at org.netbeans.modules.java.source.ElementUtils.getTypeElementByBinaryName(ElementUtils.java:49)
	at org.netbeans.api.java.source.ElementHandle.getTypeElementByBinaryName(ElementHandle.java:702)
	at org.netbeans.api.java.source.ElementHandle.resolveImpl(ElementHandle.java:161)
	at org.netbeans.api.java.source.ElementHandle.resolve(ElementHandle.java:130)
	at org.netbeans.modules.web.el.completion.ELJavaCompletionItem$ElementHandleAdapter$1.run(ELJavaCompletionItem.java:315)
	at org.netbeans.modules.web.el.completion.ELJavaCompletionItem$ElementHandleAdapter$1.run(ELJavaCompletionItem.java:311)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:60)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:445)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:428)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:399)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:433)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.web.el.completion.ELJavaCompletionItem$ElementHandleAdapter.document(ELJavaCompletionItem.java:311)
	at org.netbeans.modules.web.el.completion.ELCodeCompletionHandler.documentElement(ELCodeCompletionHandler.java:729)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionDoc.<init>(GsfCompletionDoc.java:91)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionDoc.create(GsfCompletionDoc.java:108)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionProvider$JavaCompletionQuery.resolveDocumentation(GsfCompletionProvider.java:528)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionProvider$JavaCompletionQuery$1.run(GsfCompletionProvider.java:315)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:197)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:180)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.modules.csl.editor.completion.GsfCompletionProvider$JavaCompletionQuery.query(GsfCompletionProvider.java:320)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment]
Please provide a minimal reproducer.
