### ISSUE TITLE
A java.lang.NullPointerException has occurred.

### ISSUE THREAD

**Issue by jatinbht** [apache/netbeans#7828]
### Apache NetBeans version

Apache NetBeans 23

### What happened

java.lang.NullPointerException: Cannot invoke "org.json.simple.JSONArray.iterator()" because "array" is null
	at org.netbeans.modules.web.webkit.debugging.api.Runtime.getRemoteObjectProperties(Runtime.java:77)
	at org.netbeans.modules.web.webkit.debugging.api.debugger.RemoteObject.getProperties(RemoteObject.java:192)
	at org.netbeans.modules.web.webkit.debugging.api.console.RemoteObjectMessage.getSubMessages(RemoteObjectMessage.java:69)
	at org.netbeans.modules.web.webkit.tooling.console.BrowserConsoleLogger.logMessage(BrowserConsoleLogger.java:316)
	at org.netbeans.modules.web.webkit.tooling.console.BrowserConsoleLogger.logMessage(BrowserConsoleLogger.java:210)
	at org.netbeans.modules.web.webkit.tooling.console.BrowserConsoleLogger.messageAdded(BrowserConsoleLogger.java:152)
	at org.netbeans.modules.web.webkit.debugging.api.console.Console.notifyConsoleMessage(Console.java:153)
	at org.netbeans.modules.web.webkit.debugging.api.console.Console.access$100(Console.java:38)
	at org.netbeans.modules.web.webkit.debugging.api.console.Console$InputCallback.line(Console.java:225)
	at org.netbeans.modules.web.webkit.tooling.console.BrowserConsoleLogger$ConsoleReader.run(BrowserConsoleLogger.java:658)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
[messages.log](https://github.com/user-attachments/files/17248135/messages.log)

### How to reproduce

No idea

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows x64

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I am reporting because I was prompted to by Netbeans 23.

"A java.lang.NullPointerException has occurred.  If you are running the [latest](https://netbeans.apache.org/download) version of NetBeans you can [report this](https://netbeans.apache.org/nb/report-issue), including a copy of your messages.log file as an attachment.  The messages.log file is located in [this folder](file:///C:/Users/HP/AppData/Roaming/NetBeans/23/var/log/)."

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
this would require some form of a reproducer otherwise its impossible to investigate. Seems like the maven runner plugin is installed this happened during debugging.
