### ISSUE TITLE
Impossible to build web app project with ant with binary format newer than java 8

### ISSUE THREAD

**Issue by PCore-D** [apache/netbeans#7935]
### Apache NetBeans version

Apache NetBeans 23

### What happened

error when try to build with binary format newer than java 8
```
Exception in thread "main" java.lang.IllegalArgumentException: PWC6309: Illegal compilerSourceVM: 17
	at org.apache.jasper.JspC.setCompilerSourceVM(JspC.java:684)
	at org.netbeans.modules.web.project.ant.JspC.main(JspC.java:55)
```

### Language / Project Type / NetBeans Component

Java web application with Ant

### How to reproduce

create new project and try to build with binary format > 8

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

debian

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Please provide a demo project reproducing the problem, with steps to reproduce.
