### ISSUE TITLE
High CPU load when screen is off - Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by shadowfly256** [apache/netbeans#8079]
### Apache NetBeans version

Apache NetBeans 24

### What happened

I switched my monitor off to preserve some power while idling. My CPU started getting hot immediately. I looked at my TaskManager and found NetBeans using one CPU core at 100%.

I then used VisualVM to profile NetBeans to see if it's "easy" to fix, and the terminal output of VisualVM filled with exceptions like this:

```
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:305)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:239)
	at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1111)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5057)
	at java.desktop/javax.swing.JLayer.paintImmediately(JLayer.java:431)
	at java.desktop/javax.swing.plaf.LayerUI.paintImmediately(LayerUI.java:728)
	at java.desktop/javax.swing.JLayer.paintImmediately(JLayer.java:426)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5057)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Then i realized that both NetBeans and VisualVM's GUIs were glitching:
![Screenshot_20241220_170149](https://github.com/user-attachments/assets/64a12613-de5a-4122-b864-0d59f681709f)
So i closed NetBeans, and switched off my screen. My CPU shot to 100% again. So yes, **this bug is not NetBeans exclusive**.
Without NetBeans or VisualVM my CPU remains cool.

Then i tried a simple Java GUI program, as i thought this might be a Java bug. But no, a simple Java JFrame does not create problems.
This is the reason why i did not report this to OpenJDK.

I hope this is not the wrong place for this bug. Maybe this should be an OpenJDK bug, but i am sure you can tell me.

Thanks for the awesome FOSS IDE by the way.

### Language / Project Type / NetBeans Component

Java Ant application

### How to reproduce

1. Get a clean NetBeans install
2. Start NetBeans
3. Turn your monitor off (with a physical button)
4. Observe no CPU load
5. Create a new Ant application
6. Turn your monitor off
7. Observe high CPU load, and NetBeans reporting exception
8. Close Ant project
9. Close NetBeans
10. Start NetBeans
11. Turn your monitor off
12. Observe no CPU load

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Gentoo Linux 2.17 KDE Plasma Version: 6.2.4 Kernel Version: 6.6.62-gentoo

### JDK

Gentoo host: openjdk 17.0.13 2024-10-15 >> NetBeans Flatpak: jdk21

### Apache NetBeans packaging

Other

### Anything else

NetBeans package: Flatpak -  org.apache.netbeans//24

Reproducable: Always

VisualVM "source of load":
![Screenshot_20241220_170241](https://github.com/user-attachments/assets/967bad9c-9a8b-472e-8f82-39280bfa56df)

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
@shadowfly256 thanks a lot for taking your time and posting such detailed bug report.

**Comment by mbien** [comment]
I am wondering what your system does when all screens are unplugged. In my case it keeps at least one graphics device.

```java
    public static void main(String[] args) {
        JFrame frame = new JFrame("test");
        frame.setSize(400, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        new Thread(() -> {
            while(true) {
                try {
                    Thread.sleep(2000);
                    SwingUtilities.invokeLater(() -> {
                        List<GraphicsDevice> devices = List.of(GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices());
                        GraphicsConfiguration gc = frame.getGraphicsConfiguration();
                        System.out.println("s: %s, d: %s, gc: %s, devs: %s".formatted(frame.isShowing(), frame.isDisplayable(), gc, devices));
                    });
                } catch (InterruptedException ex) {
                    return;
                }
            }
        }).start();
    }
```
```
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=1],vis=0x21], devs: [X11GraphicsDevice[screen=0], X11GraphicsDevice[screen=1]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=1],vis=0x21], devs: [X11GraphicsDevice[screen=0], X11GraphicsDevice[screen=1]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=1],vis=0x21], devs: [X11GraphicsDevice[screen=0], X11GraphicsDevice[screen=1]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=1],vis=0x21], devs: [X11GraphicsDevice[screen=0], X11GraphicsDevice[screen=1]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x21], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x21], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x21], devs: [X11GraphicsDevice[screen=0]]
```
I unplugged both screens and the frame still had a graphics configuration and a device assigned. So I likely won't be able to reproduce this on gnome / cinnamon. (also NB 24 was doing fine running in the background without exceptions in the log)

**Comment by shadowfly256** [comment]
For me, the output is just like it is for you:
```
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
s: true, d: true, gc: X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x45], devs: [X11GraphicsDevice[screen=0]]
```
When i select this program in VisualVM, and turn the screen off, nothing happens.
But when i maximize the test window, and turn the screen off, then exceptions like this are generated:
```
SEVERE [global]
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
        at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
        at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:305)
        at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:239)
        at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1112)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1557)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Somehow the Exceptions say NetBeans even though i made sure to close NetBeans.

As for NetBeans: Widowing NetBeans does not protect it from the bug (at least not for me).
As for VisualVM: Windowing VisualVM does not protect it from the bug. When i select no program to profile, VisualVM does not output anything when i turn the screen off. When i select the test program, or VisualVM as target for the profiler, the following exceptions are generated:
```
SEVERE [global]
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
        at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
        at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:305)
        at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:239)
        at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1112)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1557)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
So i don't know if these Exceptions are form the test program or VisualVM. Unfortunatley i don't know how to get the test program's exceptions without VisualVM.

Journal while i turn the screen off:
```
journalctl -b --follow
Dec 21 18:51:48 SHADOWFLY-03 kwin_wayland_wrapper[1178]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Dec 21 18:51:53 SHADOWFLY-03 kwin_wayland_wrapper[1178]: qt.qml.context: file:///usr/share/kwin/aurorae/AuroraeMaximizeButton.qml:54:9 Parameter "mouse" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead.
Dec 21 18:51:55 SHADOWFLY-03 polkit-kde-authentication-agent-1[1429]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kded6[1346]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kde.plasmashell: requesting unexisting screen available rect -1
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kde.plasmashell: requesting unexisting screen available rect -1
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kde.plasmashell: requesting unexisting screen available rect -1
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kde.plasmashell: requesting unexisting screen available rect -1
Dec 21 18:51:55 SHADOWFLY-03 dolphin[2496]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 DiscoverNotifier[1691]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 konsole[2691]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 org.kde.kwalletd6[2101]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kactivitymanagerd[1425]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kdeconnectd[1668]: 2024-12-21T18:51:55 qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1679]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 yakuake[1672]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 xdg-desktop-portal-kde[1431]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1934]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1936]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1935]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1933]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1842]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1937]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1931]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 kalendarac[1932]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 org_kde_powerdevil[1430]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:370:21: Unable to assign [undefined] to bool
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:238:17: Unable to assign [undefined] to bool
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:370:21: Unable to assign [undefined] to bool
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:238:17: Unable to assign [undefined] to bool
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kf.plasma.quick: Exposed with no visual parent. Window positioning broken.
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kf.plasma.quick: Exposed with no visual parent. Window positioning broken.
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kf.plasma.quick: Exposed with no visual parent. Window positioning broken.
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kf.plasma.quick: Exposed with no visual parent. Window positioning broken.
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kf.plasma.quick: Exposed with no visual parent. Window positioning broken.
Dec 21 18:51:55 SHADOWFLY-03 plasmashell[1396]: kf.plasma.quick: Exposed with no visual parent. Window positioning broken.
```

**Comment by shadowfly256** [comment]
I just tried to reproduce the bug on my laptop, but i was unable to reproduce it:
>OS: Kubuntu 24.04
>KDE Plasma: 5.27.11
>Kernel: 6.8.0-51-generic
>Graphics: X11

So maybe we need Wayland and or Plasma 6 for the bug to show up.
Or maybe there is just something wrong with my Gentoo installation and nobody else is affected but me.

**Comment by mbien** [comment]
I mean the cause for this is likely that the system (e.g wayland) reports a zero sized screen/frame or creates zero sized images/buffers. However I am more interesting in the defensive programming aspect of it. One exception is fine, but it it causes a loop and pins one core to 100% it would be good to check if we can somehow prevent that.

There is only one stack frame of NB code on the trace - and it doesn't do a lot. However, it looks like it is possible to turn that queue off by changing a property (`TimableEventQueue.install=false`) in `platform/modules/org-netbeans-core.jar#org/netbeans/core/Bundle.properties`. (btw it indeed is `Tim` not `Time`, which was probably a typo)

We should also not run VisualVM and NB at the same time while investigating since both are affected by this issue.
https://github.com/async-profiler/async-profiler
is a nice tool which can profile on the process level. Default output are flame graphs which show active areas.

I would also give the latest update of JDK 23 a try, since not all fixes are backported.

**Comment by shadowfly256** [comment]
I continued with my testing:
#### Reproducability
I tried to reproduce the bug on Arch (Actually Garuda, Wayland, Plasma 6, JDK21) but the error did not occur. **So there is probably nobody else affected but me.**
#### TimableEventQueue.install=false
I switched this off in `~/.local/share/flatpak/app/org.apache.netbeans/x86_64/stable/83ec4ab652c2b699b32d25fa15b286a2e0c97166a208554fe1654013c6638098/files/netbeans/platform/modules/org-netbeans-core.jar`. The stack traces still look the same, and NetBeans still detects those errors.
#### Profiling
I ran the test program with async-profiler like this: `java -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -jar JavaApplication.jar` and `./asprof -d 30 -e cpu -f cpu.html PID`:
##### Without turing off the screen
![Screenshot_20250106_162910](https://github.com/user-attachments/assets/06d13beb-7d71-46bb-9825-baef1ddf6240)
##### With turning off the screen
![Screenshot_20250106_162917](https://github.com/user-attachments/assets/045e693d-8cbb-42de-9e56-efba8bed17c0)

Either way, async-profiler does not print any stack traces to the terminal.

I guess it's best to close this, as it's just me who is affected.

**Comment by mbien** [comment]
> I tried to reproduce the bug on Arch (Actually Garuda, Wayland, Plasma 6, JDK21) but the error did not occur.

good to know. I did also check some wayland distributions and couldn't reproduce it. 

> I guess it's best to close this, as it's just me who is affected.

ok, lets hope it fixes itself for you during a system update at some point.
